### ISSUE TITLE
Thief Evasion Bonus trait may be broken. 

### ISSUE THREAD

**Issue by Cheezcakee** [EdenServer/community#106]
Today on the Adamantoise fight, I used a total of 6 shadows with a haste tp set. Evasion on my ninja felt fine, but I think the evasion bonus trait of thief isn't working properly. I never played thief in retail, so i'm not sure if thief is supposed to evade like 80% of attacks on IT mobs or not.

**Comment by tectal831** [comment]
I have noticed Evasion is pretty overpowered as well. I dodge way too frequently on paladin

**Comment by Cheezcakee** [comment]
I don't think evasion is broken, just the Thief Bonus trait. I didn't evade hardly at all on Ninja while fighting behemoth, but adamantoise couldn't hit me on thief. Also the Goblin Gurneyman has about the same accuracy as Adamantoise lol. That's definitely not working.

**Comment by gweivyth** [comment]
Yeah I've observed the same thing while breaking trial weapons. Barely went through 20 shadows the entire time. I don't have any other jobs to compare it to though so I sort of just figured that was normal.

**Comment by beauxq** [comment]
Note that Adamantoise is below level 75. I remember evasion working well on him on retail.

**Comment by godmode** [comment]
Good call Beaux. I’m going to keep this issue open for a bit more  but if you guys notice something weird let me know the level and mob fighting. Thanks!

**Comment by gweivyth** [comment]
That would make sense then. I was fighting Robber Crabs (easy prey @ 75) so maybe working as intended? 

I don't know how to tell. I only have warrior to compare with and their evasion is laughable.

**Comment by Serephim** [comment]
No THF is not supposed to evade 80% on IT mobs. Maybe on like an EP.

**Comment by roriffxi** [comment]
https://www.youtube.com/watch?v=uZGf0-Zy-dY

I didn't listen to sound so I don't know if he says what his characters skill is at, but here is a Thief in not that amazing of gear skilling up (so not capped) evasion against a Tough colibri.  The colibri hits 15 out of 33 attacks in the video.

Getting 80% against a DC mob doesn't seem out of the realm to me and I remember watching many thieves soloing a NM that I thought would for sure kill them and it didn't because it couldn't touch them back in retail.

**Comment by godmode** [comment]
Please reopen if this is an issue.
