### ISSUE TITLE
Hitting the marquisate

### ISSUE THREAD

**Issue by yuhsho** [EdenServer/community#1074]
I’m trying to get my thf af boots. Have done all the quest tells me to do go to Garlaige citadel and ??? Do nothing

**Comment by yuhsho** [comment]
I talked to nanaa mihgo in windiest went to Jueno trade grenades then to mhaura for the incense go to citadel hit ??? Near entrance for rocks nothing go to I-9 and H-9 for those ??? And get nothing there either

**Comment by Aviglug** [comment]
I have the same issue as above. Here are the details.

3.0 Client
For this quest you are supposed to examine multiple ??? in a specific order with the key item Bomb Incense. Nothing happens when I examine the initial one. I have examined every single one and nothing happens. Only twice, each on separate occasions, a random one will display the message "You feel a presence". They were different ones each time. I checked all the ones before and after the first banishing gate. I made sure that I was not getting the "Target is out of range" message. Upon examining the ???, the cursor goes away and nothing happens; no dialogue is produced. You are supposed to get a CS at the initial one, I believe. I have talked to gms and a dev already. They say my parameters are correct but I am still unable to progress with this quest. Again, I have the necessary key item Bomb Incense in my inventory. Please help!

**Comment by godmode** [comment]
Make sure you’re actually examining the first one not the second one.

**Comment by Aviglug** [comment]
I am. The one at I-9 closest to the gate.

**Comment by godmode** [comment]
That is not the first one. That's the second one.

**Comment by Aviglug** [comment]
The one closest to the gate on is labeled as 1 on the map on the wiki. I've examined all the ???. Which is the first one?

**Comment by godmode** [comment]
If you examined them both outside of the gate it should be good. I don’t think that there is a message there that should be displayed though.

**Comment by godmode** [comment]
There is some code I just put in review that makes the process more like retail. It should be deployed next patch. If the next patch comes out and you are still unable to continue please place a GM ticket and mention issue 1074.
