### ISSUE TITLE
Charmed Monster/Jug pet vs Monster ignores any Physical Damage Resist/Reduction

### ISSUE THREAD

**Issue by FeliaEden** [EdenServer/community#1140]
I know someone commented about how "when charming a slime, they lose their physical resistance". 

However, after further testing I believe in the damage calculation done when a monster damages another monster, any physical resistance is ignored. I've tested charmed mobs/Jug pets vs Slimes/Elementals. They rip right through them doing normal damage. I don't have summoner, dragoon, and/or puppetmaster high enough to test if avatars/automatons/wyvern act the same way.

**Comment by FeliaEden** [comment]
Also to note, I tested Even Match Bat (charmed) vs Even Match Slime, and Even Match Slime (charmed) vs Even Match Bats and saw the same numbers. Also used the slime/bats vs other monsters of respected level. 

Slimes should have a 50% pierce/slashing, and 75% blunt resistance. Elementals should have high physical resistance as well. So it should be pretty clear if they resistance was in effect.

**Comment by gweivyth** [comment]
Haven't played BST on Eden yet, but I've played it extensively on other DSP servers.  It's like that on basically all of them.  On retail you could VERY clearly tell the difference in pet defenses.  Slimes especially.  

There used to be a strategy for Phomiuna Aqueducts farming on retail where you would charm one of the higher level slimes, 2 hour it, and smash through a bunch of Fomors because it could easily survive multiple encounters with them if you healed them up with biscuits.  It's documented in plenty of places on the internet.  [Here's just one example](https://www.bluegartr.com/threads/67126-Phomiuna-Aqueducts-Subligar-Solo-Farming?s=49600cefce0a480df1dd49adc20db0e5&p=2395746&viewfull=1#post2395746), and I didn't really even search very hard.
