### ISSUE TITLE
Damp Scroll

### ISSUE THREAD

**Issue by Arlen90** [EdenServer/community#1142]
I just fished up a Damp Scroll, even though I've completed the quest "Secret of the Damp Scroll" - It shouldn't be possible once this quest is completed.

Edit: Not 100% if this was changed later on or not. Retail it's not possible, anyhow. Would seem a weird thing to nerf.

**Comment by Shoruto** [comment]
While wikia during post era does state you shouldn't be able to catch these again after completing the quest, I found someone post on FFXIAH that they still fished them up after completing the quest.  I'm also seeing people post that they fished for hours and days after completing it and haven't fished it up.  I only found one post during era and they weren't able to fish it up.

**Was Fished Up**
7/26/2013 - https://www.ffxiah.com/item/1210/damp-scroll 

**Wasn't Fished Up**
6/14/2006 - http://ffxi.allakhazam.com/db/item.html?fitem=3233
10/7/2009 - https://www.ffxiah.com/item/1210/damp-scroll

**Comment by Setz0r** [comment]
yeah. this is a strange scenario because normally quest requirements dictate that you be ON the quest to get something.  in this case, you don't actually flag this quest, so the quest requirement i put on the damp scroll made it impossible to catch, so i just made it full time catchable until i could implement a "can't catch if X quest has been completed" system

**Comment by Setz0r** [comment]
this item is catchable at any time.  items can just be hard to obtain when you are actually trying to get them.
