### ISSUE TITLE
Conquest Reward Bug

### ISSUE THREAD

**Issue by stretchfox** [EdenServer/community#1179]
I'm unable to buy anything with conquest points.  Even when buying a warp or reraise scroll, it says I don't have enough points.  I have plenty of points.  Char name = Naturally

Thanks!

**Comment by godmode** [comment]
Have you read this post? https://www.edenxi.com/forums/viewtopic.php?f=31&t=68
If there is still an issue please comment which items you are unable to purchase and how much CP you have and how much they cost.

**Comment by stretchfox** [comment]
Yea, I read that before and I'm not sure this is the same issue (might be related).  I have 622 points available.  The warp scroll shows it's available for 10 points.  When selected, it says I don't have enough points.

**Comment by HammerhandsKupo** [comment]
Warp Scrolls and Reraise Scrolls are now era values, as written in Godmode's post above. Era values are 750 CP each.  It will still say 10 CP when you go to buy them (due to them being unable to program them to say 750), but when you check your CP in Status>Currencies you will see the correct amount spent.
