### ISSUE TITLE
Bloody bolts not draining correctly

### ISSUE THREAD

**Issue by Altnob** [EdenServer/community#1191]
Bloody bolts are supposed to drain HP even if you're full hp. The log does not show this but it is supposed to do the full damage.

As of now if you're full hp it says drained 0 hp. It isn't supposed to show any amount drained at full HP but it is still supposed to drain more than the initial shot. 

https://ffxiclopedia.fandom.com/wiki/Talk:Bloody_Bolt

Also noted: bloody bolts at 75 are draining WAY too little HP. I remember effectively draining 50+ on EP/DC mobs but I seem to cap out around 18 on era. 18 drain bloody bolt is essentially useless at 75.

**Comment by Wiggo32** [comment]
you're right, bloody bolts on dsp are not as effective as they are on retail. the problem we have at this point in time is, we need to get lots and lots of retail data to more accurately tune the formula to be more accurate. and that is going to require a lot of time and a lot of data collection. it's something we would like to see happen eventually though, so thank you for posting the issue so we can keep in on the "list".

**Comment by archfiendrubicante** [comment]
I seem to remember in retail that the upper limit of the bolts draining effect was 75, and that the "resisted amount" was generally 37.

As it is now the bolts seem to be way under-tuned. They barely return any HP at all for a level 25 consumable.

**Comment by Mozzy4Ever** [comment]
Gunna add that bloody bolts never drain HP from Yowie and Sozu Rogberry. There's probably other mobs they don't seem to work on. THF75 with 286 RATK, 68 INT, and 230 Marksmanship. Maybe there's a correlation between Sozu/Yowie that could give more insight as to why? I'm not sure what their INT is set to. Neither mobs have a weakness to piercing or resistance to dark magic (including that info cause of the report @Wiggo32 referenced to here)

**Comment by Drognand** [comment]
Any information you guys have keep posting it here I have been on and off working on the DSP code for the last month on bolts. I am about to set up my own test server and will use all relevant data and what I used to see after thousands of hours of using them on retail in era to try to get them to work correctly.

**Comment by Drognand** [comment]
Proof towards what i submited for the bolts will be below:

Site Refrenced with needed information:
https://ffxiclopedia.fandom.com/wiki/Bloody_Bolt?oldid=369925 (pre Cut Of Date cyclopedia page)
https://ffxiclopedia.fandom.com/wiki/Bloody_Bolt (Current Retail information alot more indepth)


These are the only 2 with relevant data on how the bolt drains that have information on the way it may be coded. IDK if Setz can find more.

Volkaru's Retail SS's of capped Bolt Drain on retail
https://cdn.discordapp.com/attachments/635827080533114881/668454416034168842/ffxi_2019.10.21_06.43.51.png
https://cdn.discordapp.com/attachments/635827080533114881/668454412469141524/ffxi_2019.10.21_06.44.43.png
https://cdn.discordapp.com/attachments/635827080533114881/668454409700769812/ffxi_2019.10.21_06.45.30.png
https://cdn.discordapp.com/attachments/635827080533114881/668454406303252480/ffxi_2019.10.21_06.50.25.png
https://cdn.discordapp.com/attachments/635827080533114881/668454376234549258/ffxi_2019.10.21_06.50.25.png
https://cdn.discordapp.com/attachments/635827080533114881/668454373231427594/ffxi_2019.10.21_06.53.50.png
https://cdn.discordapp.com/attachments/635827080533114881/668454367770443786/ffxi_2019.10.21_07.00.40.png
https://cdn.discordapp.com/attachments/635827080533114881/668454365765566531/ffxi_2019.10.21_07.04.31.png

**Comment by Balrahn** [comment]
So I've been using bloody bolts on my 75THF for a bit and they seem very off.
On Tonberries lv 60-67 I usually drain 20+
Moblins level 75-79 I'm draining 2-5hp.

My marksmanship is capped, I'm not using gear to enhance my marksmanship and I'm not using INT.

I'm not sure about tonberries, but bloody bolts should be effective against beastmen.

I've been trying to find some info on old forums about how much I should be draining, and I can't find anything definite. Adding sources here:

https://ffxi.allakhazam.com/db/item.html?fitem=3162
https://ffxi.gamerescape.com/wiki/Talk:Bloody_Bolt

**Comment by Balrahn** [comment]
Heres a vid of a 75thf draining 36hp from Alky.
https://www.youtube.com/watch?v=crmdebamybA

**Comment by ThoseWhoFight** [comment]
> Heres a vid of a 75thf draining 36hp from Alky.
> https://www.youtube.com/watch?v=crmdebamybA

You can see him drain 73 HP back three different times later on in the video around the 2:00 mark as well. I can say for certain they don't drain anywhere near that on Eden currently. Maybe 20-30 max.

**Comment by Balrahn** [comment]
This vid is JP, but can still see the amount drained.
https://www.youtube.com/watch?v=jNvM5GOTPHM

1:48 75thf drains 43hp from Narasimha

Following drains are all on the same Marid
3:24 drains 30hp from Marid
3:33 drains 34hp from Marid
4:22 drains 58hp from Marid
4:34 drains 39hp from Marid
4:40 drains 43hp from Marid
5:07 drains 25hp from Marid
5:13 drains 34hp from Marid

6:24 drains 25hp from Frostmane
7:22 drains 53hp from Frostmane

7:38 drains 36hp from Tyrannic Tunnok
8:35 drains 36hp from Tyrannic Tunnok
9:01 drains 44hp from Tyrannic Tunnok
9:14 drains 37hp from Tyrannic Tunnok

**Comment by Balrahn** [comment]
https://www.youtube.com/watch?v=m81Rj40BJhs
72thf marksmanship not capped.
2:12 drains 72hp from Colibri
2:20 drains 71hp from Colibri
3:00 drains 35hp from Colibri

**Comment by Balrahn** [comment]
https://www.youtube.com/watch?v=FbRkNqGi02c


0:43 97hp and 98hp drained from Mourioche
0:49 97hpx2 drained from Mourioche
1:27 98hp drained from Mourioche

**Comment by Balrahn** [comment]
75thf

https://www.youtube.com/watch?v=-2Vm-Hz9fHE

2:34 drains 32hp from Khimaira 13
2:58 drains 32hp from Khimaira 13
3:22 drains 32hp from Khimaira 13
3:33 drains 32hp from Khimaira 13

**Comment by Ladypinky** [comment]
I've always been saddened by private server's bloody bolt damage. I remember back in the day I would impress my party by tanking lv25war with defender + racc gear & food and be able to solo mandys in the jungles, especially with /rng and sharpshot. I remember my taru draining about 80-88 per bloody bolt on the mandies. So as you can imagine I murdered them even at lv25~. It seems crazy to me that they only do 20-30 drain on easy prey mobs. I think the base on bloody bolts should be around 70 per drain, then it's affected by INT decently as it wasn't uncommon for a taru to drain 80+ from exp mobs granted unresisted. I was always sad more people didn't use them as DPS in exp parties, but they were by far the most expensive bolt in era.

**Comment by E5una** [comment]
I'm not close to this topic but FWIW I saw a 75 THF Bloody Bolt a gigas in Korroloka Tunnel for ~125 a few days ago. Sorry if this is derailing in any way, just saw some numbers and wanted to provide info on what I saw recently.

**Comment by dowzer** [comment]
I’ve noticed anything higher than even match, especially against level 80+, the amount drained is reduced to single digits. 
For thieves looking to solo higher level content, I recommend using au lait regen drinks and turning around to regen hp without feeding the monster TP. 
In the past I used bloody bolts without having to delay fights to regen hp but that’s not possible on Eden until they’re fixed.

**Comment by archfiendrubicante** [comment]
I remember very clearly when I was playing leveling ranger in Yuhtunga on
retail that I would be able to pop mandies for at minimum 75, and those
were IT mobs.

**Comment by dowzer** [comment]
Some retail testing:

They will either not drain HP, resist for half of the drain amount, or drain the full amount.

INT 55 vs Mt. Z Ebony Pudding INT 89 = 21 or 42 HP drained

INT 55 vs Bhaflau Greater Colibri INT ? = 35 or 71 HP drained

- 554 shots
- 210, no HP drained
- 131, 35 HP drained
- 213, 71 HP drained

**Comment by dowzer** [comment]
Images to support my previous comment
https://i.imgur.com/2N73CxL.png
https://i.imgur.com/gMssaFC.png

Wild Sheep HP drained capped at 92 with INT 84 and stayed at 92 with INT 113
https://i.imgur.com/uZCgOtJ.png
https://i.imgur.com/QCQoopw.png

Goblin Reaper in Gustav drain capped at 92 with INT 96 and stayed at 92 with INT 97
https://i.imgur.com/nhVc9qu.png

Goblin Reaper in Gustav drain fell to 91 with INT 95
https://i.imgur.com/rhQOQef.png

Bloody Bolts will receive a 1.25 piercing bonus modifier
https://i.imgur.com/9T9EzCF.png

Piercing bonus mobs with dark  resistance, specifically large bats will halve the damage
https://i.imgur.com/5sA4VI1.png

**Comment by dowzer** [comment]
AFK'd and came back to this NM, couldn't drain more than 46 HP
https://i.imgur.com/pQq555E.png

**Comment by dowzer** [comment]
Magic Defense Bonus doesn't reduce the amount of HP drained
https://i.imgur.com/DjYfWUH.png
https://i.imgur.com/LTDKflm.png

Confirming those pots have MDB
https://i.imgur.com/8fDvQsB.png

**Comment by Ladypinky** [comment]
way to go dowzer <3! those numbers are more aligned from what i remember. like a too weak mob shouldn't really be able to drained for more than like 90ish unless you have an incredible INT+ set regardless of if you're lv30 or 75 fighting a level 10 mob and even then the +INT wouldn't do that much, like at 75 in a full INT gear set maybe you'd get up to 110 drain on a wild sheep lol. I always thought it was kind of a waste of gear slots to carry around all that INT+ for an extra 8-12 HP on a T mob when you're already draining like 78+ at lv75(i mean i might see differently now but when i was a child :3). Thus again, level doesn't matter so much. Right at LV25 you'll be draining for about 80 on IT mobs, of course at lv25 you won't be draining 80 off mobs that are like lv80, but mobs like 5-8 levels higher than you could still drain 80, just the resist rate isn't ideal for soloing all types of ITs, mostly just mandies. war/blu could probably tank like literally anything 25-75 without the need for a healer or PL in exp parties, especially against birds. you get a lot less resists, and bolts would drain at the higher end of cap. so if you were a hume you'd be draining like 88-92 off birds/bees rather than 76-78ish. if you were a taru you'd probably go from like 85-88 to like 92-95. the formula for how they work must be wild. i don't know if i can begin how to comprehend to code it. it seems complex. it must depend on character level, average INT across all races and then platform from there starting at a base of roughly 75hp drain for hume, sorry but galka are horrible with bloody bolts, i imagine their base drain is around 68, elvaan around 72, hume 75ish, mithra 78ish, taru 80ish.

**From a 2005 Allakhazam post
 "10-20 drained each hit?

I solo'd Even Match mobs when raising Marksmanship from over 60 levels below cap, thanks to RNG great accuracy I hit almost every time. Mobs would hit me for about 30-40 dmg, and my HP would INCREASE. I was draining anywhere frmo 40-80 hp. Something has to be said about Bloody Bolts when you can solo a Tough tiger with only one Utsusemi cast when they can do Razor Fangs for easily over 100 dmg. These are UBAR."**

in my experience the higher the mob level difference the higher chance to resist. INT difference didn't really make much of a difference. like at level 25 on war whether you fought a mandy or a goblin you'd still drain a good 80ish if unresisted, and that's with out focusing on INT+ AT ALL. how ever, you would get resisted quite a bit, like 50% of the time and about 20% of the time on IT you'd just straight up not even see the additional effect proc. 

bloody bolt's def shouldn't be draining 140-180 from too weak mobs. a bug fix will be great for somethings, and not so great for other things.

I find it relatively annoying that i can only drain like 40ish off easy prey mobs with full INT gear/food but it gets the job done well enough. bleghhh it's more of knowing i could be draining 90 off an EM naked with just a lv1 xbow + bolts >_>! I am also quite aware that a true fix/insight into this issue will transform eden and the meta xD! could you imagine what attohwa burns would've been like with bloody bolts draining 78-90 xD!! I do also remember certain mob families being super resistant. Elementals are by far the worst. Ahriman being drained for 42ish is bad but i remember elementals being like 4-12 drain- unresisted  (yes even at lvl75 in full INT on a level like 20 ele- which i know is also probably the more devastating result of an eden fix since it's kind of wild to be draining them for 140+ on eden lol)

<3 sorry this is such a long post. I is just excited Dowzer is getting some werk did on this issue as far as retail testing. it's very interesting they do so little on ahriman since they're flying. i imagine if they weren't flying, bloody bolts would do even less than that 42 lol. Unfortunately those allakhazam posts don't have much info on how they worked but it's something lol.

**Comment by dowzer** [comment]
Holy cow, where do I start? Thanks! I'm not sure exactly how to create or modify the formula either, hopefully this data will help solve it. I'm still wondering if anything was changed over the years, when I was testing Greater Colibri it was very surprising the resist rates were strictly full damage, half damamge, or no proc. I could have sworn I remember 1/8, 1/4, 1/2 but I guess I was wrong. It still falls in line, I remember fighting very tough mobs and the proc rate wasn't 100%, but it certainly wasn't draining for 0 or single digits. 

Looking forward to any other questions, comments, or methods to clarify how they're supposed to work!

**Comment by Ladypinky** [comment]
i think armored goblins get some extra resistance rate to them. i think that's why it wasn't as ideal to fight goblins with no healer just war/rng bloody bolt tank. they had a lot more 50% resist rate drains but are also more deadly than those silly mandies. goblin ranger/mage types (light armor) always seemed kinda squishy against bloody bolts though. there's def something about families/armor types that just make them more resistant. i don't recall quadavs, they might've been neutral and yags were weaker to them(almost no resists but still no extra drain dmg, just the extra phys dmg.) i do remember there was a JP warrior who solo'd to 75 on my server back in the day. i always wondered how he did it but then i realized he used a ton of bloody bolts lol.

 in hindsight he must've been my inspiration to try war/rng on mandies. war/rng on mandies at 25 in jungle was lit. with defender and defense food they'd hit you for next to nothing but each bolt would do 100 dmg. they literally had no hope. you could get like chain3-4 solo if you saved sharpshot for the last 2. they melted. and this was when i was a child, like back in 2006 when i was still in highschool. unfortunately out of all the times i did it, no one else ever did it ._.a. i think its cuz when you're at 100% hp it'll show that you didn't drain any HP but you're still doing like 100 dmg per so maybe they just thought they were doing all the dmg idk >_> ughhh. i mean bloody bolts were hella expensive but i was also the only english max rank chocobo digger on my server too so i mean O_O;. 

testing on retail sounds hella fun lol. if only i had more time/less lazy about playing. we could like level sync to 25 and murder mandies together :Q! your drains on bune were also very impressive btw, i suppose things like that'd you'd need a decent INT+ set but also i don't think i would've dared to take him on on THF/nin LOL. you is brave

**Comment by archfiendrubicante** [comment]
Bloody bolts have always functioned like dark element spells to my knowledge. 
Its pretty much impossible to get a good drain amount on ahriman, dark dragons, or any other dark type monsters.

For some reason I also remember ice type enemies resisting by half as well for some reason, though I haven't played in a while so my memory in this specific instance may be failing me. Even so I could still solo ice elementals for their clusters in Beaucedine.

**Comment by dowzer** [comment]
That makes sense, heavy armor goblins may have higher INT than others? The NM was a heavy armor goblin too, but it flat out had 50% immunity. The PH's on the other hand, more than 95 INT was required to hit the 92 HP drain cap. I was surprised Bune was even up lol

Maybe with ice being apart of darkness elements? I wonder if earth or water follow that pattern too? 

The majority of the issue seems to be solved, refining it may take a monster by monster audit to see which have flat 50% or 100% immunity. Goblins, even the NM I fought, have no description that they should resist or be immune to them.

**Comment by 59blargedy** [comment]
thanks a lot for the work here, there's a few remaining questions i have, that aren't necessarily for you to do since you've already contributed a ton, but still need answers.
- clarification question: im assuming all your tests were done with a 99 thief. was 119 gear a part of any of these tests? im mainly glancing at vids and just looking at your numbers atm. 
- does level correction have any play in the damage values, or is it solely INT and resist based dmg variance? would need to test on a higher level mob in a zone where level correction hasn't been removed yet. would need to test without 119 gear. a hard thing to test, but if we can find mobs in the 100s range that have level ranges while keeping INT static this would be the best bet. SoA areas are sadly off limits for this.
- proc rate affected by level correction or INT? when int rate is increased over 55 vs. colibri, how does the proc rate scale?
- for the dark based mobs, was there a lower proc rate or was the resistance solely affecting the damage values?
- it seems like these values align with memory for the most part, but are there any patch notes that reference changes to bloody bolts?

**Comment by dowzer** [comment]
The majority of tests were as 75 Thief (synced to the 75 RNG) naked with a crossbow, 119 gear was added for INT when finding the cap. That's why the stats are so low due to level sync restricting some entirely

I don't think level correction has a play in the damage value, although it does affect resist based variance. My test with ~500 shots was a RNG75 with Machine Crossbow vs Greater Colibri.

That's what I want to check next. When I was checking sheep in Ronfaure, I did see one half resist.
https://i.imgur.com/4lBPdai.png

The dark mobs I checked were low level, I'd like to check if they can add a half resist to the 50% immunity they have. It should follow the same sequence of no proc, a full drain (46, since 50% immunity) or a half drain of 23. 

I haven't been able to find any update notes, it doesn't seem like they were publicly announced if a change was made

**Comment by dowzer** [comment]
> **you is brave**

https://i.imgur.com/Yf3BlJ1.png

you is smart!

**Comment by dowzer** [comment]
INT 83 (RNG75 with SV Sage's Etude 55+23)
https://i.imgur.com/wbKlyVy.png

INT 84 (THF99 synced down to THF75 via RNG75)
https://i.imgur.com/kkFjef6.png

INT 104 (THF99 synced down to THF75 via RNG75) Used level sync 119 gear
https://i.imgur.com/kkFjef6.png

I believe INT solely affects the amount of HP drained.

I'll post results to find if level correction affects the resist rate

**Comment by dowzer** [comment]
INT 55 RNG75/NIN37 vs Mourning Crawler ~level 103-105
https://i.imgur.com/ijOJ9QS.png
https://i.imgur.com/oE0Oa6P.png


After 261 shots, 243 didn't drain HP, 9 drained 28 HP, and 19 drained 57 HP

**Comment by archfiendrubicante** [comment]
> INT 55 RNG75/NIN37 vs Mourning Crawler ~level 103-105 https://i.imgur.com/ijOJ9QS.png https://i.imgur.com/oE0Oa6P.png
> 
> After 261 shots, 243 didn't drain HP, 9 drained 28 HP, and 19 drained 57 HP

Those are some funny looking Mourning Crawlers...

**Comment by dowzer** [comment]
Haha yeah it's been a long day, here they are
https://i.imgur.com/OjKHAzD.png

**Comment by dowzer** [comment]
INT 104 (RNG75/NIN37 with INT 55+49) Resulted in the same HP drained as my THF99/NIN49 synced to THF75/NIN37 with INT 104 via scaled down ilevel gear
https://i.imgur.com/yvbP36B.png


INT 104
- 512 shots
- 173, no HP drained
- 138, 40 HP drained
- 201, 81 HP drained

Compared to:

INT 55
- 554 shots
- 210, no HP drained
- 131, 35 HP drained
- 213, 71 HP drained

There seems to be a minor improvement in overall proc rate by increasing INT. I would argue that the sample size is too small and INT does not affect the proc rate, where as level difference plays an obvious role

**Comment by archfiendrubicante** [comment]
INT 104

    512 shots
    173, no HP drained -- Rate of Occurrence: 33.7%
    138, 40 HP drained -- Rate of Occurrence: 26.9%
    201, 81 HP drained -- Rate of Occurrence: 39.2%

Compared to:

INT 55

    554 shots
    210, no HP drained -- Rate of Occurrence: 37.9%
    131, 35 HP drained -- Rate of Occurrence: 23.6%
    213, 71 HP drained -- Rate of Occurrence: 38.4%

Let me enumerate your data a little bit.
I added some percentages, the floor of draining seems to have raised with higher int from 35 to 40, and 71 to 81.
Form that we can infer that INT does play a minor role in how much is drained.. but its very minor. 

A 49 INT difference is quite a lot of stats, but that 49 INT only gives a difference of 5-10 hp depending on whether the proc halves or procs normally.

The accuracy of the effect landing Seems to not be dependent on INT by much. The middle proc (A half resist) doesn't change much, hovering at around what I assume is a 25% chance, While the complete resist seems to hover around 35%. We can infer from this data that the chance of an unresisted bolt against a mob in this level difference is somewhere around the 40% area. 

Five hundred bolts can't really be considered a small sample size, Generally most statistical inferences say that 1000 is the minimum sample size to establish a trend, but for the most part 500 just means you have to extrapolate a little more to find where the data points intersect.

**Comment by archfiendrubicante** [comment]
It seems that INT does shift a lot of the no procs to middle procs, but the difference in full procs doesn't seem to be too huge.

**Comment by archfiendrubicante** [comment]
What this would lead me to believe, as far as the coding of the formula is concerned, is that the game first checks to determine if it is a success. If it is a success, the drain calculates based on int.

If it fails, then it does a check based on int to determine whether or not if half succeeds. If this check succeeds, you get a half-resist and drain half instead.

Either that or its the same regardless of whether you have high int or low int.

**Comment by dowzer** [comment]
Thanks, I was hoping to see a big difference in full procs but at least it increased overall middle procs. That sequence seems right, with the first check being determined by level difference and the amount of HP drained based on INT.

**Comment by Steam-arch** [comment]
Just noting that bloody bolts are doing 115 in promies atm with a high proc rate and low resist rate. 

![image](https://user-images.githubusercontent.com/69089249/236626935-b14725bf-d721-43fb-bae3-fd991e995ac1.png)

Crazy numbers for promies with 130/arrow with none of the above hits reaching +100s, esp with no distance penalty applied to HP bolts (is dis correct also?), totally foreign subject for me, mentioning incase might need some adjustments/reopen at some point

**Comment by 59blargedy** [comment]
this is a separate issue not specific to bloody bolt damage, and only for MRs. separately, distance correction does not apply to a drain value. it applies to the bolt damage only.

**Comment by dowzer** [comment]
As a follow up, the amount of HP drained used to have a pretty wide ranged variable.
https://youtu.be/jNvM5GOTPHM

It used to be like that in 2006 up until it was "ninja updated" without being mentioned in any patch notes. JP wiki mentions, "Specifications have been changed without notice in the version upgrade on June 6, 2007"
https://wiki.ffo.jp/html/4290.html

This video clearly demonstrates how the amount drained was changed in August 2007. Instead of being a variable, they either drain for the full amount of HP or half of it. 
https://www.youtube.com/watch?v=m81Rj40BJhs
