### ISSUE TITLE
Various Shen issues.

### ISSUE THREAD

**Issue by gweivyth** [EdenServer/community#123]
Shen doesn't retreat into his shell. 

His adds were immune to sleep, says on wiki they are sleepable. 

Adds did not share hate with Shen as they are supposed to, we ended up having to kite them since we couldn't sleep them.

Still a pretty challenging fight, but mechanics are definitely not working as intended.

**Comment by Shoruto** [comment]
> His adds were immune to sleep, says on wiki they are sleepable.
> 
They should sleep, however what was your enfeeble skill at the time when you attempted to sleep?  Also did you use Elemental Seal or someone with /blm or another sleepable job?  There is a chance it got resisted.  Since it is a higher level nm, it has higher resistance during era.

The other issues mentions are indeed errors that need to be corrected to be era accurate.

**Comment by Volkaru** [comment]
Adds also are casting all sorts of nukes. All aga IIIs, AMs, Sleepga II. They should only be able to cast water nukes.

**Comment by 59blargedy** [comment]
We fought Shen three times tonight, he did not retreat into his shell at any point. Shen's adds also did not despawn when he was killed and had to be force despawned by GM/dev. They were sleepable with both light sleep and ES sleepga2, though.

**Comment by Shoruto** [comment]
More Shen information #2724
