### ISSUE TITLE
Mimics do not despawn, and they prevent coffers from spawning

### ISSUE THREAD

**Issue by rujind** [EdenServer/community#1237]
Each time this happens either a GM has to be called to remove the Mimic, or it is fixed by the server crashing or being reset. 

Sadly I can't find any data online that states Mimics should despawn if left alone for a bit. I found one site that actually said they don't despawn, but I don't think this is true. I'm not sure what their despawn timer was on retail (I think it was the normal time that a force spawned mob would despawn after returning to its spawnpoint, which I believe was 3 minutes?) but regardless of them despawning or not I don't believe they are supposed to have any impact on whether coffers are spawning.

**Comment by godmode** [comment]
I’m pretty sure you are right. I can’t imagine they would stay up. Thanks

**Comment by gweivyth** [comment]
As a temporary workaround, if you find a Mimic sitting up in the wild, please put in a GM ticket and include your map position (or just sit tight for a few minutes, if it's prime time a GM will probably jump on it within a few minutes.) so that we can come and despawn it.  I'll try and keep an eye out for these tickets and take care of them as quick as possible.

**Comment by slassen** [comment]
I just made a PR for this. If there are any mimics you see that don't despawn please create a new ticket for each zone you see them not despawning.
