### ISSUE TITLE
Kazham Airship

### ISSUE THREAD

**Issue by ahbender** [EdenServer/community#1248]
The airship from Jueno to Kazham is not entering to the port.  The timer is working, but the ship never shows up.

**Comment by Volkaru** [comment]
Airship to Windurst also never appeared. Waited 20 minutes for it.

**Comment by rujind** [comment]
Jeuno to Sandoria airship never came

**Comment by Volkaru** [comment]
After looking at other bug reports. And hearing various testimonies from people around the server... ALL airships are currently not functioning. Boat from Mhaura to Whitegate also not showing up. No words yet on manaclipper. But it seems as though since the update. The only boat that works is the one going between selbina to mhaura and back

**Comment by fillerbunny9** [comment]
and "works" is a very loose definition - the boat from Selbina to Mhaura was essentially a teleport, as I arrived on the docks immediately after the screen fade for departure.

**Comment by godmode** [comment]
This was fixed in a followup patch. Please comment if it is still not working.
