### ISSUE TITLE
ToAU Kings comprehensive bug list

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#1249]
We killed all 3 NMs tonight and here is a list of what we noticed (probably not the complete list but the best that we noticed/can remember).

**Cerberus**
- Enfeebling resist too high. Even with elemental seal, enfeebles (particularly elegy) were resisted.
- Above 30%, he was susceptible to stun but below 30%, his resistance skyrocketed. No stuns landed post 30% which is where the danger zone is.
- TP moves in general appears to do too much damage. Lava Spit was doing on average 200 damage more to similar geared tanks in era videos. 
- _Gates of Hades_: also did too much damage (almost one-shotting an 1800 hp PLD) but the more dangerous aspect was that it appeared to have an absurdly fast or near-instant cast. It should be a fast cast, but as someone who was routinely on stun duty on retail, you shouldn't need amazing gear and a lightning fast connection to reliably stun this. I'm not even sure it is possible to stun this with third party tools in its current state (not that we would!).

**Khimaira**
- Good(?) attack speed and strength, however his defense appears to be low, likely attributed to the fact that he spawned at _level 81 instead of 85_.
- We did not see a Fulmination to comment on its cast speed but we all assumed it would be like Gates of Hades and near instant. Should be similarly stunnable as long as no resistance has been built.
- No sword. ; ; Not a real bug, but a sad note.

**Hydra**
- The head breaking mechanic appears to work correctly but certain things were not being locked by it. He seemed to have access to bulwark and regen regardless of how few heads he had.
- With TP gain in its current state, this fight is far more difficult than necessary. The trembling spam was real, yo.
- On a positive note, his enfeebling resist didn't feel overtuned. He was always resistant on retail and we were reliably landing with elemental seal.

**Comment by Treble011** [comment]
Others that were involved in the fights, please comment as well. I'm sure I didn't get everything.

**Comment by Lilswitche** [comment]
Ref Cerb Gates of Hades: [Video](https://youtu.be/UQSmb8bEgIM?t=162) demonstrating the cast time of Gates of Hades.  (The ability name is filtered but you can tell it's Gates of Hades)

I felt like Khim's auto-attack delay was slightly high.

**Comment by Treble011** [comment]
@Lilswitche that is a good eye, I've never even thought of that. I think the stun wiping a monster's TP deserves its own bug report.

**Comment by Elysien** [comment]
The thing with stun not wiping Cerberus's TP seemed unique to Cerberus I think, he may possess a Conserve TP trait, or something like that. I did remember this being a thing the other day though, but can only ever remember it being a thing with Cerberus.

As for everything else, Khimaira's delay did seem a bit low, although it didn't have any slow effects on at the beginning and got a hefty volley of double attacks in. Without slow effects on, this can seem like it has hundred fists due to it's very low delay--most likely the reason the wiki claims Khimaira possesses Triple Attack which it certainly did not, but a volley of double attacks will certainly make it appear that way.

Other than that it's defence did look pretty low, and it's attack was pretty low too--- 60~ dmg auto-attacks in -50% PDT and a good phalanx; under the same conditions I would expect 120~150. 


Mostly what Bass said concerning Hydra, another note though is the physical shield ability is using the incorrect animation. The physical shield (Pyric Bulwark) is the blue-ish haze animation, while Polar Bulwark is the red-ish one.


Based on their names you'd think it would be the way they currently are but alas, no;


https://www.youtube.com/watch?v=xVM0FEx_7PQ - 50 seconds into the video you will see Hydra using Polar Bulwark, red-ish haze, magic shield effect.

Not a big deal, probably not something anyone even really noticed excepts those very familiar with Hydra enemies.

**Comment by Mozzy4Ever** [comment]
Just to add to the Gates of Hades issue:

Per https://github.com/DarkstarProject/darkstar/blob/04e6339730b658f90df5ccf30ca95dc6671e7ba4/sql/mob_skills.sql line 1613, Gates of Hades is a 1.5 second timer. According to https://ffxiclopedia.fandom.com/wiki/Category:Cerberuses (which admittedly is an OOE page but I doubt it's inaccurate on GoH timing) it should be 3 seconds. While 3 seconds may have been good for retail due to less overhead in networking (so less lag), 3 seconds may not be enough on DSP/Eden. I would recommend starting it as 3 seconds (via simply going to mob_skills.sql and changing the 1500 in gates_of_hades' line to 3000) and seeing how it's handled on live Eden. It'll be difficult to test due to less people in the area on the test server, so there's less lag there.

**Comment by Oyaziiiiiii** [comment]
I figure this would be the best place to update the current state of ToaU kings. 

1. Gates of Hades/Fulmination are still too fast to stun. Coupled with the newly added regain and excessive damage these do(far more than retail, gates currently does over 1600 unresisted and without shell atm), this makes these a good deal more dangerous than retail. 

2. The draw in is currently drawing in the entire alliance. In the bazillion Cerb/Khims I killed on retail I don't remember it being this way but I will look for some video proof.

**Comment by panfunk** [comment]
taken from general DSP files:
mob_skills.sql
...
334 INSERT INTO `mob_skills` VALUES (511,253,'self-destruct',1,20.0,2000,3000,4,0,0,0,0,0,0);
...
1613 INSERT INTO `mob_skills` VALUES (1790,1228,'gates_of_hades',1,20.0,2000,1500,4,0,0,0,0,0,0);
...
1851 INSERT INTO `mob_skills` VALUES (2028,1386,'fulmination',1,32.0,2000,1500,4,0,0,0,0,0,0);

7th index appears to be the 'cast time' of the skill defined as `mob_prepare_time`.
almost every TP move has 2000/1500 for 6th/7th values. Self-Destruct which is easily stunnable has 3000 as 7th. So I'd assume anything between 2000-2300 should be managable for GoH/Fulm, while still being required to pay close attention as on retail.

**Comment by MalteseFalcon** [comment]
Khimaira elemental resist much too high:

Bliz4 hitting for 150 (Taru rdm/blm) on Eden and here is a screenshot from retail (2008~);

![unknown](https://user-images.githubusercontent.com/33695616/75633220-1a8d9400-5bd1-11ea-9c2f-7bf3828e6574.png)

Aragan is galka blm, endless is hume, obviously there are some gear discrepancies but not enough to triple damage.

**Comment by SBC-Nyxai** [comment]
Darkness skillchains also hit for 10% of the closing WS every time. Assuming its a decimal misplacement.

**Comment by 59blargedy** [comment]
mostly resolved december 7 update. i don't believe everything is fully resolved here, but if possible to make a new bug report on remaining disparities, i would appreciate it.
