### ISSUE TITLE
Crayfish breaking Hume

### ISSUE THREAD

**Issue by Charismati** [EdenServer/community#1287]
While catching Crayfish in East Sarutabaruta with Little Worms, one catch was able to break a Hume Rod. I don't think this is supposed to be able to happen.

**Comment by Setz0r** [comment]
i'm not taking any more rod break bug reports until after the new version of the fishing system is rolled out.  also, please understand that while my system doesn't have a perfect rod durability system, the wiki and other sources are unreliable because they have no evidence or sources, nor do they seem to account for the fact that rod durability has a skill level based bonus that makes weaker rods stronger at higher skill levels.  for instance a willow rod can break on a moat carp at level 0, but not at skill level 50+

**Comment by lalas99** [comment]
Hume rod:
Your keen anger's senses tell you that this is the pull of a crayfish!
Your rod breaks.

![download](https://user-images.githubusercontent.com/50406295/57538092-81695600-72fc-11e9-96e5-9a09ab4f5dd4.png)

They may not have evidence or sources but they were pretty much a fishing bible for the era this server is trying to recreate.

**Comment by tacbox3** [comment]
Setzors comment about skill level factoring in needs to be considered. I say this to everyone: if the second line of your hook message is anything other than " you have a good feeling about this one!", then there is a chance your rod will break. Always trust the in game warnings above what any online sources indicate.

**Comment by tacbox3** [comment]
Additionally, regarding "keen senses" procs, these can "hide" bad feeling messages. It's therefore recommend that you fish up a few without that proc whenever you're targeting a new fish. That way you can get a feel for how often bad feeling messages come up, if at all.

**Comment by lalas99** [comment]
Skill level isn't a factor in this case. Crayfish don't break hume rods, ever. Doesn't matter if you are a level 0 galka fishing with his toes. Shouldn't happen. Unless they changed things majorly skill level only figures in if the fish can break the rod. Then it makes it more likely.

**Comment by Setz0r** [comment]
I will explain this again..

Each rod has a base durability that's checked against some unknowable stat on the fish.  
Skill difference mods this durability.
The reason the wikis can't be trusted is because there's no way of knowing what skill level the player who reported something as breakable or unbreakable was.  

For instance, a yew rod can break on a moat carp at fishing skill 0, but never at 50+.

To find out the 100% accurate numbers would require a level of rod testing on retail i simply don't have time for.  I will be applying the skill level bonus in the next fishing update, so no more complaints about X fish breaking Y rod until its out.

**Comment by lalas99** [comment]
For enough. It does seem like you want to add a level of mystery to rod breaks that, at least 8-10 years ago, didn't exist. Leveled fishing to 100 twice with the info from great blue and never broke a rod unless I was lvling woodworking or working on ebisu.

**Comment by Setz0r** [comment]
yeah, i made a couple revelations during my hundreds of hours of packet testing on retail.  got 60 fishing levels just from tests.  i think most fish have a "family" category that has the durability related stats.  I just can't get those numbers without extensive and very precise and well-thought out testing starting at level 0 with all rods and gear available.
