### ISSUE TITLE
[PUP] Inhibitor SC properties off when cannibal blade introduced.

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#1294]
Not sure exactly is what going on. But in a level 60 party against Colibri. I was trying to make my Valoredge automaton use string clipper when equipped with Inhibitor. 
I was using the proper WS that would trigger him to use String Clipper at lower levels. But it seems Cannibal Blade is interfering. 
Even when using 3x fire maneuver and using Spinning Attack. Backhand Blow, or Howling Fist. He'll ignore the SC open, and instead do Cannibal Blade. He'll Trigger Chimera Ripper if the SC calls for it, And Cannibal Blade. But he won't use String Clipper.
Also seems Cannibal Blade is getting a damage boost from Flame holder. I'm not sure if that was a thing in retail or not, though.
EDIT: Seems Cannibal Blade getting a bonus from flameholder was added in retail at some point. Though I can't find any info about when.

**Comment by Volkaru** [comment]
Also related to #1294.

**Comment by KnowOne134** [comment]
this does not have the the extra property for scission, but it is the only ws that has is a ranged attack so if you deploy from out of melee range it will do it instead of anything else if tp threshold is within its limits. now that tp can be held past 1k unless a fire is up will be a little easier to control.

does this sound more like your issue?

**Comment by KnowOne134** [comment]
actually hopped on retail,
with fires up:
retail backhandblow > cannibal, howling Fists > Cannibal, spinning attack > chimera
and tested eden and we do the same, it will bypass the man check and do the highest skillchain avail.
