### ISSUE TITLE
Mob stayed claimed after death

### ISSUE THREAD

**Issue by mlandrum22** [EdenServer/community#1295]
I was power leveling my alt from outside of the party, but I got hate from the mob due to curing him. 

My alt died (lol i suck at PLing).

The mob did not change colors and attacked me but I could not then attack the mob.

**Comment by KnowOne134** [comment]
Was your alt in a party?

**Comment by mlandrum22** [comment]
No.

**Comment by beauxq** [comment]
to reproduce this bug:

player A and player B are not in a party together
player A provoke mob
player B cast Cure (1) on player A (Get on the threat list but not enough threat to change mob's target.)
mob kills player A

expected:
mob goes unclaimed because everyone in claiming party/alliance with threat is dead

current bugged (I haven't tested this recently. I remember testing it a long time ago. So maybe not current.):
mob stays claimed to the dead player A

**Comment by 59blargedy** [comment]
this has been resolved in a prior patch
