### ISSUE TITLE
[PUP] Flashbulb's Flash effect seems really weak.

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#1310]
The effect of Flashbulb compared to the spell is really low. Even when used in dunes, where it should pretty much floor the mob's accuracy for a few seconds... Sees almost no reduction in the monsters accuracy against the player.

**Comment by Danzibeast** [comment]
Neither does it seem to generate any enmity. What makes me think this is that if flashbulb lands on a mob prior to any other attacks the mob does not become a battle target, nor does the mob attack the party/puppet.

**Comment by FariskaEden** [comment]
@Danzibeast Flashbulb isn't supposed to generate the same amount of hate as the PLD/WHM spell. I also think pet abilities don't claim as it's the same on retail. https://ffxiclopedia.fandom.com/wiki/Flashbulb

Regarding the Flashbulb attachment though, it seems to scale with level rather than being a flat amount of -accuracy, making it not so great at lower levels but better later on.

**Comment by Danzibeast** [comment]
Thanks for the quick response. Flashbulb scaling poorly at lower levels is a wider issue due to the strobe attachment (which gives provoke) being very difficult to obtain on Eden. The Era appropriate way of obtaining the attachments was via crafting or farming a lvl 75+ mob. That said, one of the ingredients for the craft of said attachment is not available on Eden. Also, the lack of high level players willing to farm make the attachment on Eden a true rarity! If you combine the poor performance of flashbulb with the immense difficulty in obtaining the strobe attachment, it somewhat shuts off the PUP tank option. It would be a great compromise (at least while the player base is developing) to allow players to purchase certain *must have* attachments from the NPC as SE implemented at a later date.

Kind regards

**Comment by KnowOne134** [comment]
fixed on next update
