### ISSUE TITLE
Some HNM ToDs not persisting through server crash/restarts?

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#132]
Receiving some reports from Fate/Virtue that Serket/Roc/Simurgh's ToDs seem to be reset upon server crashes and restarts.

**Comment by Aneyus** [comment]
As far as I'm aware, they simply aren't spawning if their 21 hour cooldown is interrupted by a reset/restart. Will look into it more and update.

**Comment by Lilswitche** [comment]
You can add Orcish Overlord to this list.

**Comment by godmode** [comment]
So all of the NMs respawned this morning?

**Comment by Lilswitche** [comment]
Traditionally, when a server reset were to happen on retail, these NMs would respawn within 0-3 hrs of the server coming back up.  In these instances of the server restarted, I believe it's pushing it 21-24hrs after reset.  

Ideally we have the ToD persist thru resets.  e.g. I killed Orcish Overlord yesterday around 1pm pst but it never popped today because of the server downtime this morning.

**Comment by Treble011** [comment]
We killed KB about 40 minutes before maintenance today. After maintenance, normal Behemoth was up when the server came up.
