### ISSUE TITLE
Unable to create Ark Pentasphere for Divine Might

### ISSUE THREAD

**Issue by Hatberg** [EdenServer/community#1349]
During Full Moon (Earthsday 1322/9/10 Full Moon 98%) I tried to create an Ark Pentasphere on two different characters, but was unable to do so.

- Zilart Mission 14: Ark Angels is active
- Shrine of Ru'Avitau blank ??? was visited twice, with instructions given to create Ark Pentasphere with Parchment and Illuminink at Qu'Hau Spring
- Questlog shows Outlands: Current Quests containing Divine Might
- Weather was clear, with animation showing of spring filling up with water and reflecting the (Earth color) moon
- Parchment was crafted with Sheep Leather and Rolanberry
- Trading 1x Parchment and 1x Illuminink to Qu'Hau Spring does nothing.

Characters: Hatbyrg, Hatburg

**Comment by Hatberg** [comment]
Retraced all steps, clicked all relevant ???s again.
Was able to create an Ark Pentasphere on 1322/9/12 Windsday at 98% Full Moon.

The Earthsday report in original post was a a Full Moon 98% climbing to 100%.

The successful attempt at Windsday was on 98% going down again.

**Comment by Hatberg** [comment]
Maybe relevant: I gained access to Sky about a month ago, did all the cutscene work. Perhaps some CS progress was lost between patches.

**Comment by rujind** [comment]
It can't be cloudy either I think.

**Comment by Hatberg** [comment]
If it's cloudy the spring won't fill up with water.

**Comment by MB213** [comment]
I had this same issue on 31/5/19.
Steps I followed:

- Received the cutscene from Shrine of Ru'Avitau
- Went to Qu'Hau Spring and waited for Full Moon
- On Lightsday 0:00, 100% Full Moon, the weather became clear and the spring filled up and glowed. 
- Traded the items to the spring, but nothing would happen. 

You can see here in this screenshot the items (that is illuminink) being traded to the spring while it is full (please ignore the out of range prompt, I was trying from to trade from the other side too because it wasn't working):
![Mihki_2019 05 31_000909](https://user-images.githubusercontent.com/37488914/58744360-f0ae1200-8484-11e9-99d0-2b0d08dbde01.png)
Here is the log from before this, showing I had done the quest up to this point:
![Mihki_2019 05 31_002926](https://user-images.githubusercontent.com/37488914/58744372-1affcf80-8485-11e9-914a-f085a4ba83de.png)

**Comment by baroom84** [comment]
Every day it's usually fog in game in the morning. You can't trade during any weather. If it's 0:00 was fog most likely.

**Comment by MB213** [comment]
The spring only fills up during clear weather. You can see in the screenshot it's full.
Also, there are 2 bombs that spawn there during foggy weather which were not up.

**Comment by MB213** [comment]
Update - I was able to create the Ark Pentasphere today.

The only thing I can think of is I went back to the monument in Shrine of Ru'Avitau and clicked on it. I did not receive the cutscene again, just some text reiterating the Qu'Hau Spring part.

My guess is the quest is not getting flagged properly after the cutscene, but only once you click the monument again. This is not retail behaviour, and is very unintuitive as the cutscene is **very** clear about what you should do next.

**Comment by FariskaEden** [comment]
Today I was able to create an Ark Pentasphere during the appropriate time / moon phase, however it was created during rain weather and the spring was not full.

**Comment by Mahou81** [comment]
I got my Ark Pentasphere today, but it was around 22:## time (full moon) and the fountain wasnt filled yet. The fountain filled up like it should at 0:00, but as I said I received my item before that. Classic wiki says +0:00-3:00 which is indeed the time the fountain is filled (drained again at 3:00). Current retail fountain fill time is 18:00-6:00 so maybe DM quest on Eden is still set to that as well, even though fountain fills according to era hours.

**Comment by KnowOne134** [comment]
Corrected in 12/15/2023 update
