### ISSUE TITLE
Desynthesis Break/NQ/HQ rates.

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#1382]
Currently the desynth rate on Eden is too reliable and the rate of HQs is either too low/high based on level.  At synth cap, some estimates of the era fail rate were approx 50%~60% and NQ/HQ rates both 20%~25% respectively.  Desynth recipes were not subject to HQ tiers like normal synthesis.  

I can't confirm this, but I suspect that certain recipes on Eden are not categorized as Synth/Desynth but all lightning synths are categorized as Desynths.  There should be wind/fire/water desynths as well.

There are some lightning crystal synths that are not considered desynths - such as thread synths like flax flowers, spider webs, etc.  Non-comprehensive lists of desynths from the wiki: [Link1](https://ffxiclopedia.fandom.com/wiki/Desynthesis), [Link2](http://ffxi.somepage.com/recipedb/list.php?synth_desynth=Desynthesis&result_set=200)

*Note that on that desynth page they do mention: "Also, unlike normal crafting, the chances of getting a High Quality result from Desynthesis is greatly increased, meaning that crafters can get a HQ1, 2, or even 3 while still being under the skill cap for the item!".

Some supporting evidence: [Link1](https://www.bluegartr.com/threads/60046-Quick-desynth-question), [Link2](https://www.bluegartr.com/threads/72886-Desynthing-How-do-you-do-it-w-90-success-rate),

**Comment by godmode** [comment]
This issue may not be completely fixed when the patch deploys. Leaving the ticket open until we can get some data collected.

**Comment by bkesecker** [comment]
The change in success rate should have a corresponding increase in HQ rates.  This is how retail made it viable.  I don't have evidence unfortunately, only my decade-old recollection.

The rate change from 95% to 50% without adjusting the tiered HQ rates, will hurt auction sales of commonly desythed items and it will become a lose-lose vs lose-to-potentially-win situation.  No one will be able to sell these non-NPCable items.

**Comment by ababyduck** [comment]
> The decrease in success rate should have a corresponding increase in HQ rates. This is how retail made it viable. I don't have evidence unfortunately, only my decade-old recollection.

This is what I remember as well. It was noticeable very early on in woodworking, as you got a lot of HQ results on maple sugar even while skilling up. I suspect if you look at old crafting guides which include desynths in the skillup path, they may mention this.

**Comment by mlandrum22** [comment]
(Azmanz if you want to check logs) Decided to test this out, I went for Bronze Subligars: level 9 Smithing de/synth

I'm level 2. I actually had a very high success rate 11/17 BUT I did not get a single skillup. Is the Bronze Sub coded as a lower level synth or is this related to the new desynth? I also got 1 HQ (it was teir 2)

I tested gold orcmasks 4 levels below cap and was able to get skill-ups on both successes and failures so that seems to be working as intended.

**Comment by Tolkage** [comment]
I'm confused as to why this decision was made, and why it was acted upon so suddenly and without sufficient data gathering. The links provided in the OP don't include a single shred of hard evidence, only "It feels like" or "It seems as if" statements all throughout, not a single post of real data with tons of logged results. (I also want to point out if you go to forums from that same time period, you'll find a ton of posts "proving" that directional crafting was a thing, even though SE later confirmed it wasn't. So these old forums posts aren't really fact we can go off of)

The biggest reason I am confused about why this change is happening now, is because this system has been in place for so long already with so many players already taking advantage of it. This comes off as yet another change simply putting down new players.

It also *does* effect skillup rate, (which I saw in discord people saying it wouldn't.) There are multiple ranges in multiple crafts (Smithing 70~79, Goldsmithing Hairpin levels, etc.) Where desynthing is a big part of your skillup process, and with lowered success rate those desynth recipes are no longer a viable option for new players after they've been available for a yr+ for old veterans.

Putting this change through as an emergency patch without sufficient data gathered before hand makes absolutely no sense.

**Comment by MGramolini** [comment]
> (Azmanz if you want to check logs) Decided to test this out, I went for Bronze Subligars: level 9 Smithing de/synth
> 
> I'm level 2. I actually had a very high success rate 11/17 BUT I did not get a single skillup. Is the Bronze Sub coded as a lower level synth or is this related to the new desynth? I also got 1 HQ (it was teir 2)
> 
> I tested gold orcmasks 4 levels below cap and was able to get skill-ups on both successes and failures so that seems to be working as intended.

Bronze Subligar is coded as (16) on Eden for desynth (same as brass for some reason).  It should probably be (9).

**Comment by mlandrum22** [comment]
Thanks for looking into it MGramolini, this is a different bug then. Were they coded as Goldsmithing then, too? 

I was able to desynth them with Smithing skill 2, but GS skill 49.

**Comment by AnkleAssassinz** [comment]
FWIW, Test result of my desynthesis.

Synth recipe  wind+quad helm: 51 cap
Total Starting Quadav Helms count: 107
Direction: East...always into the East!(Shout out to Deckard Cain :D )

(A) Base lvl 50+3(advanced support) = 53
breaks: 8
NQ bronze: 36
hq#1 ironsheet: 6
hq#2 steelsheet:  2
hq#3 darksteel sheet: 0

*gained enough skill up to be base 51.

(B)  Base lvl 51+3(advanced support) = 54
Quadav helms left: 51
breaks: 7
NQ bronze: 36
hq#1 ironsheet: 6
hq#2 steelsheet : 1
hq#3 darksteelsheet: 2

randoms: 
hq1--> hq2 back to back:  [https://postimg.cc/9RCshWBd](url)

HTH

**Comment by xrocksterx** [comment]
Hello, this is Sylv sharing my data after a few desynths today.

30+1 above cap
Total Desynths: 155

NQ: 52
HQ1: 16
HQ2: 8
Breaks: 77
Synths with Lost Items: 14

**Comment by MB213** [comment]
My results from 97 Synths, 53 levels over synth cap:

Break: 49
Break + Loss: 7
NQ: 22
HQ1: 11
HQ2: 6
HQ3: 2

As percentages:

57.7% Break Rate with 7.2% total items lost
42.3% Success Rate with 46.3% of those being HQ

**Comment by MGramolini** [comment]
https://images.app.goo.gl/XK9TsG1dEAeEUe469
https://nhac.vip/videos/2qInP6VvhPo/clip-desynth.html

Its hard to find any large data video/images of desynth.... And based on the language of allakazham posts i don't trust their posted data enough to use it.  Hopefully someone can find 100+ desynths data somewhere.

**Comment by Lilswitche** [comment]
Ayyy. Just yesterday I was just talking about how Cerb Mantles weren't desynthable on DSP.  Of course when I brought it up the wiki warriors tried to tell me it was never era.

**Comment by MGramolini** [comment]
Yea switche, i actually found another example, but that one was only just 1 desynth and 1 synth so wasn't really important in this context.
