### ISSUE TITLE
Castle Zvahl map quest Northward incorrect text flag

### ISSUE THREAD

**Issue by Jimmayus** [EdenServer/community#1398]
for reference: https://ffxiclopedia.fandom.com/wiki/Northward

I have capped fame in all regions and this quest requires rank 4 Jeuno fame. When I talked to the NPC he said "I want somebody to take this map I got in the north and stave off impending disaster, but you don't look ready for such a task". 

So, I traded him a flame degen anyway as the quest requires and he completed the quest as normal. Looks like the text flag for the quest start is off. The quest is in my completed folder but I unfortunately did not check to see if it was in my current quests tab once I talked to him.

**Comment by ababyduck** [comment]
The event id for the start of the quest is missing, and there's a comment from the original author noting they couldn't find it. I've done some digging, and while the dialogue does exist, there doesn't appear to be an event to play it. The quest is otherwise coded correctly and should function as expected.

If anyone would like to dig further, the text IDs associated with this quest are 10227-10237, and this NPC is associated with events 61, 159, 160, and 10244.

**Comment by ababyduck** [comment]
Wiggo filled my request for a capture of this quest so I'll take another look at it soon.

**Comment by ababyduck** [comment]
Fixed in https://github.com/DarkstarProject/darkstar/pull/5811/commits/21961a2da3c0ffe151499a7c608597961bfcf4d9

**Comment by 59blargedy** [comment]
resolved december 28th patch
