### ISSUE TITLE
DRG Out Of Era Buff

### ISSUE THREAD

**Issue by ccl085** [EdenServer/community#1423]
I got to play DRG on eden and I noticed it is getting the  out of era buff when wyvern is alive and leveled ->" The bonuses are as follows:
For the Dragoon per parameter increase:
Attack +4% [10/256] (Cap: +20% [51/256])
Defense +4% [10/256] (Cap: +20% [51/256])
Job Ability Haste +2% (Cap: +10%)"
https://www.bg-wiki.com/bg/Wyvern_(Dragoon_Pet)

Att and def are easy to check as they appear in equipment, did not bother to check the haste but it is safe to assume it is there too.

**Comment by Shoruto** [comment]
These Parameters were definitely added post era.  I am finding nothing showing it occurred before then.  SE also announced new attribute increases in 2008 Patch.

**Comment by ccl085** [comment]
Yes those were added after Adoulin

**Comment by panfunk** [comment]
Since I'm (taru) 75DRG and very much enjoy the job at the current state I feel like I need to comment on this.

Yes DRG is very strong atm, especially in pre-50 exp parties. ( I know ppl will yell now, but they are even more OP on colibris and such!!)
But let's face it, DRG is the only 2h true piercing DD. And 99% of the xp parties post 50 are made on mobs that are weak to piercing. I've been in alot of parties between 53-75 (all on Lesser to Greater Colibri) as DRG and all I can say is that the DRG is mostly leading the charts, but well geared SAMs and WARs keep up no sweat. SAMs wielding a polearm at a skill of B- compared to the A+ of a DRG.
I wish I could find a mamool ja staging point merit party to compare DRG there against SAM or WAR and I'd not be surprised if it fell way behind.

Yes, this buff is not era, and to make DRG era you could remove it. But anyone who played 2005-2006~ should remember what a dead job DRG was back then. Back then as far as I remember DRG was like THF, noone would invite a DRG for anything unless nothing else was lfp and DRGs in endgame? No way if the person had any other job than DRG he'd come on that, except the rare occasion where you'd need Angon. And by my few trys on Sky Gods as DRG, it's not the 'OH SHIT'-job there atm either. It does DMG but it's not outstanding in any way.

**Comment by isotor** [comment]
Open the door to this (a huge buff targeted at one specific job) and you leave the door open for players' lobbying for any and all OOE changes to their preferred job down the line that they want - this is power creep in an environment of perennially static difficulty (content-wise).

You (panfunk) freely admit that the presence of this out-of-era benefit takes DRG from *"somewhat underwhelming"* to *"probably the best job for exp parties at all levels period"*. Hard to square that with telling everyone else they can't have their cake as well.

**Comment by godmode** [comment]
I think the bigger issue is that I think some mobs are more weak to piercing than they should be. Not just DRG is OP

**Comment by panfunk** [comment]
Wow, that comment sounds salty, but as I said, sure go ahead and remove it, then everyone will ask for SAM as /yell LFM 53+ piercing DD. I'm not sure if you played 2005, but with the introduction of the 2h update+ Hasso/Seigan, the job SAM went from oh-lolSAM to OMFG-SAM which everyone leveled because it was superior to every other DD

**Comment by isotor** [comment]
Not salty at all, I have no skin in this game, I'm just chiming in with an objective overview of what this discussion is about. Keeping it in any form would be breaking away from "true to era", but keeping it in it's fully powered current state *(designed for a level 99+ environment where exp as we know it is a functional irrelevance)* goes a step beyond into the realms of playing favorites. Just advising caution here.

**Comment by panfunk** [comment]
I understand what this discussion is about, and I just wanted to point out what will happen if this buff is removed and as I also tried to point out, yes DRG is very strong on mobs that are weak to piercing, which imo should come naturally as a DD with the best piercing combat rating. Just like MNK is the best/only possible DD for the ancient skele-burn parties in KRT.

I see the problem you mention about other OOE stuff being requested, but as it is there are several OOE buffs/nerfs/QOL changes currenty active.

If it's about era accuracy, by all means remove/nerf it, but if it's just because so many ppl whine that DRG is surpassing other DDs on birds, that'd be wrong imo.

**Comment by MGramolini** [comment]
When you parse with Deeps, you have to remember that you are not including any of the pet damage in the parse.   People using KParser have shown that the wyvern commonly will out DD a thf or monk in the party.  They are likely not top notch, but when you add up the wyvern + the DRG damage against an equally good SAM, the DRG/wyvern combo wins even on non-piercing mobs from what I have seen.

**Comment by gweivyth** [comment]
I burned Dragoon from 50 to 75 over the course of like two weekends, and I feel confident in saying that Dragoon is hands-down the best exp job by a wide enough margin to make literally every other job not worth inviting.  All of them.  It isn't even particularly close.  And it isn't JUST piercing damage being too high, it's Spirit Link buffs being active and Jumps being overtuned as hell.  (Might be a side effect of having a bunch of "free" attack+ from Spirit Link.)  It's such a strong effect that gear really doesn't even matter as long as you're using an up-to-date weapon.

There was never a single party where I parsed less than 15% ahead of every other job, and this was while using Deeps, which doesn't account for pet damage, so who the hell even knows how far ahead I would have been vs. other jobs had I accounted for Max?  In parties with other DRGs we would be neck-and-neck, and in most cases those other DRGs had worse gear than I did.  It just doesn't matter.  You parse around 80% accuracy on auto-swings without food in even mediocre gear, your average hits are 170 damage and jumps are WAY overtuned, regularly doing 250-500 damage on Colibri.  

I didn't notice any difference in swing time when comparing my wyvern "leveled up" vs. not being summoned, but the attack difference is something you can visibly see in /checkparam.

I mean maybe mobs are "too weak" to piercing or something, but that doesn't explain why DRG is still so far ahead of jobs like Samurai and Ranger who also do piercing damage.  I could see being within 5% but at the moment it isn't even close to that.

**Comment by Slamm21** [comment]
I think this is far too overpowered to not remove. +10% job ability haste alone is game breaking for era, especially when you start adding more haste later on.

Using scoreboard I have found that the wyvern out-damages often every other DD in party so there is no way the problem is just mobs being weak to piercing and like Gweivyth said, there is no point inviting any other DD now if you can get a DRG. 1DRG often = 3 other DD and always at least two.

Yesterday on colibri one of our DRG were holding back so we didn't kill too fast to loose chain and yet the two DRG between them did 50% of the party damage before the wyvern, the wyverns topped that up to 70% leaving the DRK and NIN who were both very well geared and with merits (unlike our 2 DRG, one of which even being NIN sub) to take the final 30%. Before one of them was holding back they were doing 80% of the party damage and the NIN and DRK together doing the final 20% How is this not completely broken? Jump does more damage than most weapon skills right now.

I used to Merit all the time in ToAU and a well geared DRK could out-damage an AH SAM etc, Yes DRG was weaker than the others and we all know it was loldrg but no job was ever this far ahead and the 2Handed update really helped lower that gap although the gap still existed.

It does seem that out of era damage calculations are applying to all jobs, as SATA does much higher damage than retail and things like Fast Blade and Vorpal Blade are doing way higher than they did in era but small differences like this we can all live with and in some ways are nice that we do have some variance, but DRG right now is just too much, far too overpowered and game breaking.

I love Eden, and really appreciate the time you devs spend giving us the game we all missed, and for me it really does feel like era apart from this one thing, it is just too broken.

**Comment by VerrenGunnar** [comment]
DRG & Piercing are simply too strong, weve traded loldrg for lol(everything else)

**Comment by Slamm21** [comment]
If you just look at numbers piercing is clearly not the reason, weak to piercing means piercing weapons will do 25% extra damage. All Colibri on wiki shows exactly their defence and vit depending on their level so the game will just do a simple calculation on your attack rating against theirs + the piercing bonus to calculate the possible damage. There is no way this calculation could be wrong as we have known the damage formula for years.

If the problem was just piercing DRG would do at best 25% more damage than a war (without counting pet) whereas the pet (which is blunt damage) out-damages a war and the dragoon itself does 2-3x a warriors damage. The issue can only be explained by JA haste, attack and defence bonuses from the wyvern and the way haste works in the game the more you add on the more effect each 1% has so when you start adding BRDs DRG gets even more disgustingly broken.
