### ISSUE TITLE
Gray chip acts as if it is Rare but shouldn't be

### ISSUE THREAD

**Issue by MGramolini** [EdenServer/community#1468]
https://ffxiclopedia.fandom.com/wiki/Gray_Chip?oldid=264297

![GrayChip](https://user-images.githubusercontent.com/1774728/55532083-90fcdb80-567a-11e9-9e55-f3386ae84349.png)

**Comment by Volkaru** [comment]
Looks like as far back as December 2006 they were R/EX: https://ffxiclopedia.fandom.com/wiki/Gray_Chip?oldid=170589

However. It was changed sometime between then and June 2007: https://ffxiclopedia.fandom.com/wiki/Gray_Chip?oldid=264297

Since the server's cutoff date is November 2007, I feel this change should be made.

**Comment by godmode** [comment]
The CoP missions have original level difficulty as stated on our wiki and several “about us” pages.

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
