### ISSUE TITLE
Melee Gloves giving OOE stats

### ISSUE THREAD

**Issue by Qair** [EdenServer/community#1492]
Melee Gloves when equipped give +6 to geomancy and +2 to handbell. seems to be a hidden stat boost.

version [30181205_0]

<a href="http://tinypic.com?ref=dnlnco" target="_blank"><img src="http://i68.tinypic.com/dnlnco.png" border="0" alt="Image and video hosting by TinyPic"></a>

### Checklist

- [/] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [/] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [/] I have provided my client version in the details. (type /ver into your game window)

**Comment by godmode** [comment]
```sql
INSERT INTO `item_mods` VALUES (15103,123,6); -- Enhances "Chakra" effect II - Increases VIT mult by 0.6
INSERT INTO `item_mods` VALUES (15103,124,2); -- Chakra removes Disease
```

These two lines are what is causing the issue. However I'm not sure if they are giving the correct bonus or not. The modifier IDs are correct in CPP and Lua.

**Comment by mousseng** [comment]
i don't have any historical context (`git blame` locked up on `charutils` lol), but this appears to be an issue with the relationship between skill IDs and modifier IDs (the `Mod` enum). in `BuildingCharSkillsTable()` it loops over each skill by its ID, and critically it assumes the respective skill modifier is just the ID + 79:

```cpp
// charutils.cpp:2502
for (int32 i = 1; i < 48; ++i)
{
    skillBonus += PChar->getMod(static_cast<Mod>(i + 79));

    if (MaxMSkill != 0)
    {
        // ...
    }
    else if (MaxSSkill != 0)
    {
        // ...
    }
    else
    {
        PChar->WorkingSkills.skill[i] = std::max<uint16>(0, skillBonus) | 0x8000;
    }
}
```

the skill modifiers stop at id 122 (blue magic) and that's where our Chakra modifiers start. 44 + 79 = 123.

one potential solution is to reorganize the `Mod` values, but that seems pretty invasive. there doesn't appear to be any modifier implemented for Geomancy and Handbell, so the call to `getMod()` could be made conditional (`if i <= 43`).

or the loop could just be shortened to 43, because we don't have those skills on eden. dunno what sort of knock-on effects that could have.

**Comment by 59blargedy** [comment]
looks like this was resolved in a recent update
