### ISSUE TITLE
Cannot Ride the Manaclipper

### ISSUE THREAD

**Issue by paulyffxi** [EdenServer/community#150]
I bought multiticket (don know if that matters) and have tried to take the boat to all locations several times (10/9) for 2hrs, (10/10) for about an hour

when the boat is turning into park at the dock and boat looks like it will line up but then when it stops it flashes and the boat deck will be above the dock and your character cannot get on the boat unless you run back and forth.  When on the boat, half of your body is under the deck of the boat and when the boat takes off your are left floating over the water and cannot return to the dock unless you wait for next boat to come or warp out.  I tried running after the boat like a fat kid behind an ice cream truck hoping it might zone me to the boat but you can only run so far.

**Comment by gweivyth** [comment]
Hey Pauly,

Yeah, we experienced the same issue when we did our Shen run the other night.  It would let some players off at the isle, (only a few, most of us got ported back to the Bibiki zone or put back on the main dock)

If I'm online I can manually drag you to the zone once you ride the boat, just send me a tell and I'll take care of it as a temporary fix.  I know GM is aware of this issue already since he helped us get to the isle to do Shen, but having a formal bug report is good.
