### ISSUE TITLE
Crossbow Bolts

### ISSUE THREAD

**Issue by chlorr** [EdenServer/community#151]
Bought a few stacks of lv 1 Xbow bolts (All jobs usable) but as i go to equip them as THF nothing happens. 

Plz halp. dont wanna waste the good bolts

**Comment by roriffxi** [comment]
That's a change se made in like 2011. Thf only gets the status bolts in era (acid, blind, sleep, bloody, venom)

**Comment by chlorr** [comment]
pooo. i want a 1.5k refund for the vendor lying :p

**Comment by beauxq** [comment]
I think this is still an issue that can be open (though not a high priority) since something can be done for any decision on a resolution.

options:

1 Leave as era (THF can't equip) and dat mod to show it. (There is a "needs dat mod" tag for issues.)

2 Quality-of-life change to allow THF to equip it.

Either way, the issue should stay open until one of these are done.
