### ISSUE TITLE
Morion Worm ??? Respawn Time should be 15 min, not 5

### ISSUE THREAD

**Issue by GalkaZajin** [EdenServer/community#1516]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
The ??? for Morion Worm in Korroloka Tunnel respawns every 5 min or so instead of every 15 minutes. https://ffxiclopedia.fandom.com/wiki/Morion_Worm?oldid=310751

ver 30181205_0

**Comment by Shoruto** [comment]
Want to add more 15 min proof.  After the link are the posts that talk about it.

http://ffxi.allakhazam.com/db/bestiary.html?fmob=573
--------------------------------------------------------------------------------------------------
**Apr 15 2006** at 9:19 PM Rating: Decent
mungus

meh 1st killed it as 42MNK/war took me down to about 689/902 HP (GALKA HP). i've seen a RDM39 kill it o.O dont know if he used 2H or not

pops every 15 minutes (earth time) from the last time it has been killed

bit of addvice. kill it fast so that the other campers dont get the TOD aswell. so kill worms in the area to build up tp.

also: have a THF 50+ for TH2, it helps still DS ores drop like every other pop lol.

----------------------------------------------------------------------------------------------
**Aug 26 2006** at 12:33 AM Rating: Decent
Dragoonmage

### 57 Thief here, 5 kills in the last hour and fifteen minutes, no drop. No skills/magic/ws used period, i just melee it to death, wait 15 minutes, and make my way around the zone again. Bad drop rate on Tathlum, need one for my rdm... did get 1 darksteel ore thusfar though.
-------------------------------------------------------------------------------------------------
**Jan 18 2007** at 10:18 AM Rating: Decent
eGocOrrupteD

ok. i can validate that the 10-15 minute respawn time is absolutely valid. my bf and i [35blm/17rdm & 35whm/17blm] killed this thing THREE times in about an hour last night. the ??? appears within the same area every time. i just traded it an iron ore, and there it was.
