### ISSUE TITLE
Cannibal Blade Automaton WS too strong

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#1556]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181222_1
Cannibal Blade hits for 600-900+ damage, should do 250-300 in this era according to multiple sources on wiki talk page

https://ffxiclopedia.fandom.com/wiki/Talk:Cannibal_Blade

**Comment by FariskaEden** [comment]
Was it being used with flame holder? While it should add a little extra damage, it should not be reaching that level of damage with it.

**Comment by Volkaru** [comment]
#1294 Already has this mentioned. 
The WS is getting a big boost from flame holder. But there isn't any info on if this is era accurate or not.
I've spent quite a lot of time trying to find info on it. But not many people used Valoredge in retail during 75 cap.
The only 900 hit from it during this run was on a Memory Receptacle. Which take enhanced physical damage. Otherwise was hitting for 600 with 3x fire maneuvers and flame holder.

**Comment by MGramolini** [comment]
I don’t remember the receptacles taking double physical damage like the wiki claims, was this how it’s been on Eden the entire time?

**Comment by Iced-Latte** [comment]
My cannibal blade hits on valoredge @ 75 do not hit this hard. I do not have flameholder.

**Comment by FariskaEden** [comment]
https://ffxiclopedia.fandom.com/wiki/Talk:Cannibal_Blade
There are some comments here about the Cannibal Blade + Flame Holder interaction, seems like it only added a little bit of damage per fire maneuver.

**Comment by 59blargedy** [comment]
we spent some time during pdif update to adjust damage here. assumed resolved, but may comment if further damage-specific changes are needed.
