### ISSUE TITLE
Digging rank up

### ISSUE THREAD

**Issue by Qair** [EdenServer/community#1560]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

v. 30181205_0

So according to the wiki it takes approximately 75-200 greens to rank up past level, I'm at over 200 stacks and my delay still hasn't changed from 16s to 11s. Every digger I talked to seems to have ranked up sub 100 greens. I just want to know if there's a way to see if the skill up system is working as intended because I'm on route to go 400 greens without a rankup @ rank 1

**Comment by chlorr** [comment]
are you counting stacks, or single greens? cause I always mean stacks if i didn't make it clear in game :x

**Comment by Qair** [comment]
yes, ive used over 200 stacks and i only dig on non first quater last quater moons

**Comment by Lilswitche** [comment]
What zones have you been digging in primarily?

**Comment by Qair** [comment]
Dunes,South gustaberg, and e saru. Maybe 40 to 60 stacks in the jungles

**Comment by gweivyth** [comment]
So what is the consensus on zone mattering for skillups?  I have noticed an abnormally long amount of time between skillups too, and I've been doing most of my digging in Altepa lately.

**Comment by AnkleAssassinz** [comment]
16s-->11s is 200-->400 stacks
 [https://ffxiclopedia.fandom.com/wiki/Chocobo_Digging_Guide](url)

Chocobo digging is working as intended in Eden afaik.  Just keep at it; that wiki guide is not 100% accurate; those are just general estimate numbers imo. If you are counting the greens down, then it will just get 'worse' because the 11s--> 6s grind takes even longer and the final push to a10 will seem crazy.
