### ISSUE TITLE
Marinara Pizza / Chalaimbille OOE

### ISSUE THREAD

**Issue by roriffxi** [EdenServer/community#1582]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [na ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ na] I have provided my client version in the details. (type /ver into your game window)

### Details

Marinara pizza is still being sold.  The recipe is out of era and the Chalaimbille being obtainable at all is out of era.

https://ffxiclopedia.fandom.com/wiki/Marinara_Pizza?action=history
https://ffxiclopedia.fandom.com/wiki/Chalaimbille?offset=20160609153220&action=history

**Comment by Volkaru** [comment]
We already removed the recipe a while ago. What is being sold is back stock. Hence why from now on we're removing the stock a week after the recipe.

**Comment by MGramolini** [comment]
The cheese hasn’t been purchasable for a couple weeks now.

**Comment by MysticLogos** [comment]
I had a short convo last week with Godmode in the ffxi-chat discord channel on this subject, and he said, "Marinara pizza should be removed if it wasn't already.  Just oversight."

There is still lots of marinara pizza stock on the server.  I think it's only fair that the stock of marinara pizza gets deleted at the same time the crab sushi stock gets deleted.  It's long overdue for deletion.

I can understand the reasoning behind removing a recipe, waiting a week, then deleting all the stock.  That seems fair, as long as its consistent.  I just think it's really unfair that people have been making tons and tons of gil off of hoarded marinara pizza stock, which hasn't been available to obtain since Kupo days afaik.

![pol_2019-04-28_18-45-22](https://user-images.githubusercontent.com/45980769/56921365-9b50a080-6a93-11e9-936b-46ba0f9c207a.png)

![pol_2019-04-28_18-45-37](https://user-images.githubusercontent.com/45980769/56921353-955abf80-6a93-11e9-89c4-b00e4ab4f2c8.png)

![pol_2019-04-28_18-45-54](https://user-images.githubusercontent.com/45980769/56921379-a1df1800-6a93-11e9-82fc-d08d040a0804.png)

**Comment by MGramolini** [comment]
You could make the pizza up until 3ish? weeks ago when the NPC in Jeuno was removed.  These are not from kupo as they required fishing to make. (100% eden crafted)

**Comment by MGramolini** [comment]
I suggest any consumable being removed should have a chance to be used up.  As long as there isn't price gouging i don't see an issue with letting it just run out.

**Comment by MysticLogos** [comment]
I just want this to be consistent.  If crab sushi stock is being deleted, there is no reason why marinara pizza stock should not be deleted as well.  Then going forward, just sticking to the remove recipe, wait 1 week, delete stock method seems perfectly fair.  I know there are some other ooe foods being looked at right now, so this is all very pertinent.

**Comment by MGramolini** [comment]
If pizza is going to be removed, it should be given a 1 week warning also, not just removed today. It would be fair to do as I don’t see anything saying the recipe is disabled. I do know that the cheese is no longer purchasable.

**Comment by MGramolini** [comment]
I think we should probably have a separate thread on the forums to be able to see when items are going to be removed from the game instead of having to browse around github or hear it by word of mouth.
