### ISSUE TITLE
Trick Attack effect not wearing off with blue magic

### ISSUE THREAD

**Issue by virden88** [EdenServer/community#1587]
When stacking the trick attack ability with physical blue magic behind someone, the trick attack effect does not wear off. As a result, you can spam spells behind a tank and each one gets the damage boost from trick attack.

However, with blue magic damage being in it's current gimped state, hopefully blue mage is made a viable DD as it was in era before this bug is fixed. As even with this bug, blue mage is just barely a viable DD in 62+ colibri parties. It is marginally able to outparse a well geared PLD, which was not how the job was in era. Without this bug, it is very gimp in terms of damage.

**Comment by Shoruto** [comment]
I'm wondering if the TA effect isn't being removed because the code is reading the blue mage ability as a magic weaponskill instead of physical based attack.  Since it was a physical attack it definitely should of been removed.  Which ability did you use?

**Comment by Elysien** [comment]
Coming from a 75 BLU 'in the era' I guess but, post lv50 BLU was always pretty bad in XP parties, especially against IT targets at those levels where gear options are pretty mediocre. 

Where it dominates and has always only ever been redeemably good with the exception of SA cannonball on Lv80+ targets, is trash level content ala limbus/dynamis/nyzul izle/salvage/etc. If it's bad in those aforementioned scenarios would be cause for concern, but otherwise this sounds about right.

Concerning the actual bug report regarding Trick Attack, this is indeed incorrect. TA effect should be consumed when a physical spell is cast, and take no effect for a magical spell.

**Comment by VirtuosusFFXI** [comment]
Shoruto may be on to something, and it might also explain why physical spells are able to get resisted. (Physical spells should not *ever* be resisted. They should only be checked for physical accuracy, and nothing else. Hit or miss.)

Bludgeon on EXP mobs (VT-IT) is extremely inconsistent and underperforms almost every time compared to Head Butt, for example. In era, reaching 18 and gaining access to Bludgeon was a huge power spike, but on here it feels like a waste of MP. It performs well on Easy Prey through Even Match mobs, which I can only guess is because there's a better chance of landing all three hits as well as not resisting.

If the code is actually reading physical spells as magical and putting them through both accuracy checks and resist checks, it would explain why Bludgeon generally performs well on mobs lower level than you, but terribly on anything higher. The chances of you landing all three hits and not resisting any of them would be very low. It would be comparable to Penta Thrust being able to resist and only do 1/2, 1/4, or 1/8th of its usual damage in addition to being a multi-hit weapon skill prone to missing hits.

**Comment by FallenXI** [comment]
I would going to add this myself ^ that if BLU magic is indeed acting as magic weaponskills than this may be the reason for the resists.

**Comment by virden88** [comment]
@shoruto I did not test them all but it should work with any physical blue magic spell. I believe your theory deserves extra testing because, like the original person to report the bug about blue magic pointed out, it seems like physical blue magic is subject to resists like magical type nukes.

@elysien you are correct, blu has never been a top tier DD nor should they be, considering the support they bring to the table. Saying they were bad in exp in era, however, is silly. BLU DD is focused around spells, not their DoT melee although it contributes. At the 62+ camps, you could CASA Death scissors for 700+ and thats on the conservative side. TA death scissors on the tank was around 400+. I have yet to find a spell that comes close to that damage. I mean dimensional death seems to be more consistent than death scissors here which is very wrong. 

A well geared BLU should blow a PLD out of the water on a parse, let alone using a bug like this.

**Comment by Jimmayus** [comment]
Rather than discuss personal anecdotes about how one feels that blu is currently correct based on vague recollections from a decade ago, or on a singular post from bg, how about we actually relay empirical data collection from this actual server to inform our understanding of the situation:

**Comment by virden88** [comment]
@jimmayus I disagree with you discouraging discussion of personal anecdotes. While you shouldn't base a damage formula or how you code something off of memory or one BG post alone (literally took me 30 seconds, if you need more sources for ballparks) the whole point was to recognize there's an issue in the first place, based off memory... which is what that post was meant to show. Someone who's never played BLU on retail wouldn't know something was wrong with Death Scissors and BLU in general on this server if they didn't have a recollection to go by. And many bug reports that are submitted are first noticed because its not in line with memory (which then opens the issue up to be investigated and fixed based on data). Unless your point was this discussion is more suited for the forums rather than here?

I do agree though that we need more data. Big props to drfistmd for his testing. Unfortunately, I'm not knowledgable enough to know what needs to be tested to make it easier for the developers to fix. Or even how to set up a test appropriately, removing variables. If someone wants to specifically instruct me on how to do this, i have no problem conducting and recording the tests to help.

**Comment by Jimmayus** [comment]
The premise of my post is that there is empirical data from this server that demonstrates an inconsistency in the damage formula. That data, coupled with the strange behavior of trick attack, points to the likelihood that blue magic is not being properly characterized in the code as essentially a physical weaponskill. The second premise of my post is that his anecdotes are unnecessary primarily because we have this data that already indicates an issue. You can see how Elysien posting about how he remembers blu "sucked in retail" and thus nothing is apparently wrong is unhelpful, especially considering this is a bug report about a demonstrably incorrect mechanic.

**Comment by virden88** [comment]
Okay I think I understand your point better now, thanks for elaborating.

**Comment by Elysien** [comment]
@virden88 didn't think we were talking exclusively TA'd/SA'd  spells as a means of main damage, what I said isn't any less accurate really; stacked against other damage dealers vs. VT~IT enemies BLU is, and did, get crushed. The spike damage every 1 minute and terrible damage over time amounts to nothing more than a THF+1, if that. I didn't mean to say you should be getting beaten by a PLD as accurate though, that'll sort itself out when these spells are properly adjusted to work with SATA, which I've heard has been an issue prior to this bug reports creation.

**Comment by DrfistMD** [comment]
The weird thing here is SA does fall off after one use, although I know that had to be manually adjusted after BLU's launch.  Have we confirmed if TA is actually transferring hate when used with BLU spells, or if the buff is not falling off because they're not registering at all, the issue behind the matter might vary depending on the result.

**Comment by DrfistMD** [comment]
Isn't the expected behavior for TA when used as a sub job to only transfer enmity, and not receive a damage boost?  Grabbed from the wiki, and confirmed verbiage matches in the history as well.

"If this ability is used by a character with Thief as a support job, the next strike will not receive any boost in damage whatsoever, only transfer the attack's enmity."

If there actually is a damage boost that alone seems inaccurate, are we sure it just isn't the random variance that seems to be plaguing BLU currently?

Also, have we observed hate actually being transferred with TA?  It seems like there's 2 possible causes, the spells aren't registering at all and the buff is just hanging out as nothing is consuming it.  That or there is very weird logic at play as when we look at how SA works with BLU magic (after the fix) it does seem to be consumed on spell cast as expected.

**Comment by VirtuosusFFXI** [comment]
That's correct, TA when used by /thf never increased damage in era. My BLU isn't 60+ to test whether its doing so here.

I understand that this bug report is specifically about trick attack when used with blue magic, and this may not be the best place to discuss this but I really hope that BLU as a whole gets looked at further. It is by far the most broken and non-functioning job on Eden. Its going to be difficult for any of us to help the dev team out and figure out if any particular spells/formulas are incorrect because as it stands, physical spells being able to resist gives them so much variance that I don't know half the time whether the spell just resisted/missed some hits or not.

These inconsistencies are very apparent every time  you cast any physical spell in an exp party. Seeing one Bludgeon do 3 damage, another do 12, and another do 190 all on the same mob is a bit silly and quite discouraging. With insane variance like that, its going to be impossible for us to determine whether spell damage is being calculated properly.

**Comment by DrfistMD** [comment]
To avoid derailing this bug, there is a forum post where this issue has been brought up and discussed, and is probably the best avenue for continuing that of discussion.  But yes, as others have noted above, and in this thread, and as I've documented myself thoroughly in my own bug reports, something is certainly off currently.

https://www.edenxi.com/forums/viewtopic.php?f=1&t=1263

**Comment by mousseng** [comment]
Per stock DSP, blue magic handlers aren't provided a trick attack entity. if they don't know anything about the TA, they can't divert enmity.

i've slapped together a quick proof-of-concept here: https://github.com/mousseng/darkstar/commit/0c37581f7710478aeb719f7a7a747d999e38697d

**Comment by godmode** [comment]
Although I normally don’t approve of broken mechanics being used as a crutch for other broken mechanics I’m going to allow this one here until blue magic accuracy is fixed. 

However, keep in mind to check this bug report from time to time. In case the verdict on it changes. It was determined that even with this bug BLU is still vastly underperforming with accuracy.
