### ISSUE TITLE
Promy - Vazhl memory flux warps not retaining

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#1602]
As far back as march of 2006 (https://ffxiclopedia.fandom.com/wiki/Desires_of_Emptiness?oldid=54422), everything indicates that after you get the post-mini boss cutscenes at the memory fluxes, you get a warp from the gate in Pso'Xja. This works mid mission, but after completing the mission, the warps disappear and you are no longer able to help people without completely climbing again.

**Comment by Mikokiko** [comment]
When you have multiple people clicking the bosses for the cutscene, it seems it can bug. I never got the cutscene on kiko, I got the message right after the cutscene.

On the next floor, I could not pop the boss. I still had previous CS text in my log, so not sure what happened.

![Kiko_2019 05 04_204814](https://user-images.githubusercontent.com/43910014/57193805-59997d00-6f0d-11e9-990e-3b99c12eb899.png)

**Comment by Satirof** [comment]
Adding to this as my group cleared floor 4 NM today.

The door in Pso'Xja gives me the options to go to Propagator (Floor 3 NM) and Solicitor (Floor 4 NM).
However, the warp to Solicitor does not work (Propagator works fine).
When attempting to use the Solicitor warp it gives me the mini CS of being sucked in by the emptiness, and then makes the screen black, but no zone change. It leaves me outside of the door (but black screen other than UI). Tested it with a LS member, I had not moved on his screen. I am also able to move and interact with anything like normal (including re clicking the door to try again), but nothing removes the black screen other than actually zoning or logging out.

Steps:
1: Kill floor 3 and 4 bosses in Vahzl (Propagator + Solicitor).
2: Wipe, or leave Vahzl
3: Reenter Pso'Xja, proceed to the Door
4: Select Solicitor as warp location
5: Be enveloped in darkness
6: Receive no zone, and black screen (other than UI)

Note: We did not kill the floor 5 NM as we were not about to kill the MR to get to that floor (adding a bug report on that too in seperate comment ([Link here](https://github.com/EdenServer/community/issues/1706#issuecomment-557809528)

**Comment by roriffxi** [comment]
Even going back to Nov. of 2005 it mentions the ability to teleport back.
https://ffxiclopedia.fandom.com/wiki/Desires_of_Emptiness?oldid=25203

i've done the floor climb but never completed the BCNM battle in there due to party make up.  With more COP missions on the horizon I went to check to see if the teleport would work for me and it does not.

**Comment by roriffxi** [comment]
My character marori helped another play fight the NM golem which is int he mission just before this one.  She is unable to teleport (no option to teleport is given to her).

My other character, Rori, did NOT fight the golem and just ran straight up.  She was given the teleport options and the teleport for the 5th floor worked and took her to the correct location.

**Comment by roriffxi** [comment]
Found the bug:
https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/PsoXja/npcs/_i99.lua

update:
elseif (player:hasCompletedMission(COP,dsp.mission.id.cop.DESIRES_OF_EMPTINESS) or (player:getCurrentMission(COP) == dsp.mission.id.cop.DESIRES_OF_EMPTINESS and player:getCharVar("PromathiaStatus")==7))

to 
elseif (player:hasCompletedMission(COP,dsp.mission.id.cop.DESIRES_OF_EMPTINESS) or (player:getCurrentMission(COP) == dsp.mission.id.cop.DESIRES_OF_EMPTINESS and player:getCharVar("PromathiaStatus")>=7))

And it will work.

The bug here is that entering Spire Vahzl updates mission status to 8.  Completing Vahzl sets you to 9.  Currently the cutscene with Cid to complete the mission isn't available to complete the mission fully and the teleport only works if you're specifically on 7.  Which is where you've beat the 5th floor boss and checked the Flux, but haven't yet entered the spire.

**Comment by roriffxi** [comment]
This script is also written for some reason to not allow the teleports if you've completed The Last Verse, which is the final part after doing all of ROZ, COP and Apoc Nigh.  Which I don't find any evidence to say you shouldn't be allowed to teleport afterward finishing up all of the storyline.

This would make doing the Vahzl ENMs pretty much impossible for anyone who got that far in progression, which is something you'd read about.
