### ISSUE TITLE
# diff players SMN macros not working in Ifrits cauldren

### ISSUE THREAD

**Issue by beastffxi** [EdenServer/community#1623]
3 of us were in smn party in ifrits, after the server restarted could not use macros, all of us having the same issues, in different locations , not in the same house or state, seemed to be intermittent, could occasionaly assault and use pet pact but very random, mostly not at all, had to stop attempting to xp due to high risk of death.
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

**Comment by Volkaru** [comment]
Some people are saying this bug is related to standing near a wall. Try to see if you get the errors when you're against a wall, and if you don't when you're out in the open.
People also having issues with curing others in Onzozo when one is standing near a wall in various spots.
Also a couple PUP unable to deploy in different zones.
