### ISSUE TITLE
Non-level-up Skill Cap Issue

### ISSUE THREAD

**Issue by bkesecker** [EdenServer/community#1648]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Player reported from Discord the following scenario lead to a skill cap issue without leveling up the player character.

Dagger was capped at 13 (I think) on RDM at 20. I equipped /THF became uncapped. Went from 13 to 39 in one "sitting", and then did the weapon swap (from Onion Dagger to Decurion Dagger) and suddenly it was "uncapped again".

**Comment by Loglode** [comment]
Similar issue- Combat skills(so far i have noticed Axe, Great Axe, and Katana) at random times will start capping well below their natural cap. This cap appears to take effect after gaining a new skill level, so when I notice it happening, I will check combat skills after every skill level. If it is capped, unequipping the weapon will uncap me so I continue to gain skill ups. Without this "fix" though, the artificial cap WILL prevent skill ups

**Comment by Caelic** [comment]
When hitting a monster at your level or higher level than you, you can continue getting skillups all the way until you cap. However, when you hit a monster lower level than you... say you were lv 10 hitting a level 5 rarab. You can only get skillups up until the point where you would normally cap if you were character level 5. The issue in the code is that it is capping at that point if you happen to skill up to that number. Using DSP to explain, under charutils.cpp function TrySkillUP...

`if ((PChar->WorkingSkills.rank[SkillID] != 0) && !(PChar->WorkingSkills.skill[SkillID] & 0x8000))
        {
            uint16 CurSkill = PChar->RealSkills.skill[SkillID];
            uint16 MaxSkill = battleutils::GetMaxSkill(SkillID, PChar->GetMJob(), std::min(PChar->GetMLevel(), lvl));`

there needs to be a bool check here to see if we're actually using the mob's level or not instead of just using std::min and moving on

`if ((PChar->WorkingSkills.rank[SkillID] != 0) && !(PChar->WorkingSkills.skill[SkillID] & 0x8000))
        {
            uint16 CurSkill = PChar->RealSkills.skill[SkillID];
            bool usingMonsterLevel = PChar->GetMLevel() > lvl;
            uint16 MaxSkill = battleutils::GetMaxSkill(SkillID, PChar->GetMJob(), std::min(PChar->GetMLevel(), lvl));`

so that this check can be used later in the spot (within the same function) where the bug itself occurs, changing the following code from

`if (SkillAmount + CurSkill >= MaxSkill)
                {
                    SkillAmount = MaxSkill - CurSkill;
                    PChar->WorkingSkills.skill[SkillID] |= 0x8000;
                }`

to

`if (SkillAmount + CurSkill >= MaxSkill && !usingMonsterLevel)
                {
                    SkillAmount = MaxSkill - CurSkill;
                    PChar->WorkingSkills.skill[SkillID] |= 0x8000;
                }`

(0x8000 is the "skillcapped" flag)

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update
