### ISSUE TITLE
Lost Garlaige Coffer Key 

### ISSUE THREAD

**Issue by agjevik999** [EdenServer/community#1675]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I recently got a coffer key drop for my AF quest in Garlaige Citadel.  When I lotted the key, I lost the key because I didn't meet the requirements. I had inventory space when it was sorted, and I didnt already have a copy, however I did have a Garlaige Treasure Key in my Mog House.

Now maybe I am totally wrong but I am sure that having both a Treasure and Coffer Key was possible in Era Retail. I am thinking there was maybe a bug that thought the treasure key and the coffer key were the same. 
![Osopi_2019 05 21_130244](https://user-images.githubusercontent.com/49248117/58116409-35ef5b80-7bca-11e9-85ca-ad8aa6d1a1db.png)
![Osopi_2019 05 21_130326](https://user-images.githubusercontent.com/49248117/58116411-35ef5b80-7bca-11e9-9886-16bf9c097d3e.png)
![Osopi_2019 05 21_130343](https://user-images.githubusercontent.com/49248117/58116412-35ef5b80-7bca-11e9-80a9-c9f17915e706.png)

**Comment by xizeta** [comment]
There is a known issue on retail, when several items are pushed out of the pool at the same time (eg. dropped from the same mob). Item one drops, checks inventory space, adds to inventory, runs auto sort, recalculates available space. Item two drops and does the inventory check before item one is finished. A couple of reasons for this could be, auto sort runs asynchronously to the pool code, or the delay from adding the item to inventory (Which should involve a DB write) allows item two to catch up first.

However, it's really hard to know without more logs. You did say "I had inventory space when it was sorted" which indicates you were probably close to the limit and the issue may be caused by the above.
