### ISSUE TITLE
Rare/EX Items unobtainable if a duplicate is in mog storage

### ISSUE THREAD

**Issue by Mallanon** [EdenServer/community#1694]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

**Comment by Raphtalia1** [comment]
you are unable to own, in any of your storagaes (safe, storage, wardrobe, locker, inventory, etc) 2 copies of any Rare item, you can get around this by sending a rare item to your own delivery box, or putting it on the auction house, but you cannot do either of those things with a rare/exclusive item. 

Chest keys are only 1 per character at any given time. Because they are rare/ex

**Comment by bkesecker** [comment]
This is the intended behavior.  The rare tag is the key in understanding why.  https://ffxiclopedia.fandom.com/wiki/Category%3ARare
