### ISSUE TITLE
[Fix ready] Beastmen Treasure side quests not implemented

### ISSUE THREAD

**Issue by kassisaf** [EdenServer/community#1722]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

The [Beastmen Treasure side quests](https://ffxiclopedia.fandom.com/wiki/Beastmen_Treasure) are a set of 3 semi-niche quests from the Zilart era that are a minor pain in the ass to complete, for items that are largely irrelevant now with the exception of [Mermaid's Ring](https://ffxiclopedia.fandom.com/wiki/Mermaid%27s_Ring). Currently they are missing from DSP, but **[I've implemented them on a feature branch here](https://github.com/DarkstarProject/darkstar/compare/master...ababyduck:quest-beastmen-treasure)**.

**Summary of the quest mechanics:**
Peddlestox is a gob that appears in Yuhtunga Jungle, Yhoator Jungle, and Western Altepa Desert, each on one specific day of the elemental week. You have to catch her during that day to flag* the quest _(* = it does not appear in the quest log, hence "side quest")_. If you're missing the map for the area, she scolds you about it. If you do own the map, she'll tell you to go collect 4 items from local beastmen. Bring the items back to her and she gives you a semi-random dig location where you can go and excavate your reward. Excavating gets you 4,000gil and 4 items, one of which can be the "unique" item for the area ([Mermaid's Ring](https://ffxiclopedia.fandom.com/wiki/Mermaid's_Ring) for Yuhtunga, [Bitter Earring](https://ffxiclopedia.fandom.com/wiki/Bitter_Earring) for Yhoator, [Sand Mantle](https://ffxiclopedia.fandom.com/wiki/Sand_Mantle) for W.Altep). These are not 100% rewards, and the quest is repeatable.

**Some gotchas:**
- The ??? you're sent to to excavate is _supposed_ to be invisible until you're within something like 5 yalms of it. I've left this out and made them always active, since A) I don't believe there's a performant way to achieve this in current DSP, and B) this benefits people using a certain cheat.
- Peddlestox is supposed to play a teleport spell animation before fading out when she leaves for the day. DSP doesn't currently support the animation packet used by retail, but I've left notes in the code for how to play it back if/when we're able to send 0x3A. For now she just disappears instead, with no animation.

**Other info:**
There's not a lot of existing information on these quests, due to how niche they sort of are. I reverse engineered the event args to find every dig site, and compiled a list of every drop report from old Alla/BGLS posts to figure out the loot pools. [I've compiled all of that info plus some helpful DSP commands and a db update script here](https://docs.google.com/spreadsheets/d/1Xw4fZ3ixM2sLCMq57IH19oEblpi_TZt0gLtVXyKar48/edit?usp=sharing). **There are 4 separate sheets at this link, so be sure to check the tabs at the bottom of the page.**

**Comment by ababyduck** [comment]
Also big thanks to Imakyl for the retail capture!

**Comment by ababyduck** [comment]
In retrospect, the weighted loot can also be generated at startup, so I'll likely fix that when I get back.

**Comment by ababyduck** [comment]
Weighted loot tables are new generated once on server startup so that it never has to be done on runtime.

addLoot() should probably be rewritten to be Lua-version-agnostic. (DSP ships with Lua 5.1, but Lua 5.2+ made changes to table methods in the standard lib that are relevant here. When I discussed this with godmode on discord he said he just won't update Lua, so this may be a non-issue for Eden.)

I would also like to double-check all of the fetch items in the db to ensure they all drop from the correct mob with the correct rates, but the Eden db deviates from base DSP on at least one of these mobs, so someone else will have to verify that. Imakyl has verified that all of the mermaid items drop from the correct mobs on Eden. Drop rates for the sahagins, and antican/tonberry drops are probably fine, but should be verified.

Otherwise, this is fully functional and ready to go, pending review.

**Comment by ababyduck** [comment]
Some improvements have been made since posting this. Weighted loot tables are now generated on server startup, drops have all been verified and corrected where necessary, and the concern over Lua version has been alleviated. Also the entire branch has been squashed down into a single commit to keep the PR clean and digestible.

**Comment by KnowOne134** [comment]
This was added in some time ago. Ty for your work in it
