### ISSUE TITLE
Windurst Mission 2-3

### ISSUE THREAD

**Issue by Rand87** [EdenServer/community#1735]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

After completing the BCNM in Waughroon Shrine, the cut scene freezes and I am forced to close program.  After logging back in, I am outside the zone and do not receive the key item needed to complete the mission. I have done it twice with the same results.

ver: 30190430_0

**Comment by alex69** [comment]
Have you tried "Print Screen" ? Worked for me for a cutscene for CoP mission.

**Comment by xizeta** [comment]
The cutscene freezing is due to your client version. Please make sure you are using the latest release from the Eden website. However, because this has been a common issue, we just added a patch that will allow progress even if this cutscene does not properly complete. If you clear the battlefield again, your progress will be updated even if the CS locks up. Sorry for the inconvenience.
