### ISSUE TITLE
Reraise doesn't take effect if killed during a cutscene

### ISSUE THREAD

**Issue by PatricYuumi** [EdenServer/community#1806]
I was going to get my first staging point after getting whitegate access. Omw to azouph... I got aggro from Imp. I ran far while it was casting to get to safety, this way I can use my Reraise earring.

I see Yuumi gains the effect of Reraise.
I see buff.

Imp didn't hurt me, he only cast Drown... I think maybe I'll run to staging point door and go die there and reraise... I run... Take a few hits from Jhun.

I get to staging point. I die while in that small cutscene to zone into staging point area.

On otherside I'm dead with no option to reraise. Long 2 boat rides back to Nashmau here I come. Reporting bug no one else has to suffer this.

### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by godmode** [comment]
Thanks for the report. Unfortunately we have some work to do yet for making monsters de-aggro once you enter a cutscene. But it should not be possible to die in a CS. This issue exists as is but won’t in the future. We will be spending time figuring out the correct implementation rather than on figuring out how to bandaid it.
