### ISSUE TITLE
Bugi Soden > True Will

### ISSUE THREAD

**Issue by Kurtalicious** [EdenServer/community#1823]
Ryoma (Ninja NPC in Norg) is giving me the quest Bugi Soden (Kodachi of Trials) and will not give me True Will (AF body quest).  What do I have to do to activate the AF body quest?

**Comment by bkesecker** [comment]
For development team: Unfortunately, there are many quest givers who require a certain order to progress questlines (missions mostly seem to already be ahead of quest checking).  This is mostly due to the way quest logic is written in the Lua scripts.  Instead of a linear set of condition checks, they need to be changed to be tree-based decisions.  Changing this would be a major overhaul to the standard quest logic and would require a lot of testing.  Koru-Moru and Halver are prime examples.

**Comment by KnowOne134** [comment]
Has been corrected as all wsnm quest were moved to a new non blocking system
