### ISSUE TITLE
Orlando's Antiques ( Repeatable Quest )

### ISSUE THREAD

**Issue by JIFCode** [EdenServer/community#188]
Orlando's Antiques in Mhaura doesn't appear to be working. I used beastcoins ( in the required stack of 8 ) and only beastcoins. I do not have any of the other required items for testing.

I spoke to Orlando and tried to trade him the stack multiple times with no feedback from the npc on trade.

**Comment by Althaia** [comment]
That's odd, because I've done Orlando's Antiques with beastcoins many times. I only started playing this summer, though, so I don't know when you guys might've implemented this.

Perhaps the person who couldn't get the dialogue was not of sufficient level to ride a chocobo (Level 20), which is Orlando's prerequisite before he'll even talk to you about it. He'll even say he doesn't have any business with someone who can't ride a chocobo.

I couldn't do this quest when I was about Level 16-18, but I returned after receiving my chocobo license and talked to Orlando with a job that was at least Level 20, which worked. I don't if it's just a level requirement or you need the actual license, but either way, this quest has been working fine for me.

For reference, I've only ever done the quest by trading a stack of 8 beastcoins to Orlando.

Additionally, unlike many NPCs, you have to talk to him again before you can repeat the quest (he asks you how it's going and wishes you good luck).

Not a big deal, but just saying if you're trying to trade a stack repeatedly, you'll have to initiate that additional dialogue every time before it works.
