### ISSUE TITLE
Abjuration Drop Rate on Kings/Gods

### ISSUE THREAD

**Issue by ultimazero** [EdenServer/community#1886]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

The abjuration drop rate does not seem era accurate. In era, 2 abjurations was the norm but it seems that on Eden they only drop 1 abjuration 95% of the time.

**Comment by godmode** [comment]
None of the checkboxes ticked are actually here. Please fill out some information. It doesn’t need reproduce-able steps but statistics will help. Like times killed vs times with double drops.

**Comment by roriffxi** [comment]
Aspid and KB have both given us a double drop a few times, but we stopped keeping such detail to know the exact number.  Absolutely no way has it been more than 5 times for either of those. 3 or 4 at the most though.  Fafnir and nidhogg have never given a double abj for us.

22 KB kills
20 Aspid
27 Nidhogg
116 Fafnir

Side note: There have also only been 7 ridill drops out of those 116 kills.

This accounts for roughly half of the kills on the server up to this point.

**Comment by StriderClerix** [comment]
> Aspid and KB have both given us a double drop a few times, but we stopped keeping such detail to know the exact number. Absolutely no way has it been more than 5 times for either of those. 3 or 4 at the most though. Fafnir and nidhogg have never given a double abj for us.
> 
> 22 KB kills
> 20 Aspid
> 27 Nidhogg
> 116 Fafnir
> 
> Side note: There have also only been 7 ridill drops out of those 116 kills.
> 
> This accounts for roughly half of the kills on the server up to this point.

Thank you for providing actual numbers, not fake %'s

**Comment by Oyaziiiiiii** [comment]
Just wanted to bump this because the rate on the second abjuration is still much lower than retail, especially for Faf/Nid. Since the beginning of Eden, Spoondaggers has had 0 Fafnirs and 1 Nidhogg drop 2 abjurations. We've killed Nidhogg 36 times and Fafnir 200 times. King Behemoth and Aspid have dropped more often than Nidhogg but still not at the 20-25% clip. I could go back through the logs and get exact numbers on these if needed but I can't imagine it has been more than 3-4 times each.

Other data that might be useful:
Our Ridill rate with TH3: 11/200(5.5%)

Sources: 
https://www.bluegartr.com/threads/42316-Fafnir-Nidhogg-Statistics
https://ffxiclopedia.fandom.com/wiki/Nidhogg
https://ffxiclopedia.fandom.com/wiki/Fafnir

**Comment by 59blargedy** [comment]
related to https://github.com/EdenServer/community/issues/2695 and resolved a couple months back to consistently have 1 guaranteed drop per king and a rarity 4 chance at an additional abjuration
