### ISSUE TITLE
switch monitor

### ISSUE THREAD

**Issue by gannony** [EdenServer/community#1950]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by godmode** [comment]
There are no details or boxes checked. In addition if this is an issue with a third party utility it is not something that we support—even if it is allowed.

**Comment by benwelker** [comment]
I know this issue is lacking in details, but if you're referring to moving the game to another monitor try the /move command.  Once logged in type the following:

`/move 1920 0`

This will depend on your monitor resolution and if it doesn't work, you may need to try -1920 to move it the other way.

You can also add that to your startup config for Ashita I believe.
