### ISSUE TITLE
Level Restrictions on Pet Food is out of Era

### ISSUE THREAD

**Issue by Wade9363** [EdenServer/community#1970]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Beastmaster Pet Food items did not have a level restriction added until 9/3/2010.

http://www.playonline.com/pcd/topics/ff11us/detail/5811/detail.html

**Comment by godmode** [comment]
This will make something like the zeta biscuit go from 900 to 350 HP restored. This may be a balancing issue but thanks for bringing it up. Do most BST think it would be better to have the lesser limit with lower HP? If so, then it's an easy decision to make it era.

**Comment by KnowOne134** [comment]
Also removes the regen, but the dat is coded to lvl 72, would need a dat edit to be equipable

**Comment by greyenvy** [comment]
This is one of those changes I think is fine as-is.  It will cause some serious confusion and the reality is no one is going to use Zetas at level 30.  The food is scaled appropriately and the level restriction is a great guideline.  That's my .02 as a BST75.  Maybe Azmanz will have an opinion on this too.

**Comment by Wade9363** [comment]
I don't think anyone who has played Bst would trade removing the level restriction on pet food for a decreased HP from Reward.  It would nerf reward at all levels.

I almost never used pet food in Era Retail because it was practically useless at all levels; 350 HP cured every 3 minutes when XP mobs are doing that much damaged every 2-3 auto-attacks.  

Re: KnowOne134 - Pet food did have a regen effect in 2006.  Here is a forum post from the time discussing it:  https://www.ffxionline.com/forum/ffxi-game-related/race-job-type-q-a/beastmaster/59290-pet-food-regen-effect

**Comment by mlandrum22** [comment]
(This is Azmanz)

This would make all pet foods obsolete aside from Zeta since Zeta isn't really that much more expensive and would be better at all points.

Pets have ~2400 HP I think, 350hp every 3 minutes would basically make reward useless.

We wouldn't be able to melee since we'd be getting pets much more often and our new pets wouldn't be able to grab hate off us since we don't have Snarl.

I think all the changes SE made to BST were great (obviously) and made the job much more enjoyable and farrrrr more adaptable/customizable. With the recent Reward change (to 3:00), it makes it VERY tough to survive in Beastman zones (or other high level zones) w/ nothing to charm -- and we're basically stuck only using CC since she survives the best.

If we lower Zeta to 350 hp, we'll be forced to only stay in Attowa Chasm, the Boyada Tree and Den of Rancor for the rest of our lives as those are the only places with level 75 charmable pets.

**Comment by KnowOne134** [comment]
Was resolved in 5/3/2023 update
