### ISSUE TITLE
/assist no longer working properly

### ISSUE THREAD

**Issue by Tjonke** [EdenServer/community#1978]
### Checklist

- [ X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

While doing Dynamis-Bastok we noticed that /asssit no longer cares if the assist target is engaged or not, it only mattered if he was targeting a mob and /assist would engage on that monster.

**Comment by godmode** [comment]
It used to work only if someone was engaged only? When did you notice it last working correctly if so?

**Comment by Tjonke** [comment]
Only noticed the issue this last Dynamis, haven't had any problems previously.

**Comment by OverTheNeptune** [comment]
That's how /assist has always worked here (or a least since late last fall when I started playing). That's how i remember it working in retail too but it's been a long time since i played there.

Our group uses timed nukes on some statues in dynamis and we use /assist for targeting. It's never required the person we /assist to be engaged. Also, my wife played for a little when I first started. I helped her set up an /assist macro so she could easily target whatever we were fighting. Sometimes I would just target without engaging and let her practice "pulling" mobs back to us. Her /assist macro worked as long as I had something targeted.

**Comment by icariumkupo** [comment]
In era /assist only worked if the person was engaged. Don't you guys remember mashing assist macro waiting for your assist guy to engage? My Dyna group used to have a guy dedicated to this by standing at range and engaging the next target.

**Comment by mlandrum22** [comment]
I don't believe there's been a change recently on Eden. 

Last night Toth would engage a mob and then look around to provoke/flash the next target and our /assists were taking us to that 2nd target. While I like the idea that we don't need to be engaged for /assist to work, it would be nice to go towards the tank's engaged target over where he's currently looking -- if that's even possible.

**Comment by Treble011** [comment]
/assist has always required the assisted player to be engaged to the best of my knowledge. Even to this day when I want BLMs to target something specific, I'll engage it just so they can assist me.

**Comment by Tjonke** [comment]
Yes Treble, that's exactly how it has worked all the time previously. Now in Dynamis it was enough for me to even target a mob, not even provoke or flash or anything and the /assist macros would target the mob I had targeted. This didn't use to be the case.
