### ISSUE TITLE
Spirit's Within Dmg is being Calculated into Breath DMG

### ISSUE THREAD

**Issue by Drognand** [EdenServer/community#2011]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

So I was doing some digging in the DSP lua and was curious about Spirit's within because i was noticing on pots and and things that Spirit's was doing less dmg then on a monster with less Mgk Def and thats where I found it.

function onUseWeaponSkill(player, target, wsID, tp, primary, action, taChar)

    local HP = player:getHP()
    local WSC = 0
    local tpHits = 0
    -- Damage calculations based on https://www.bg-wiki.com/index.php?title=Spirits_Within&oldid=269806
    if (tp == 3000) then
        WSC = math.floor(HP * 120/256)
    elseif (tp >= 2000) then
        WSC = math.floor(HP * (math.floor(0.072 * tp) - 96) / 256)
    elseif (tp >= 1000) then
        WSC = math.floor(HP * (math.floor(0.016 * tp) + 16) / 256)
    end

    if (USE_ADOULIN_WEAPON_SKILL_CHANGES == true) then
        -- Damage calculations changed based on: http://www.bg-wiki.com/bg/Spirits_Within http://www.bluegartr.com/threads/121610-Rehauled-Weapon-Skills-tier-lists?p=6142188&viewfull=1#post6142188
        if (tp == 3000) then
            WSC = HP
        elseif (tp >= 2000) then
            WSC = math.floor(HP * .5)
        elseif (tp >= 1000) then
            WSC = math.floor(HP * .125)
        end
    end

    local damage = target:breathDmgTaken(WSC)
    if (damage > 0) then
        if (player:getOffhandDmg() > 0) then
            tpHits = 2
        else
            tpHits = 1
        end
    end
    if (player:getMod(dsp.mod.WEAPONSKILL_DAMAGE_BASE + wsID) > 0) then
        damage = damage * (100 + player:getMod(dsp.mod.WEAPONSKILL_DAMAGE_BASE + wsID))/100
    end
    damage = damage * WEAPON_SKILL_POWER

    damage = takeWeaponskillDamage(target, player, {}, primary, damage, dsp.attackType.BREATH, dsp.damageType.ELEMENTAL, dsp.slot.MAIN, tpHits, 0, 0, 0, action, nil)

    return tpHits, 0, false, damage

end

Now from what i remember on retail the equation parts are right however the Damage should be its own Damage with nothing being able to resist it. Its like stone skin where a mathimatical equation determines its out come and nothing other then that equations effects it.

**Comment by godmode** [comment]
Very nice. Thanks for the through research. For some reason it feels like non-elemental magic to me. Something like Meteor where MDT would affect it but not MDB.

**Comment by gweivyth** [comment]
I'll meas with it tonight. I messed with it a little bit after you and I talked about it and I couldn't figure out a great way to make the damage "true" without crashing my test realm.

**Comment by Drognand** [comment]
If you can figure this out it will help with what we saw on excalibur as well. Where the dmg is supposed to be more true but isnt coded as such. Sorry I can't be of more help with it right now.

**Comment by Raphtalia1** [comment]
I don’t think Mdef effects meteor, it should just do a set amount of dmg, except that the pld merit fealty should reduce it to 1/16

**Comment by everlast101069** [comment]
According to the old bg info meteor was at least dark based for absolute virtue.

https://www.bluegartr.com/threads/81211-Absolute-Virtue-Information-(OP-Updated)/page11?s=6a40045830b1f6af3ab985a3e50b654e

A quote from there:
"Ya I don't notice our PLDs getting resisted almost ever in videos, them having baraero so roughly +100-120wind. I personally tried dark elemental resist build with my RDM against both AV and KB, and I got 1/2 1/4 and 1/8 against KB (it obviously generally doesn't get many meteors off), and 1/2 a few 1/4 and maybe one 1/8 resist with roughly +200 (no dark carol as there was a lot of confusion).


With augments the best possible +dark resist is probably ridiculously high now, and you can get +dark augments on items that have MDB or -MDT on them. Obviously getting the augments you want is unbelievably rare tho. My assumption would be that around +250 is needed to resist reliably enough to warrant you replacing a full MDB/-MDT build for full +dark or +wind. The fact is, if you are in full resist build for Meteor and you don't resist it, you die because you will take ridiculous damage with no MDB -MDT equipped (unless you are PLD due to Aegis)."

**Comment by 59blargedy** [comment]
per https://www.bg-wiki.com/ffxi/Spirits_Within and the linked forum posts, breath damage is correct for spirits within.
