### ISSUE TITLE
Fafnir/Nidhogg TP regain too low

### ISSUE THREAD

**Issue by Oyaziiiiiii** [EdenServer/community#2024]
Fafnir/Nidhogg TP regain seems too low recently. With 0 TP feed, it took Fafnir just over 4 minutes to use a TP move. We didn't time Nidhogg but his seems low as well. 

### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by Oyaziiiiiii** [comment]
I guess this is similar to [#272](https://github.com/EdenServer/community/issues/272) but applies to both Fafnir and Nidhogg.

**Comment by Oyaziiiiiii** [comment]
After watching Nidhogg today, I believe it might actually have 0 regain for the first 74%. I think an update may have broken this semi-recently. In 31 minutes of fighting, it used a TP move 10 times total and only twice before 25%(Two TP moves in about 22 minutes of fighting).  After 25% it used 8 TP moves in about 9 minutes of fighting.

**Comment by Corvinus1337** [comment]
Commenting because this is still an ongoing issue. Nidhogg's regain is not era-accurate currently (I.e. way too low). Iirc Nidhogg's regain should be at least equal to Fafnir but that doesn't seem to be the case. Can someone double check if it's even got regain active at >25% health? Secondly can it be verified if the the regain value is accurate and not something absurdly low as it appears right now.

**Comment by 59blargedy** [comment]
resolved december 7 update. fafnir regain already correct.
