### ISSUE TITLE
ZM8 Kam'lanaut doesn't use Light Blade or Great Wheel

### ISSUE THREAD

**Issue by Oyaziiiiiii** [EdenServer/community#2053]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Fought him today and he didn't use Light Blade or Great Wheel. I'm not sure if the elemental blade moves count as a TP move but he only used those.

Ver 30190328_2

**Comment by Slamm21** [comment]
That's odd, I did it about 20x before for various ls members, last kill about 7 weeks ago and it definitely used those two abilities. Light blade was the only dangerous move he did really.

I have not killed it since then so it is possible but I would guess it was just a coincidence in that one fight.

**Comment by Oyaziiiiiii** [comment]
He used them in the past but I suspect maybe something broke with one of the recent merges.

**Comment by FariskaEden** [comment]
Can confirm, did this fight again today and he only used enspells along with his aoe spells. Did not see light blade or great wheel get used.

**Comment by 59blargedy** [comment]
resolved with the April 5, 2021 update
