### ISSUE TITLE
Out of Era NM's (Synnergy)

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#206]
https://github.com/DarkstarProject/darkstar/blob/09b3ddfe5f24190203a2ceb225c479bcc699d045/scripts/zones/FeiYin/mobs/Jenglot.lua

http://ffxiclopedia.wikia.com/wiki/Jenglot

While not a big issue, he spawns right near Miser Murphy (RDM AF NM) and is magic aggro. Could be a problem for newer players, and he has no purpose on this server since we don't have Synergy

**Comment by beauxq** [comment]
I recommend changing issue name to refer to all synergy NMs. It might be easier to deal with all of them at once instead of one at a time.

Here is a SQL query that SHOULD find all of them, but it doesn't find all of them because DSP doesn't have all the drops.
(It seems Jenglot should drop synergy items, but he doesn't in current DSP.)

SELECT * FROM(SELECT * FROM dspdb.item_basic WHERE name like "aptant%") AS aptants

INNER JOIN dspdb.mob_droplist ON aptants.itemid = mob_droplist.itemId

INNER JOIN dspdb.mob_groups ON mob_droplist.dropId = mob_groups.dropid

INNER JOIN dspdb.mob_pools ON mob_groups.poolid = mob_pools.poolid
