### ISSUE TITLE
Kirin Fire Breath Spam

### ISSUE THREAD

**Issue by Slamm21** [EdenServer/community#2090]
### Checklist

- [ Y] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ Y] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ Y] I have provided my client version in the details. (type /ver into your game window)
client version 30181205_0
### Details

Kirin has 6 abilities without counting astral flow, and 5 spells. These are:
•	Heat Breath
•	Great Whirlwind
•	Great Sandstorm
•	Tail Smash
•	Tail Swing
•	Deadly Hold
•	Rasp
•	Quake
•	Stone V
•	Stonega IV
•	Sleepga

If you straight tank him, he seems to use all of these abilities equally.

However, if you kite him, he seems to uses Heat Breath around 90% of the time. This makes it extremely difficult to gain hate, especially without W legs.

On retail, before we started tp burning it I used to tank him on RDM/NIN and by the time the alliance had finished killed the ads I had capped CE so I could just run forever and never lose it if I wanted to. Even if your alliance could barely land gravity, once you got used to it it was easy to keep hate and avoid most or all attacks.

This is because he would equally try to use the abilities depending on how close you were. From memory it was mostly the spells + great whirlwind he would do and heat breath was rarer. This is why it says on the ffxiclopedia “It is advised to keep Baraera up rather than Barfira or Barstonra if Kirin is being kited, as kiters should be able outrun Stonega IV with ease.”

Because heat breath is spammed, you can avoid most by using the pillars but the odd one still hits, and unless you get very lucky with him suddenly doing quake or stone V you can’t get stoneskin back up or do a cure because you just have to keep moving. Not only that, you cannot spam hate spells like sleep and dispel which you could on retail and so when you do take damage you lose any hate gained. 

Essentially right now aside from when straight tanking it, only a PLD is viable for the fight, making NIN/DRK and RDM/NIN pretty shitty as tanks when the adds are dead.
Perhaps it is a similar bug to this NM which just spams Refueling?
https://github.com/EdenServer/community/issues/398

Reading this back now, perhaps he is spamming it until it lands and then he does a spell or different move after? This would explain why he only does it when kiting. We are doing more Kirins on the weekend so I will try to see if that is the case.

As for heat breath damage, while I know this is based on HP and it can only be reduced from -breath damage taken gear, could this not also be resisted on retail with fire resistance/barfira? On Eden it never resists and always hits for full damage it seems. This is not just Kirins heat breath but heat breath from all mobs.

Regardless the fight is fun and just makes the strategy different

**Comment by Falaras** [comment]
We noticed this problem too. The way I saw it was that Fire Breath has a longer range than his melee attacks, so when he was being kited he was using Fire Breath as soon as he got into the exact range for it instead of running closer and using all his WS like on retail. Anytime I was in true melee range he would use all his skills like he should. It was pretty dang frustrating having the only WS that he ever be used be something I can't even use gear to lower the damage of. We also had some pretty wonky hate stuff but I couldn't tell what was going on so had to nail down.

**Comment by Slamm21** [comment]
yeah, lots of people tell me "kirin hate is bugged" it's not, it's just this fire breath spam and the fact it does a set 500dmg means you lose hate so easy.

**Comment by godmode** [comment]
This is because you are out of range of other abilities. Each mob skill just like abilities have a range that it can reach. Heat Breath is an extended range so you will get that most often if you are out of range. Now, if there are moves that should target players around Kirin rather than players around the target that is a different story and we already have code in place fixing that from the grand wyrms update.

As far as controlling hate I have observed several linkshells that are able to kite Kirin—rarely taking damage. Even some without movement speed.

But back to the matter at hand. If you can find retail videos showing Kirin using various moves at similar distances that would be the best thing to add to this report.

**Comment by Falaras** [comment]
I can't seem to find perfect examples, but after looking at a ton of videos I've seen situations where you can see it. For example if you look at this video https://youtu.be/w9U3usqjOt0?t=181 you will see him run into range and then use his WS (Deadly Hold), how this interaction would work on Eden is he would run not as far, then Fire Breath you from max range, and then his next WS would then be something like Deadly Hold because he is now in range after his WS delay. Maybe someone can find a better video, there aren't many that just focus on the kiter sadly. 

As someone that kited a lot of Kirins back in the day it was immediately noticeable how wrong it was that he was spamming Fire Breath so heavily. Heck I remember he would run at me at top speed and then immediately use Tail Swing and it would look like he was gliding while Tail Swinging at a moving target.

**Comment by godmode** [comment]
Ah. Then this will likely require a refactor of mob skill queuing. Right now it just goes off of time and then checks skills in range. This shows me that it should queue a skill and hold it until the target is in range.

**Comment by Slamm21** [comment]
yeah it was the first thing I noticed when we did Kirin, on retail it was very common to see things like him readying deadly hold and then "Slamm is too far away" over and over. Same for great whirlwind.
I also miss the tail swing gliding lol

**Comment by Slamm21** [comment]
Noticed this has been fixed, closing.
