### ISSUE TITLE
Dynamis - Alliance break bug

### ISSUE THREAD

**Issue by Raphtalia1** [EdenServer/community#2141]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

In dynamis-windurst our alliance broke due to some kind of bug, afterwards claims were no longer shared across parties or zone breaking and reforming alliance didnt help, mobs suddenly started to grant exp when killed

Unsure what kind of steps lead to this break, or how to reproduce, but it made continuing the run with any real success impossible, luckily it happened in our last 30 minutes, if it had happened earlier it would have been far worse

**Comment by Mozzy4Ever** [comment]
Odd that mobs would start to give XP... You say this was in your last 30 minutes, was this after win so people were leaving?

**Comment by Raphtalia1** [comment]
This was prior to win, an alliance break preceded the issue (where the alliance bugs out and you can’t invite or drop so you need to /acmd and /pcmd leave then reform

We actually had another 40 minutes of TE’s left

**Comment by mlandrum22** [comment]
We’ve had similar issues where if one of the alliances breaks, they can’t fight mobs of the other alliance until all members in the 2nd alliance logged.

The last time it happened was also dynamis windurst. 

I don’t believe anyone got XP though.

**Comment by perkuprightmeow** [comment]
This happened again tonight -- were able to fix it by completely dissolving the outside alliance and fixed when it was reformed. 

We were getting EXP and loot pools were distributing oddly. Some mobs were un-attackable.

**Comment by setsuk0** [comment]
Tonight we had players disband from alliance and warp out to job change for Dynamis Lord. When everyone came back into the zone and the alliance was reformed, we pulled Dynamis Lord. The entire main alliance obtained the your target is already claimed/cannot attack error message. DL was pulled by someone not in a party, and the RDM/DRK party was able to cast on DL, but the main alliance was not. I am not making a new bug report since this seems to be slightly related. For clarification, though, we did not have the alliance bug out. We completely disbanded the original two alliances and completely reformed prior to the dynamis lord attempt.

**Comment by Slamm21** [comment]
Yeah we had this recently in sandy and it was a nightmare.
It seems to be caused most of the time by someone warping out and then disbanding or logging instead of waiting to be kicked.

**Comment by Mozzy4Ever** [comment]
I believe this was fixed (alongwith several other dynamis bugs) on February 15th, 2021. 
![image](https://user-images.githubusercontent.com/11255886/113517483-caa49d80-9545-11eb-9782-0ea733b8d54e.png)
https://discord.com/channels/482610771126386688/670735434799644690/810894527874990081
