### ISSUE TITLE
AH listings have no name, can't be removed

### ISSUE THREAD

**Issue by rpcon** [EdenServer/community#2203]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Two AH listings have no name, and cannot be removed. I don't remember the initial post date.

Screenshot here: https://imgur.com/a/x9heLjq

There is definitely enough space in inventory, and there are already 8 of said item in inv as well. It's not rare.

Steps to reproduce: 1. Go to the AH and select "Sales Status".

**Comment by Raizuo** [comment]
Having the same issue. 5/7 no named items with 0 sell history on them. All item seems to be different with different prices.

**Comment by spaceIdiot** [comment]
having the same issue as well.  
![image](https://user-images.githubusercontent.com/39474306/69315701-b8e68280-0bfc-11ea-9b40-9078bf722e77.png)
![image](https://user-images.githubusercontent.com/39474306/69315711-c00d9080-0bfc-11ea-82e3-5823228779a3.png)

**Comment by Kusarigama-Eden** [comment]
![Kusarigama_2019 11 21_000355](https://user-images.githubusercontent.com/58048122/69367657-4908e400-0c5e-11ea-9063-80a91c1e7d6c.png)

Same issue

**Comment by Giak1982** [comment]
![IMG](https://user-images.githubusercontent.com/55852850/69385934-47bcd300-0cc1-11ea-885b-6a4e11da0c3e.jpg)

Same too char name Minerslave and Toscanello

**Comment by godmode** [comment]
I suggest not posting things on the auction house until this issue is fixed for those that are debating it.

**Comment by Kusarigama-Eden** [comment]
It still is not fixed I cleared the AH and my Power Bow +1 Magically came back but i still have a blank space after the update. I don't know if anyone else had this happen yet since the update.

![Kusarigama_2019 11 23_004304](https://user-images.githubusercontent.com/58048122/69474775-8a96ad80-0d8a-11ea-83f9-d31c4c18fbfb.png)

**Comment by godmode** [comment]
That means you had another item with the bug too.

**Comment by godmode** [comment]
This should be resolved. If the same issue continues please comment on this bug report. If you have questions about your items but no details to add place a GM ticket. Since this is just myself who will be looking into these issues please expect delays. So the more details you provide the first time the more timely the resolution.
