### ISSUE TITLE
Meteorite item from crawlers in West Sarutabaruta

### ISSUE THREAD

**Issue by SleazyFFXI** [EdenServer/community#2220]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
The crawlers in West Sarutabaruta do not drop meteorite,   a few on the far west side do but none near starfall hillock do which is the way it's supposed to be.

**Comment by Althaia** [comment]
I have definitely noticed meteorite coming from the Crawlers on the far west side (like along Crawler Way, that stretch of road between Waters and Port entrances that's full of crawlers), because the first time I got it, I remember thinking "Huh, it's way over here? Shouldn't it only be on the hill?"

It's been a long time since I specifically hunted the crawlers on/near Starfall Hillock for the Meteorite, so I don't remember if it dropped there, too...

I just assumed it was in the loot table for all West Sarutabaruta crawlers.

I think I may've gotten it from those Starfall Hillock crawlers at some point (I started playing over the summer), though, so I wouldn't completely rule that out. I guess you could take a look at the loot for all West Sarutabaruta crawlers.

**Comment by Leonira** [comment]
I have gotten meteorites from crawlers in west sarutabaruta ALL OVER the region. starfall hillock, by the windurst gates, near giddeus, all over. I have a couple stacks of them in my mog house...

I think it's like Althaia mentioned, They're probably just in the loot table for crawlers in general, but have a pretty terrible droprate. (they always did have a bad droprate)

**Comment by 59blargedy** [comment]
resolved in May 31, 2021 update
