### ISSUE TITLE
Leepe-Hoppe no longer gives Fenrir quest after defeating it several times before.

### ISSUE THREAD

**Issue by Kobe3000** [EdenServer/community#2239]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Leepe-Hoppe no longer gives me "Moonlight Path" quest after defeating Fenrir multiple times now. Just regular dialogue.
![bug](https://user-images.githubusercontent.com/48469915/69911170-6c553100-13cc-11ea-8e13-b2c807c31736.png)

**Comment by godmode** [comment]
Hey Kobe, unfortunately there is not much details here about your character history other than you've completed it many times before. Please add more details or have someone else confirm that can give more reproducible steps. Otherwise we will just have to wait to fix it when we learn more about it.
