### ISSUE TITLE
TH4 appears weaker than TH3

### ISSUE THREAD

**Issue by Oyaziiiiiii** [EdenServer/community#2274]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I don't have a ton of data to go off of yet, but from what my linkshell has seen so far TH4 appears to be weaker than TH3. Other people I've talked to have noticed something similar. 

We almost went an entire Dynamis Bastok run with one 100 drop(with TH4), decided to swap to TH3(TK equipped, no AA) for the last 15 or so stats and got two 100s. We farmed waters in sky for a few hours tonight, TH4 wasn't yielding much so we swapped to TH3 and got 5 waters pretty quickly. Requesting an audit please to double check that TH4 is working correctly. I'll continue to update as more data comes in.

**Comment by setsuk0** [comment]
We did Dynamis-Jeuno on Tuesday. With TH4, we had about 260 currency, including only one 100 piece for the entire run. We only had three pieces of AF drop, with the first piece not dropping until about an hour and a half into the run. In the past, even in our worst dynamis runs with lots of deaths, we would typically still see at least 500 currency. We have Windurst scheduled Saturday, so I can provide another update then, but something definitely seems off.

**Comment by jmcmorris** [comment]
I reviewed the treasure hunter code and everything appears to be correct. We will continue to keep an eye out for things but keep in mind that with a small sample size the droprates between any level of treasure hunter is going to have a fairly large variance.

When I have time I will run a thorough simulation on the different treasure hunter levels to be certain that things are indeed correct.

**Comment by roriffxi** [comment]
One theory I have is that having TH3 and TH4 from two different sources is causing a conflict.  Our biggest decline in drop rates occurred when we started having teams where both TH3 and TH4 were present.

**Comment by Mozzy4Ever** [comment]
@jmcmorris I've already done the applicable tests (See #1686 ) for example. TH4 overwrites TH3 as it should. That specific report was only for the distance check, but I also tested to make sure that TH levels would overwrite each other. I don't know the exact code for how Eden handles TH3/4 cause I know it's not the same as DSP but I imagine they're setup to add the same % bonus. If so, I'm pretty sure it's just a lack of sample sizes and fallover from when RNG was shit.

**Comment by roriffxi** [comment]
Also, apparently the code for TH works differently in Dynamis than outside of dynamis (potentially due to the zonewide loot pool / ability for multiple alliances to exist) and it's possible that if a problem exists its only on the dynamis side.

**Comment by setsuk0** [comment]
Th4 "appearing" weaker than TH3 has been primarily noticeable only in the past two weeks since the last patch. In October/November, dynamis drop rates were more consistent with what we have seen over the past few months. However, for the past two weeks specifically, drop rates for our linkshell and SD (from what I've been told) have been significantly lower. I'm not sure what the other linkshells have noticed but it would be great to see some other input since this is a small sample size to go off of. 

If there is an issue with TH4 and TH3 creating a conflict, I will note that for our dynamis run Tuesday, we did have some TH3 THFs in the alliance aside from our TH4 puller. For our Windurst run last night, we only had TH4 in the alliance. The run was more consistent with what we have seen over the past few months (i.e., normal amount of AF drop, roughly 1k currency as opposed to only 250 currency from Tuesday's run).

**Comment by danismyhero** [comment]
For those testing and logging in game, please specify if your TH3 is from TK only, or AA only.  I doubt there's a difference, but more data is better than no data.

**Comment by Mozzy4Ever** [comment]
> For those testing and logging in game, please specify if your TH3 is from TK only, or AA only. I doubt there's a difference, but more data is better than no data.

DSP only looks at stats on the character itself, not on the individual gear. Tested this awhile ago to verify how +Steal works and to make sure that THF AF gear works.




> Also, apparently the code for TH works differently in Dynamis than outside of dynamis (potentially due to the zonewide loot pool / ability for multiple alliances to exist) and it's possible that if a problem exists its only on the dynamis side.

It shouldn't. TH affect is based on enmity table for the mob. https://github.com/DarkstarProject/darkstar/blob/da0b569bde3b20ebcaed00c464d19a63bdb2e0e8/src/map/entities/mobentity.cpp See line 978



> Th4 "appearing" weaker than TH3 has been primarily noticeable only in the past two weeks since the last patch. 

https://www.edenxi.com/forums/viewtopic.php?f=29&t=13455 was the last patch, in which the Random Number Generator was fixed because DSP's version of it was very streaky. You'd have either shit runs or amazing runs. Now you'll have runs that, with time, will average out to the middle.

**Comment by roriffxi** [comment]
I don't think there is a record of it anymore cause it was only a discord announcement.  But when the first TH4 was obtained, Godmode specifically said that it had been programmed incorrectly in Dynamis and was giving more effect than it should but was fine outside Dynamis.  It was then patched a day or two later.

**Comment by godmode** [comment]
It doesn’t work differently inside Dynamis. But the wording of the announcement might have made it seem that way.

**Comment by perkuprightmeow** [comment]
Just ran Dynamis-Windurst with both TH3 and TH4 tagging things together (2x TH4, 1-2x TH3) and still ended up with ~700 currency and really decent AF drops. Not a full clear (required boss route + some extra pulls).

**Comment by Slamm21** [comment]
This can definitely be closed now @Volkaru
