### ISSUE TITLE
Light Shot doesn't work on any NM

### ISSUE THREAD

**Issue by Tjonke** [EdenServer/community#2303]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
Game Version: 30181205_0

I ran around as COR/BLM for these tests. No NM that I tried, Meww, Delkfutt Key NM was sleepable with Light Shot after the nerf that happened a few weeks ago, all you get is "X uses Light Shot, but misses Y" (tried 6 shots on eaach NM just to make sure my 75 COR all of sudden couldn't hit the side of a barn) and couldn't get a single shot to land. I was able to sleep them with Sleep from my /BLM sub easy enough, just not Light Shot at all. 
![No sleep](https://user-images.githubusercontent.com/9790100/71378053-b2b24000-25c6-11ea-8b15-42ab296f2412.png)

**Comment by godmode** [comment]
For any dev that picks up this ticket before you start debugging; it is patched live to miss NMs. It is not committed in code. The resistance needs to be investigated before it’s allowed to be used.

**Comment by ShiyoKozuki** [comment]
Just for future reference in case it is not known:
If a monster has 50% light SDT(Specific damage taken), it will be immune to all light based sleeps(Lullaby, repose, light shot, sheep song).
If a monster has 50% dark SDT, it will be immune to all dark based sleeps(Sleep, sleep2, sleepga sleepga2, yawn, Soporific)

https://www.bg-wiki.com/bg/Resist#Elemental_SDT

Aside from damage, SDT values also impact magic accuracy.

Anything above 50% will add a 1/2 resist after the fact to enfeebling magic or additional effects of the corresponding element.
No resist will become 1/2, with the other levels now becoming 1/4, 1/8, and 1/16.
For example, Ghosts and Skeletons are at the 50% tier and will take a 50% reduction from Element: Dark dark elemental damage.
Furthermore, they will be guaranteed to resist Sleep for example outside of a magic bursted Compression skillchain or Rayke with at least one Tenebrae rune as that will take the tier below 50%;
As previously mentioned, spells like Sleeps and Absorbs either land fully, have a half resist, or are completely resisted. Since Sleep may not fully land against these Ghosts or Skeletons, there is now only a single state to the spell see the roll analogy and chart above again.

**Comment by 59blargedy** [comment]
resolved in March 1, 2021 update.
