### ISSUE TITLE
Cor AF "Against All Odds" Glitch

### ISSUE THREAD

**Issue by Gantofu** [EdenServer/community#2418]
I tried to run the cor af quest last night with another friend and we ended up with glitch and failed battle:
1st glitch:
My alt started battle by clicking "Cutter", and found everyone else ended up in black screen while my alt was alone in the battle.  we waited for probably 20min and eventually 1 member finally loaded into battle.  Continue to wait and around 5 minutes near the end of timer, the 3rd char finally loaded

2nd glitch:
We decided to fight the mob and tried to finish with just 3 of us.  Ended up running of time and everyone booted from the battle.  However, my character apparently was still in the battle field with black screen and could not move.  During this time, the remaining mob continue to attack and chip my alt's hp down.  So I decided to force disconnect the client and hoping i would be out of battle when I reconnected.

3rd glitch:
after reconnecting, I found my alt was dead and under water somewhere in zone.  none of the rest of party was able to target/find the body for tractor or raise

**Comment by Serephim** [comment]
I just did this last night as well again for my alt and the fight worked normally. But when it finished, my other character was black screened, couldn't warp, had to manually close the window, and when I logged in I was floating in the air above arrapago reef and couldn't move. Had to use warp cudgel. The character who was on the quest did exit normally, but was floating in mid air where the cutter is supposed to be. That's not a huge deal, because I could just walk over the water to land like I was Jesus. lol

**Comment by Gantofu** [comment]
closing this.  We tried again and was able to complete the battle.
Here is what to expect:
1. Upon joining, the quest holder would pop right into the boat with 2 mob (battle area), while the rest of party members will be in black screen, while still be able to chat.  I assume this is not a really "loading data.." kind of black screen.  it feels like the rest of the party was being transported to the battle field (boat).  after 5~10 minutes, that rest of party members would finally pop into the battle field one by one.
2. Upon defeating the 2 mobs, quest holder would go into cutscene and receive the af hat at end of the cs, while again the rest of party members goes into black screen.  At this point, everyone just had to wait patiently for the battle field timer to run out and be ejected back to reef zone.
