### ISSUE TITLE
Dragoon era inaccurate group 1 merits

### ISSUE THREAD

**Issue by deepbreathingeden** [EdenServer/community#2440]
### Checklist

- [y] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [y] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [y] I have provided my client version in the details. (type /ver into your game window)

### Details

My game version is 30181205_0
I have 1 merit point in jump recast time. it only reduces the casting time by 2 seconds. It should be 3 seconds. this is not just a visual bug. i have tested it myself. the cooldown always startes from 58 seconds upon use.
all group 1 dragoon merits are era inaccurate.

for example. each merit point in jump should reduce cast time by 3 seconds. not 2 seconds.
the same applys for all group 1 merits.
they are all inaccurate.

multiple sources can be found online. here is one reliable source: (2008)
https://ffxiclopedia.fandom.com/wiki/Category:Merit_Points?oldid=731761

**Comment by bootseden** [comment]
the merits are that way because jump/high jump and their recast merits are currently using OoE values
jump right now is 1:00 instead of 1:30, fully merited it would be 1:15 in era
high jump right now is 2:00 instead of 3:00, fully merited it would be 2:30 in era

https://ffxiclopedia.fandom.com/wiki/Jump?oldid=377604
https://ffxiclopedia.fandom.com/wiki/Jump_Recast?oldid=730090
https://ffxiclopedia.fandom.com/wiki/High_Jump?oldid=248417
https://ffxiclopedia.fandom.com/wiki/High_Jump_Recast?oldid=730091

**Comment by deepbreathingeden** [comment]
i see.

i didn't know about that original era cast time.
should've done more research on my part.
