### ISSUE TITLE
Fulm-Long Salmon Sub (Out of Era)

### ISSUE THREAD

**Issue by MeyiLekoh** [EdenServer/community#2524]
### Checklist

- [ X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X ] I have provided my client version in the details. (type /ver into your game window)

### Details

Cooking Guild requested me to turn in fulm-long salmon sub, which is an out of era item. (According to wiki, it was added July 17th, 2010.)

![ooe_sub](https://user-images.githubusercontent.com/47701928/76650422-d8911600-651f-11ea-8386-9b7640386804.png)

I am an Artisan Chef (74), My version is 30200217_0.

**Comment by Dribblet** [comment]
The item in question should be the Ilm-Long Sub, HQ of the normal Salmon Sub in-era. 
https://ffxiclopedia.fandom.com/wiki/Salmon_Sub?oldid=365358

The name change occured in this patch "To alleviate confusion", however it's still the same item
http://www.playonline.com/pcd/verup/ff11us/detail/5571/detail.html

Since both variants are the same item just named differently, the Guild should accept HQ Salmon Subs, regardless of the name it's called. Might have to produce a DAT mod to change the name of the sub to the old version.

**Comment by slassen** [comment]
@Dribblet is this just a dat mod issue then?

**Comment by Dribblet** [comment]
> 
> 
> @Dribblet is this just a dat mod issue then?

Correct, a dat mod would be needed to change the name from Fulm-Long to Ilm-Long but functionally they're the same item in-game.

**Comment by KnowOne134** [comment]
has been corrected.
dat can be found here:
https://github.com/EdenServer/Eden-Client_DATs
