### ISSUE TITLE
SMN AF quest Class Reunion cannot be completed

### ISSUE THREAD

**Issue by AstroMeiyana** [EdenServer/community#2537]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Completed reqs for quest: Class Reunion (SMN AF Pants). 
Ending NPC (Koru-Moru) will not give Evoker's Spats to complete the quest. 

My character: Astro

Also worth noting: ran into another SMN (Charcter: Vortie) having the same issue--we were not together. 

Finally, my wyvern was removed upon entering instanced fight with the 6 Dryads in the Cloister of Frost. 

client version 30181205_0

**Comment by E5una** [comment]
Astro, although this does need to be fixed so that the other quest does not block progress, you can complete your quest by doing the quest that the NPC is blocking your progress with. I’m on mobile atm, but I remember having the same problem. Spoiler, I remember it being long and annoying and being frustrated. Try searching the NPC and seeing what quest dialogue is blocking you and completing that. It could be multiple quests, but this is your problem. The dev team will need to change the precedence of the quests with this NPC when they have time.

**Comment by KnowOne134** [comment]
Has been fixed script had a typo
