### ISSUE TITLE
All furniture has out of era storage

### ISSUE THREAD

**Issue by Raphtalia1** [EdenServer/community#2602]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
 
 All furniture currently has out of era values, If one is going to be brought into era, all should be

**Comment by Shoruto** [comment]
Specific furniture (Cartonnier) storage #2539

**Comment by Shoruto** [comment]
This is a copy paste from E5una's Report

Title - Cartonnier gives 20 storage instead of 6 #2539

Details

Disclaimer: I HAVE NOT TESTED THIS MYSELF

I was told secondhand by a woodworker that Cartonnier is giving 20 storage instead of 6. Would be nice if someone would look into this. It gives 20 today in retail, but should give 6 at the time of our server: https://ffxiclopedia.fandom.com/wiki/Cartonnier?oldid=374493

Apologies for opening a ticket I cannot test myself.

version 30181205_0

**Comment by 59blargedy** [comment]
closing as the 2008 storage buff is now within server date
