### ISSUE TITLE
CoP 8-4 Promathia 5s Meteor cast

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#2630]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

In the 8-4 fight vs Promathia, Meteor is supposed to take 10 seconds to cast which would give you enough time to run out of range. Currently it takes 5 seconds.

**Comment by agjevik999** [comment]
Tried this mission just a few mins ago for the 3rd time. The 2nd form is near impossible. Our last run he opened with Meteor and near wiped our party before we could even engage. He followed up with a second meteor not 15 seconds after the first, to complete the wipe.

Supposed to be cast once every minute as per the wiki. So not only is the casting time no functioning, but the frequency at which he is casting it, is also not functioning.

**Comment by benwelker** [comment]
I noticed several other things in relation to this fight, not just the meteor cast time/usage time, that are incorrect.  I can create additional bug reports if needed, please just let me know.  
  
Selh'teus still cannot be cured according to the [Wiki](https://ffxiclopedia.fandom.com/wiki/Dawn), however, he can be cured in it's current state.
  
Haste, Protect and Refresh can not be cast on Prishe, according to the same wiki link above.  I cannot confirm Protect, but Refresh cannot be cast on her (which is correct), however, Haste *can* be cast on her.  Not sure I saw her use benediction either, but may be worth confirming.

**Comment by Spintimalli** [comment]
Few things i'd like to add here as my party struggled for hours on this:
- Prishe can be buffed with Protect, Shell & Haste
- Sel'Teus can be healed, and also buffed with Protect, Shell & Haste
- If Prishe dies and is raised, she does not re-engage Promathia and therefore cannot use Nullifying Dropkick to dispel Promathia's Magic/Physical Shields
- Sel'Teus does not engage Promathia unless Prishe dies

Our group just had 2 healers keep Prishe alive while she did all the damage while everyone else just stayed out of meteor range and did nothing making the fight very anticlimactic...

**Comment by Serephim** [comment]
Still nearly instant casting meteor. This makes winning the fight almost completely luck based depending on how much he uses it. First time he wiped us in seconds with meteor because we weren't expecting instant cast. Didn't use any damage resistance shields. Sel'Teus and Prishe's AI still busted as posted above.
We BARELY scraped a win by without using Prishe as a tank. First phase feels pretty good but the second phase is busted as all hell. lol

**Comment by E5una** [comment]
Echoing Spintimalli's report, if Sel'Teus wasn't curable and you lost when they died, it would force you to fight. Unfortunately you can have 1 person solo this while curing (and some other light participation) while staying back.

I'm not sure if healing the NPCs should generate hate, but it doesn't, and the NPCs don't seem to generate hate for themselves either. Carbuncle can get hate off of them very easily (but maybe that's due to them getting him and losing enmity)

**Comment by 59blargedy** [comment]
resolved in January 10, 2021 update. the issues with being able to buff selhteus are separate and will be posted in a new bug report
