### ISSUE TITLE
Blue Physical Spell Range

### ISSUE THREAD

**Issue by BuffaloOnEden** [EdenServer/community#2649]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

Version 30181205_0
There is a problem with the range on blue mage physical spells on extra large-sized enemies, such as HNMs. For example, on Serket, you have to be practically in the center of him in order to hit him with blue physical spells. This is a problem, since if you are trying to trick attack a vertical cleave, for example, you'll be out of range, while an ordinary weapon skill from a melee class would be in range. So far, I've noticed this on Serket, Fafnir, and Jormy.

What I think is happening is that distance is being calculated from the center of the mob, rather than the edge of the hit box. So, for smaller mobs, there is no problem. However, on HNMs and physically larger mobs, this makes casting blue physical spells with trick attack on the tank nearly impossible.

**Comment by Lilswitche** [comment]
Range is definitely calculated based on the center of the monster and the model will have an impact on when collision is calculated making it so you have to run into the mob to do things.  This isn't just the case with BLU spells but with everything; it's a common occurrence with Behemoth when you try to Steal or Shield Bash for instance.  

This distance calculation to the center of the model impacts spellcasting in a way as well.  I want to say that retail's casting range was variable based on the size of the target. In some instances, casting range could exceed 22 yalms on larger monsters and just over 21 yalms for smaller monsters because of the difference in JA/Spell range calculations.

**Comment by BuffaloOnEden** [comment]
As I understand it, modern games use a collision point on the face of the collider as the reference point for displacement, rather than the center of mass of the object, in situations like this. A quick and easy fix, however hacky it may be, would be to simply add the radius of the collider of the monster engaged to each maximum casting range check. If the source code is properly encapsulated, you should really only need to change one line of code.

**Comment by 59blargedy** [comment]
resolved by another dev in November 21, 2022 update
