### ISSUE TITLE
Drop Rates on Ground Kings/Sky gods

### ISSUE THREAD

**Issue by Slamm21** [EdenServer/community#2695]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
ver 30181205_0
### Details

The drop rates on these are way off, especially abjurations. I am positive the below is correct. **Abjuration drop rates below are definitely 100% correct.**
An example of how this works, Balmung/Hrotti/Ridill all share a slot on fafnir at V.common (64% with TH4) 20% chance of that slot containing Ridill which gives ridill a 12.8% drop rate on fafnir. This matches with the % on wiki back in the day.  

Remember because ridill is rare/ex if everyone has it it won't drop which is why the recent wiki has it listed so low. Aburations avoid this because you don't wear the abjuration and instead turn it into gear.

Fafnir
Wyrm Beard		                                            Uncommon
Dragon Heart / Dragon Blood / Dragon Meat    V.Common (50/25/25)
Dragon Talon / Dragon Scales			     V.Common (75/25)
Aegishjalmr / Andvaranauts			             Common (50/50)
Balmung/Hrotti/Ridill				             V. Common (40/40/20)
Aburation					                     100% (25/25/25/25)
Abjuration 			                                     Uncommon (25/25/25/25)
**Notes**		
With abjurations, wiki adds up to 120.2% for all 4 together.
Some of these kills would have had less than TH4 also.
The 18% for 2nd slot fits very well

Nidhogg
Dragon Heart 			          100%
Wyrm Beard		                  100%
D. Blood /D. Talon/ Nid Scales   Uncommon (25/25/50)
D. Meat  / Nid Scales		   Uncommon (50/50)
D. Scales/ Nid Scales		   Uncommon (50/50)
Abjuration 			           100% (25/25/25/25)
Abjuration 			           Uncommon (25/25/25/25)
Notes		
With abjurations, wiki adds up to 116.7% for all 4 together.
Some of these kills would have had less than TH4 also.
The 18% for 2nd slot fits very well

Aspidelchelone
A. Egg                100% 
A. Ore/ A. Shell  Very Common (50/50)
A. Ore/Heavy     Uncommon    (75/25)
A. Ore/Sipar       Uncommon    (75/25)
Abjuration         100% (25/25/25/25)
Abjuration         Uncommon (25/25/25/25)
Notes		
With abjurations, wiki adds up to 121% for all 4 together.
Some of these kills would have had less than TH4 also.
The 18% for 2nd slot fits very well		
		

King Behemoth
Behemoth Hide	 		           100%
Behemoth Hide / Behemoth Meat	   V.Common (75/25)
Behemoth Horn			           100%	
Behemoth Horn /Shining Cloth	    V.Common (50/50)
Behemoth Tongue			            100%
Pixie Earring/Defending Ring	            100% (95/5)
Abjuration			                    100% (25/25/25/25)	
Abjuration			                    Uncommon (25/25/25/25)
Notes		
With abjurations, wiki adds up to 121.4% for all 4 together.
Some of these kills would have had less than TH4 also.
The 18% for 2nd slot fits very well

**Comment by Slamm21** [comment]
I believe the 4 normal sky gods follow a similar pattern.
Part of the osode set (like byakkos haidate) = common (45% with TH4)
4 abjurations, first slot 100% with an equal 25% split of which abjuration
2nd slot, uncommon (18% with TH4) with the same 25% split

Kirin would be different
Osode = common (45% with TH4)
3 abjurations, first slot 100% with an equal 33% split of which abjuration
2nd slot, rare (8% with TH4) with the same 33% split

**Comment by Mozzy4Ever** [comment]
![image](https://user-images.githubusercontent.com/11255886/79486829-e46b6e80-7fdc-11ea-813b-337beb3080c9.png)

For Aspid, this picture from Feb 25th, 2008 shows 3 ores + shell, which with your current theory wouldn't be possible

![image](https://user-images.githubusercontent.com/11255886/79487136-6196e380-7fdd-11ea-9859-760375b655c7.png)

This one (from the same person) shows 3x Ore + Shell as well

**Comment by Mozzy4Ever** [comment]
![image](https://user-images.githubusercontent.com/11255886/79487446-dcf89500-7fdd-11ea-8f2a-e914a6e5b039.png)

This picture also shows a Fafnir kill with Talon & 2x scales

**Comment by Slamm21** [comment]
the standard items I'm having to guess a bit here as far as what shares a slot. more evidence will help to work that out.
The abjurations are most important for now though of course.

**Comment by Slamm21** [comment]
https://media.discordapp.net/attachments/682393159740817494/700452442680328262/c6ff9d0b60d0faae5be36782dca5a49e.png

An update, it looks like Kirin follows the same formula as all the others, except it's a 4 way split still with 25% of each of the 3 abjurations with the 4th one for nothing.
So I assume the 2nd slot is 18% again
The above is a picture from retail

**Comment by MB213** [comment]
Not to derail away from abjurations, but drop rates on Ridill have been taken note of by the FFXI community for a long time and almost equally as long have been assumed to be around 5 ~ 6%. 
It is also not tied to Balmung or Hrotti - it can drop independently of either and I've seen this first hand, so that is just not how this works, at least in this case. Proof can be found here from this 2005 journal: https://killerme33.livejournal.com/4456.html
There are other screenshots out there of all three weapons dropping simultaneously.

I can go into more detail if you'd like, but there is a ton of evidence for it being an independent drop and also being a 5~6% drop rate during era. I mean a _ton_. By contrast, I have never once seen a claim that it shares a 40/40/20 split drop with Balmung/Hrotti and that it's a 12,8% drop rate. 

With that out of the way, abjurations obviously work differently and I'm not saying any of that applies to them.

**Comment by greyenvy** [comment]
I just wanted to add that looking over our Sky abjuration drops over the past 11 months since our LS started Sky, there cannot be an even split between the abjurations these dudes drop.  The following abjurations drop far LESS than than the others in their loot pools:
N.Abjuration: Feet (Suzaku)
W.Abjuration: Hands (Seiryu)
A.Abjuration: Hands (Genbu)
N.Abjuration: Hands (Byakko)

For whatever reason these abjurations just don't drop as commonly as the others.  Something seems off about Sky gods still and these four abjurations are literally the only reason to keep doing sky for us.  We have had lists as long as these and completed them twice over at this point but haven't even gotten our initial line of these done.  Please audit the four sky gods to ensure even split of each abjuration.  Might as well take a look at Kirin too, although that one seems fine.

**Comment by Slamm21** [comment]
Abjuration drop rates were only changed at the end of april, so any data before that you can't count.
Right now they are even, but you will still see streaks of some things where another ls might see streaks of others.
