### ISSUE TITLE
Crimson Ring

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#270]
I was able to synth a Crimson Ring earlier, but cannot desynth it.

So now I wonder: 
1. Is it an allowed synth on Eden
2. If it's allowed, it would be nice to be able to desynth it

https://ffxiclopedia.fandom.com/wiki/Crimson_Ring

**Comment by godmode** [comment]
Probably won't be allowed because they will put the elemental ore rings out of business which are era items. Leaving the ticket open for now until it's decided. Feel free to bring others to chime in on the subject.

**Comment by Cheezcakee** [comment]
I don't really care either way, but the crimson rings are only +4, and the elemental bead rings are +5. Different Market. It would only really effect the Ruby Ring Market, which is pretty much nonexistent anyway.

**Comment by panfunk** [comment]
Posted a thread on the forums to collect some opinions as suggested.

**Comment by Elysien** [comment]
Decent fire build ring for tanks, and a pretty easy and cheap alternative to skilling GS in the 90's. I personally don't care one way or the other, but there is that.

**Comment by roriffxi** [comment]
In addition to the crimson ring there is the crimson earring.  They can be HQ'd the same way as Ruby Ring / Earring and just beat the stats of those items for the most part.

The crimson ring isnt too big of a deal because outside of a fire resist build, people aren't going to be full timing it and instead they'd just be WS'ing it.

But it would basically replace the ruby equipment since the stone portion is pretty easy to get and ori ingots aren't really that much more difficult to get than platinum.

**Comment by Cheezcakee** [comment]
Yeah you're right Rori, wouldn't matter much because people only gonna WS in it. I don't think the Harmonius earring is worth it to make, because you can't desynth it like you can the ruby earrings(which give platinum back), in addition to it being more difficult to get 2 orichalcum ingots than 8 plat beastcoins and more. Ely brings up a good point about the goldsmithing skill ups though.

**Comment by Serephim** [comment]
I don't see the point in having something out of era when it has a direct equivilant that is in era and will take away from the market of in era items.

**Comment by godmode** [comment]
Since a similar issue will come up again when ISNMs are implemented. Let me float my thoughts to you guys... Some things will really lessen the value of other things. For example, dragon talons were pretty per-capita 75 BLMs in retail before ISNM because they only dropped off some wyrms. ISNM made weskits drop from 1m to 50k in a couple weeks. So I will either remove dragon talon from ISNM or make it very rare. Do you guys see a similar solution for this ruby?

**Comment by roriffxi** [comment]
I looked at the wiki history and apparently this came out during toau, a month or two before wotg.  So I don't have a problem with it due to that.

As to the isnms, it makes it possible / feasible to go for genie weskit more easily and in general I like things to be how they were on retail in era.

Nerfing a drop rate to artificially increase grind time doesn't sound like fun to me. And it could make many isnms worthless.

**Comment by tectal831** [comment]
https://ffxiclopedia.fandom.com/wiki/Crimson_Ring?oldid=336103

there is no reason to believe this desynth is possible, and the ticket has been closed. If you can provide evidence contrary, this will be reopened.

**Comment by panfunk** [comment]
Oh yea just saw there is no desynthesis listed.
I just assumed it is possible since every synthed ring by goldsmithing can be desynthed.
Checking on all recipes made with orichalcum rings, all of them can be desynthed except the 2 rings that have charges on them and crimson ring. on the other hand, crimson rings counterpart: star ring can be desynthed, which was added along with crimson ring. even beaded rings can be desynthed. so I rather assume noone bother to try on retail/write it into wiki

**Comment by raakamies** [comment]
https://ffxiclopedia.fandom.com/wiki/Crimson_Ring , using the oldid for "era" wiki might not show the desynth because it had just not been tried yet then? Was just gonna report this here but yea guess it was alrdy a closed issue. 

SE never, to my best knowledge, added desynthesis for items after they were released they always came in a bundle.
