### ISSUE TITLE
Dynamis booted us and then reset

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#2710]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version: 30181205_0

During Dynamis Bastok we were booted on a full wipe without giving any warnings on time extensions. When we re-entered  it seemed like it started us completely fresh on a new run, with brand new spanws and time extenders etc. 

We eventually left, and are happy to return any currency that we gained after the reset, although we did get booted right in front of a time extender. 

I will update the github ticket with a link to the stream highlight after the stream.

**Comment by E5una** [comment]
https://www.twitch.tv/videos/596008639

**Comment by falzum** [comment]
This has happened to us two runs in a row now. First in Windy, Second time in Bastok. 

In Windurst it wouldn't allow us to reenter, even though we should have had time left. 

In Bastok, we didn't try to reenter because we all had to homepoint when reraise was lost by zoning. 

Seems as soon as the last person alive's hp hits 0, everyone gets booted from zone.

**Comment by rude-jerk** [comment]
Resolved in patch on Feb 22, 2021.
