### ISSUE TITLE
Nidhogg regain

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#272]
He does not appear to have regain at all until below 30%. He starts the fight with TP and has no apparent latent regain until after 30%.

**Comment by Elysien** [comment]
To add to thing, regain clocked at approximately double that of Fafnir's based on testing on the retail server holding them at 30% HP.

(Fafnir 100TP/Tic | Nidhogg 200TP/Tic)

**Comment by godmode** [comment]
So Nidhogg WS'd about every 15 seconds without any additional TP gain sub 25%?

**Comment by Treble011** [comment]
No. He didn't TP at all from the initial pull until sub 25%.

**Comment by Treble011** [comment]
He tp'd 3~4 times (I can only remember 3) sub 25%

**Comment by godmode** [comment]
Sorry, meant that for Ely on retail Nidhogg

**Comment by Oyaziiiiiii** [comment]
Nidhogg tping every 15s **without** tp feed was not retail. That was a kupo thing and it's the main reason it was so much harder there. 

https://www.youtube.com/watch?v=LBp2Uo_RHuU 4 people meleeing(2 dps and 2 tanks I think) with blms MBing and Nidhogg tps every 12-20s at low HP. That seems reasonable considering the amount of tp being fed.

Another thing I want to mention is that the wiki is wrong in saying that Nidhogg doesn't tp during its wings up mode. The video above and the video below clearly shows that it still uses tp while wings are up. During this time however, Nidhogg tends to use TP significantly less. I personally think this is because the melees are either hitting for 0 or missing completely most of the time so there is less TP feed, but there could be something else that also limits its TP usage. From how I remember it, Nidhogg's melee damage and hurricane wing damage increased while its wings were up. 

https://www.youtube.com/watch?v=sld55lttPCw

**Comment by godmode** [comment]
Can you reach out to Ely on this one? In the ticket regarding regain he said it gains 200tp/tick

**Comment by Elysien** [comment]
Interesting video, unfortunately I have no video evidence of my tests of this on the retail server---mind you, these tests were conducted only 2 years ago now. I did go through a lot of SE patch notes to make sure no changes were made to Nidhogg (unlikely they would update such an irrelevant monster by that time) and monster TP-usage, but was unable to find anything. It's not impossible I may have missed something.

**Comment by Oyaziiiiiii** [comment]
Here are my thoughts after killing our first nid since the regain change. It is much harder than retail!  With basically 0 tp feed, Nid was using TP every 14-15 seconds under 25%(as we assumed it would with the regain values that were given.) This is basically the same as Kupo and doesn't line up with those videos. If we're aiming for what retail was, this is too high. Especially since Nidhogg **should** still be tping while wings are up. Without that time off between tp moves I'm not sure we could kill it without sleeping it repeatedly. My personal opinion is that Fafnir and Nidhogg regains were probably equal, and Fafnir seemed a lot closer to normal at 100 per tick.
