### ISSUE TITLE
Monk Counterstance Defense Adjustment is incorrect 

### ISSUE THREAD

**Issue by Hawkeyemash** [EdenServer/community#2771]
### Checklist

- [ X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X] I have provided my client version in the details. (type /ver into your game window)

### Details

FFXI on Eden Game version 30181205_0

Counterstance is taking 50% of base and equipment defense. counterstance should only be %50 of base defense. See attached PowerPoint with snip its of how counterstance works when geared, naked and with defender on. I also added the text from wiki on how counterstance works from 2 Apr 2005 and 19 Aug 2006.

[Counterstance.pptx](https://github.com/EdenServer/community/files/4562017/Counterstance.pptx)

**Comment by Hawkeyemash** [comment]
update Counterstance takes 50% of total defense to include base, equipment and protect. If Defender is used while Counterstance is active than defender will provide 0 additional defense. Counterstance should only cut base defense in half not total defense.

**Comment by Aneyus** [comment]
Era behavior for counterstance should only include defense calculated from VIT/2 and Minne. any other bonuses (food, protect, defender, etc) are ignored. Defense down debuffs still apply.

I was a MNK main for a long time on retail and I recall having around ~45 defense with CS active.

**Comment by E5una** [comment]
In addition to the base defense being the OOE version as mentioned above, Defender/Berserk have no effect while in counterstance. Based on my research this is correct for Defender but incorrect for Berserk, as it should further lower your defense. **In addition, enemy defense down effects are also being ignored, which is incorrect**

Defense 180 with no abilities
![image](https://user-images.githubusercontent.com/13668758/212902295-846f6454-733d-425b-8aeb-3666c4ed7706.png)

Defense 90 with Counterstance
![image](https://user-images.githubusercontent.com/13668758/212902406-e0fa8fd8-6c3a-4330-8912-502bd9e9901d.png)

Defense still 90 with Berserk
![image](https://user-images.githubusercontent.com/13668758/212902589-ac948cbc-db06-4aeb-b438-83b6ad6b2ad9.png)

Now fighting a DC (Defense is 97 istead of 90 due to Signet) - Defense 97 with Counterstance.
![image](https://user-images.githubusercontent.com/13668758/212903566-8b428e19-8f70-436d-830f-c602ff6dbaee.png)

Defense still 97 after Defense Down from Impact Stream from an Aern.
![image](https://user-images.githubusercontent.com/13668758/212903668-22f45e5b-d7d1-4fad-9a55-6b8d80b166c1.png)


https://classicffxi.fandom.com/wiki/Counterstance
While this ability is active, the user's [defense](https://classicffxi.fandom.com/wiki/Defense) rating is calculated only using the character's [VIT](https://classicffxi.fandom.com/wiki/VIT) and any bonuses from [Minne](https://classicffxi.fandom.com/wiki/Minne). Defense bonuses and penalties from any other source (Armor, Job Traits, [Protect](https://classicffxi.fandom.com/wiki/Protect)) will be ignored **(however, "Defense down" effects from enemies will still apply).**
**"Combining with Job abilities that reduce defense, such as [Berserk](https://classicffxi.fandom.com/wiki/Berserk), will lower your defense further."**

https://ffxiclopedia.fandom.com/wiki/Counterstance
(Same message as above)

(Era Bgwiki) https://www.bg-wiki.com/index.php?title=Counterstance&oldid=83929
While the effect is active, the player's Defense is calculated only by their VIT plus any bonuses from [Minne](https://www.bg-wiki.com/ffxi/Minne). All other defense bonuses, with the exception of the [Defense Bonus](https://www.bg-wiki.com/ffxi/Defense_Bonus) trait, are ignored, but defense penalties such as [Berserk](https://www.bg-wiki.com/ffxi/Berserk) or monster-inflicted Defense Down are applied.

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
