### ISSUE TITLE
Breeze Gorget Multi hit weaponskills

### ISSUE THREAD

**Issue by Eleeciam** [EdenServer/community#2775]
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

When worn during a matching Weapon Skill, these gorgets add 25/256 fTP (~+0.1) to the first hit. Many Weapon Skills have their first hit's fTP copied over to all the remaining hits as well; making these gorgets very potent for such Weapon Skills.

They give +10 Accuracy to all hits of the Weapon Skill.

its working for single hit like shark bite , but not for multi hit past the first hit for dancing edge.
Can you please look up the magical code and see if acc is being applyed to each hit.

**Comment by Slamm21** [comment]
Can confirm all the gorgets did this. Snow gorget for example, which is often used with Guillotine:
Latent effect

> Active when using any Weapon Skill with a Skillchain attribute of Induration (and, by extension, Distortion)
> Increases fTP multiplier by +0.1 and adds some amount of accuracy to all hits of the Weapon Skill.

**Comment by Eleeciam** [comment]
I guess I was asking I know they should be active during ws. Is the acc and attack applied to all hits like it should be on eden or is it only applied to first hit ?

**Comment by roriffxi** [comment]
Digging into base DSP it looks like the accuracy carries through all hits of the weaponskill but the ftp is only being used on the 1st hit for most weapon skills.  This is because bonusFtp is calculated earlier on, added to the total ftp for the weaponskill and then 1st hit dmg is calculated.  I'm assuming the function to determine if the gorget matches the element(s) of the weaponskill is working correctly.  We already know some WS' have the incorrect elements added (see: raging rush > raging rush making Induration when it should be Fragmentation)

https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/weaponskills.lua#L170

After 1st hit dmg is calculated, it looks to see if the weaponskill in question has the ability to carry ftp over.  Rampage, raging rush, Jin, penta thrust, and dancing edge (probably all WS, but these were the ones i looked at) do not have multiHitfTP  in their wsParams list, so all of these weaponskills currently set FTP down to 0 after the first hit.  No checks are done again to add in the .1 FTP back to the damage.

the bonusAcc from the gorget is added into the hitRate and that appears to remain unchanged throughout the calculations so that at least is applying.

**Comment by Falaras** [comment]
So I was looking into it a bit, I don't think WSes replicated fTP in era. It looks like fTP replication started with some Empyrean and Merit WSes (Abyssea time frame)  and was added to a bunch of old 1 hander WSes in the 2014 December update. No mention of Rampage or Dancing Edge replicating fTP before December 2014 which was a patch that sought to buff 1 handed WSes in order to make them more competitive. I'm not 100% sure on this, since fTP replicating wasn't even found out until a while after it was introduced. 

This would also fall in line with the old mantra of Gorgets not being too noticeable for multi hit WSes back in era.

**Comment by Falaras** [comment]
Oh I actually just straight up found the patch note: 

Bonuses for the following weapon skills that only applied for initial hits will now be applied to all hits.

    Dancing Edge / Evisceration / Pyrrhic Kleos / Vorpal Blade / Swift Blade / Rampage / Decimation / Blade: Jin / Blade: Ku / Hexastrike / Exenterator / Chant du Cygne

 - December 2014

**Comment by Eleeciam** [comment]
Right on appreciate it

**Comment by Eleeciam** [comment]
So does the plus 10 acc go to every hit
Or do they consider the acc a bonus with the damage ? As I read it sounds like the bonus dmg is first hit but the acc should be all. Or am I reading it wrong?

**Comment by Falaras** [comment]
From what I can tell ffxiclopedia started listing "Adds some amount of accuracy to all hits of the WS" in 2008, so it's very likely that accuracy is applied to all hits in era while fTP isn't.

**Comment by Slamm21** [comment]
Accuracy was definitely applied to all hits on retail.
I remember comparing justice torque to gorget on guillotine and having more hits land on average back in the day.

**Comment by Eleeciam** [comment]
Very nice so u tp in torque and ws in gorget.

**Comment by Slamm21** [comment]
correct

**Comment by ThoseWhoFight** [comment]
Yes, in era FTP multiplier was only to the first hit on multi hit WS, but the accuracy bonus was applied to all hits.

**Comment by 59blargedy** [comment]
this functions on eden as discussed above
