### ISSUE TITLE
Brittle Rocks in Excavation Duty are immune to Requeim and occasionally will resist Elemental DoTs (Burn, Choke, etc)

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#2830]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

In-game:
![resist](https://user-images.githubusercontent.com/49970272/81524851-c7e2fd80-9320-11ea-935f-bfa0e2aa2a49.png)
![requiem](https://user-images.githubusercontent.com/49970272/81526664-3aa2a780-9326-11ea-96a6-cccb2e0f9620.png)

Wiki:
![requiem](https://user-images.githubusercontent.com/49970272/81524856-ca455780-9320-11ea-9d4f-d3c5885796d5.png)
![eledot](https://user-images.githubusercontent.com/49970272/81524861-cca7b180-9320-11ea-9fb6-85b9f47f6dba.png)

It is possible that the wiki is incorrect here, would require someone to confirm this is true on retail.

**Comment by FariskaEden** [comment]
![image](https://i.gyazo.com/278dc5a0b91bac59db7b6f1c55ca3a9d.png)
Tested requiem on the brittle rock on retail. It worked.

**Comment by KnowOne134** [comment]
Can remove requiem. The other do hit. You just got a resist

**Comment by VirtuosusFFXI** [comment]
Just to clarify, I wasn't saying that Elemental DoTs such as Burn can't land. I landed them on every rock at some point. According to the wiki, they should not be able to resist at all. If someone with retail access can verify this that would be nice. 

![resist](https://user-images.githubusercontent.com/49970272/81604531-010d8300-939e-11ea-82e3-9328144e40e2.png)

**Comment by FariskaEden** [comment]
![image](https://user-images.githubusercontent.com/46270382/81608588-88f68b80-93a4-11ea-9c70-32f6de7849dd.png)
![image](https://user-images.githubusercontent.com/46270382/81608620-9875d480-93a4-11ea-88f1-8af1e702f909.png)
![image](https://user-images.githubusercontent.com/46270382/81608900-fc989880-93a4-11ea-9059-dab6b356426f.png)
![image](https://user-images.githubusercontent.com/46270382/81608924-05896a00-93a5-11ea-9ae0-c1a2c52e0608.png)

I forgot I had BLM leveled to 73, so I went into the uncapped version and was able to land every elemental DoT I used with underleveled skill while naked. So probably safe to assume that they should always land.

**Comment by KnowOne134** [comment]
requiem immune fixed, dot resistance will be fixed next patch

**Comment by VirtuosusFFXI** [comment]
Resists on ele dots are very infrequent, but still do exist:

![resist](https://user-images.githubusercontent.com/49970272/82633453-203fb800-9bc9-11ea-937e-92e0cda16e12.png)

Guessing that it is currently set at 95% hit rate and can't be forced to 100% or something.

**Comment by E5una** [comment]
Hmm I was going to open a new bug report for this since this is our SMN/BLM in 60 cap with 101 INT:
![image](https://user-images.githubusercontent.com/13668758/176906590-7ee84344-7e47-4e32-9270-0e5f6b8712b9.png)

But after further investigation, I'm guessing through clues on the testimonials that maybe its not as easy to land it as the we thought:

https://ffxiclopedia.fandom.com/wiki/Excavation_Duty/Strategy

"Recommended Setup: 4 person party: 2 Damage-dealers; 1 BLM, RDM/BLM, DRK/BLM, or SCH/BLM; 1 RDM/BLM (or Good WHM/BLM*). "

"(* A good WHM/BLM can also replace the RDM/BLM in this run though the WHM will have a harder time keeping up. Yagudo Drinks are recommended for any WHM doing this mission and Dia II can be used to replace Bio II in my experience. Sticking the elemental enfeebles may prove to be difficult as well.)"

They might just be speaking from the hip and not actually have tested it, but SMN/BLM certainly gets resisted a fair amount. I'd say either there's no issue, or we might need retesting on retail as a non-enfeeble skilled job /BLM or maybe for Fariska to clarify what his elemental skill was at when he said it was underskilled
