### ISSUE TITLE
No ??? item obtained from Leujaoam Cleansing Ancient Lockbox

### ISSUE THREAD

**Issue by hyakuzaku** [EdenServer/community#2838]
### Checklist

- [✓] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [✓] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [✓] I have provided my client version in the details. (type /ver into your game window)

### Details

Client version 30181205_0

The Assault Mission "Leujaoam Cleansing" did not give a ??? item when I opened the Ancient Lockbox. According to the data on the wiki entry for the assault, there should be a 70% chance of a ??? ring and a 30% chance of a ??? box.

Repeatable steps:
• Enter the Leujaoam Cleansing Assault Mission
• Complete the mission by killing all of the worms
• Open the Ancient Lockbox

**Comment by Balrahn** [comment]
This happened to my group today aswell.

**Comment by KnowOne134** [comment]
I'm under the impression that there is a low rate at getting nothing from another source

**Comment by FariskaEden** [comment]
From my understanding ??? items should only be given at or above the recommended level that the assault lists. I completed an assault on retail below the recommended level and never received a ??? item. Since I normally do them uncapped (which is always above the recommended level) I always receive a ??? item. So this was the first case of not getting one since it was below the recommended level.

![image](https://user-images.githubusercontent.com/46270382/82124866-ebb6a100-976f-11ea-97a9-96e521bd0f0d.png)

https://ffxiclopedia.fandom.com/wiki/Category:Assault
- An unidentified item is received only if the Assault was completed at or above the "recommended level."

**Comment by KnowOne134** [comment]
That part is coded in. You must be above recommended level to get a change
at a ??? Item. It's a low chance to not receive one but I am unsure if its
impossible not to. Anyone else can clarify or give thoughts on mater and
link material?

**Comment by KnowOne134** [comment]
Updated 3/8/2021
