### ISSUE TITLE
Holy Cow ENM - No Treasure Chest

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#2850]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Making a Github since we're getting several tickets about this. People completing Holy Cow aren't getting a clear/chest is not popping. Will link this so they can provide details.

**Comment by bkesecker** [comment]
Moving out of chest model range and back in seems to resolve.

**Comment by slassen** [comment]
This is either due to a missing update packet or the client dropping it. Either way this is not rare but also not common. This also happened on retail quite a bit. As mentioned, the solution on retail was move out and back in. Due to the shared experience on retail it's probably likely that this is a client issue and we won't be able to fix without reversing and modifying the client. Closing.
