### ISSUE TITLE
Jailer of Hope immune to physical stuns

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#2851]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Jailer of Hope should be immune to magic stuns, but not physical (shield bash, blade bash, weapon bash, etc.) He currently takes damage from bashes, but no stun happens.

"Is 100% resistant to magical Stun, but susceptible to job ability stuns such as Weapon Bash."

**Comment by slassen** [comment]
Thanks, I meant to make this bug report before I released them. This will require adding new functionality which will fix a few other issues as well. For the developer picking this up you can look to what I did when splitting up light and dark sleep immunities in order to make it backward compatible.

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch
