### ISSUE TITLE
Store TP not being calculated properly with dual wield and/or multi-hit weapons.

### ISSUE THREAD

**Issue by Kurtalicious** [EdenServer/community#2867]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

/version 30181205_0

### Details

Attila's Earring is not giving Store TP +1.  I just tested it twice with and without earring equipped.  I got 47 tp per hit both times.

**Comment by Falaras** [comment]
Tested with Byakko's Axe:
With Attilas - 170 TP return
Without Attilas -169 TP return.

Retested to see if it's giving the same amount of TP as another +1 STP item:
Sam with no STP+1 on - 161 TP return.
Sam with Attilas (STP+1) on - 162 TP return.
Sam with Cancer Subligar (STP+1) on - 162 TP return.

It works.

**Comment by Kurtalicious** [comment]
I think the problem is I'm dual wielding using a multi-hit weapon and it's not being calculated properly.

**Comment by Kurtalicious** [comment]
I really don't know enough or understand how this stuff works.  I just know that I'm supposed to get more tp and I'm not.

**Comment by Kurtalicious** [comment]
No stp I get 47 tp per hit.
+1 stp I get 47 tp per hit.
+6 stp I get 49 tp per hit.
+7 stp I get 50 tp per hit.

Something isn't adding up to me

**Comment by Falaras** [comment]
Store TP isn't just straight +TP it's a percentage calculation. Your TP per hit is so low you aren't actually gaining an extra TP per hit from the looks of it. Based on the calculation the wiki gives of:
(Base TP/hit) * (1 + (Total Store TP / 100))
the TP return you are getting makes sense assuming there's no rounding involved.

**Comment by Kurtalicious** [comment]
I changed the title of the bug report.

**Comment by Kurtalicious** [comment]
Seems like it's rounding down.

**Comment by VirtuosusFFXI** [comment]
There are rounding errors with Store TP even with 2 handed weapons on Eden.

**Comment by Kurtalicious** [comment]
It's rounding down even when you have 47.94 and 49.82 tp per hit to 47 and 49 tp per hit, respectively.  I'd think you should be getting 48 and 50 tp.

**Comment by Falaras** [comment]
I'm not sure STP should be rounding up. This is a weird thing with having the 3000 TP system on Eden when it was a 300 TP system in era.
In era if you were getting 5.75 TP per hit, the 5 would just be straight cut off and you would be getting 5.7 rounded down so 5.7/100 TP.
On Eden if you are getting 57.5 TP per hit, the 5 is being cut off which is effectively "rounding down" for 57/1000 TP.

So from what I can tell Eden's STP system is indeed working correctly for era accuracy.

**Comment by greyenvy** [comment]
http://fadedtwilight.org/storetp-calc.html

**Comment by Relic3** [comment]
In my experience, it is incorrectly being rounded down at some point in the stp calculation. All the STP calcs are either exactly correct for me, or I'm getting 1 less tp than I am supposed to at random amounts of delay/stp.

**Comment by Imdesyda** [comment]
Falaras is correct. I looked into this a lot for Amano. According to the STP calc Grey posted you should only need 50 STP to get a 6 hit, however on Eden you only end up with 996 TP. 

There are a few reasons for this but according to the bgwiki from Nov 2007 (https://www.bg-wiki.com/index.php?title=Store_TP&oldid=48583):
It is important to note, however, that at each stage of calculation, fractions beyond the tenth decimal place are truncated.

Using Amano with 50 STP as an example:
bTP=5+((437-180)*6.5)/270)=11.187037037
Truncated to 11.1
aTP=11.1*(1+.50)=16.65
Truncated to 16.6
16.6*6=99.6

Now because we use the 3000tp system we have to adjust that a bit but we end up with 996 to which is what is currently being seen on Eden. 

Now there have been changes of the years and most calculators do not account for those changes. I did however come across this one: http://www.evil-kitty.com/tpcalc/
Using Amano again the Old TP section correctly shows that you would still be at a 7 hit with 50 STP. It does however show 16.5 TP per hit as opposed to 16.6. If I have some time later I'll try other weapons and see how closely they all align, but it seem like it is correct. If anyone happens to know when the Old vs New TP calculations were accurate that would also help.

**Comment by icariumkupo** [comment]
One example, with a 513 delay weapon (common for Scythe), you need +21 Store TP.

Neither calculator linked in this thread confirms this, but we all know it and it works on eden.

**Comment by Relic3** [comment]
Did something get changed to store tp calculations in recent years to make every stp calculator off by 1tp/hit at random values?

**Comment by Imdesyda** [comment]
Doing the math based on the 2007 formula 513 delay and 21 STP would give you 1008, which is what you are getting I would assume. I only just noticed this was changed to DW and Multi-hit, so I'll look at this when I'm near my computer.

**Comment by Relic3** [comment]
I get 1006 for using 21 stp. I get 994 when using 20.

**Comment by icariumkupo** [comment]
Is that ws a 1 hit? ( Cata). I thought I had to ws in 21 as well to main 6 hit. Nice to know I can remove attila ear for cata.

**Comment by Relic3** [comment]
Yea this is for Cata. I drop Atilla's for a Merman's, and rajas for x2 Flame for Cata. All I find is conflicting info everywhere for how much tp we should be getting.

**Comment by Slamm21** [comment]
best to calculate it manually


Delay Range: | Equation
-- | --
0 - 180: | 5.0 + [(Delay - 180) * 1.5] / 180
180 - 450: | 5.0 + [(Delay - 180) * 6.5] / 270
450 - 480: | 11.5 + [(Delay - 450) * 1.5] / 30
480 - 530: | 13.0 + [(Delay - 480) * 1.5] / 50
530 - 999: | 14.5 + [(Delay - 530) * 3.5] / 470

**Comment by Imdesyda** [comment]
That was the formula I used to calculate the 1008 for Scythe. If he's getting 1006 then something isn't right.

**Comment by Relic3** [comment]
Using that above formula for a 513 Delay weapon : 

13.0 + [(513-480) * 1.5] / 50

This comes out to 13.99 Base TP/Hit. Using +20 STP (Rajas + /Sam)
13.99 x 1.2 = 16.788 TP/Hit. In 6 Hits I should be getting 100.728 tp. Currently we are getting 99.6.
(With attila's at +21 stp) :
13.99 x 1.21 = 16.9279 TP/HIT. In 6 Hits I should be getting 101.5674 tp. 


I think ffxi is supposed to drop everything after the first decimal :
13.9 x 1.2 = 16.68 TP/Hit. In 6 Hits I should be getting 100.08 tp.
(With +21 STP attila's)
13.9 x 1.21 = 16.819 TP/Hit. In 6 Hits I should be getting 100.9 tp. 

Please move decimal place over 1 to reflect the TP in 1000's instead of 100's in old retail values. 

Something feels wrong on Eden.

**Comment by Imdesyda** [comment]
The 16.68 should be truncated to 16.6 or 166 and 16.891 to 16.8 or 168. Which would give you 996 TP at STP 20 or 1008 at STP 21. So if you are getting 1006 there is likely a rounding error somewhere.

**Comment by Relic3** [comment]
You are correct. I see now that it is supposed to take away every extra decimal at every part of the calculation. I suppose nobody made an accurate enough stp calc at all delays/stp values yet then for them all to be off in this way.

**Comment by Slamm21** [comment]
with relics example, 13.99 becomes 13.9
13.9 is 139tp with our client, so 139*6=834
now add the 20 STP = 1,000 TP

**Comment by Imdesyda** [comment]
That is not how STP works

**Comment by Slamm21** [comment]
yeah forgot the decimal trying to simplify it.
right so
13.99 is multipled by1.2 for your 20 store TP =16.788 which is 167tp per hit
you should have 1,002tp after the 6th hit

**Comment by Slamm21** [comment]
you only remove decimals AFTER the store TP has been included in the calculation

**Comment by Imdesyda** [comment]
Read the STP page again:

It is important to note, however, that at EACH STAGE of calculation, fractions beyond the tenth decimal place are truncated.

**Comment by Slamm21** [comment]
forgive me if I'm blind here, but all I see is this where it says "after accounting for Store TP"

> When calculating TP after accounting for Store TP, FFXI drops all decimal places after the first. For example, 11.49% adjusted TP per hit will count as exactly 11.4% TP per hit.

>

**Comment by Relic3** [comment]
Actually now that I look at it, it only drops the decimal places AFTER the Store tp bonuses are applied. 

"When calculating TP **after accounting for Store TP**, FFXI drops all decimal places after the first. For example, 11.49% adjusted TP per hit will count as exactly 11.4% TP per hit."

**Comment by Slamm21** [comment]
yeah this is what I'm trying to say..

**Comment by Relic3** [comment]
This could be the error that Eden has vs Live/Era.

**Comment by Imdesyda** [comment]
From the Nov 2007 article:

For example, Hagun has a 450 base delay, so it's base TP per hit is

5.0 + [(450 - 180) * 6.5] / 270 = 11.5 TP
At level 75, Samurai have an innate Store TP of +25 (Store TP IV). The total TP generated per hit is

11.5 * (1 + .25) = 14.375
It is important to note, however, that at each stage of calculation, fractions beyond the tenth decimal place are truncated. So, in the above calculation, the actual TP gained would be:

TRUNC(14.375,1) = 14.3

**Comment by Slamm21** [comment]
yeah you are reading this wrong.
they are calculating it after STP because the 14.375 is after STP is applied
Hagun is 11.5 with no STP

**Comment by Imdesyda** [comment]
Or it is written wrong. If thats the case there is only one stage at which it would truncated. Why statec each stage

**Comment by Slamm21** [comment]
https://ffxiclopedia.fandom.com/wiki/Store_TP

**Comment by Relic3** [comment]
Going back to the August 2007 page on Store TP as well.

"When calculating TP after accounting for Store TP, FFXI drops all decimal places after the first. For example, 11.49% **adjusted TP per hit** will count as exactly 11.4% TP per hit."

**Comment by Imdesyda** [comment]
So after looking at the code for this I believe I figured out what's going on. baseTP is being stored as an int. This is having the effect of emulating the way it appears to be worded on bgwiki. I currently have a working model on my test server that is producing the results indicated by the info from ffxiclopedia. It was done by changing baseTP to a float and then casting it back to an int during the final calculation.

With Amano and 50 STP it produces 167 TP per hit. With a 513 delay Scythe and 20 STP it produces 167 TP per hit. With Demon Slayer/Ifrit's Blade both 236 delay and 6 STP it produces 58 TP per hit.

The last one was done since I mostly play BLU and I could test the same setup on Eden and it gave me a chance to look at DW a bit. Eden is actually producing 57 TP under those same circumstances. All of the tests I did seem to line up with the calculators. I tested various amounts of DW, STP, and Delay. In addition I did some testing on RA. RA TP numbers remained consistent with what we are currently seeing on Eden though it seems there may also be an issue with RA TP.

I didn't have a chance to look into the ranged TP issue or TP gained from incoming attacks. I need to head to bed before I get myself too much further down the rabbit hole and regret it in the morning. Just wanted to drop this here so I don't forget everything before I wake up.

**Comment by Imdesyda** [comment]
https://www.bluegartr.com/threads/48572-StoreTP-Test-Regarding-quot-Pre-Truncation-quot-and-TP-hit

More data on the subject. Need to review the findings but their conclusion states that the baseTP is truncated prior to applying STP.

**Comment by Slamm21** [comment]
That's very interesting, could do with some retail testing to make 100% sure.

**Comment by Relic3** [comment]
Very weird to do that test with dual wield

**Comment by Slamm21** [comment]
yeah I think we should test on retail with a single weapon.

**Comment by Imdesyda** [comment]
The numbers will not be accurate as the TP system changed quite a bit. You might be able to determine if it's rounding before or after but it may not be relevant.

**Comment by Slamm21** [comment]
yeah my idea was to test the rounding with the new formulas, however
https://www.bg-wiki.com/bg/Tactical_Points

> The TP value is floored after these calculations, and then floored again after additional modification like Store TP.

That with the testing you sent I think is as good as proof we will get to it flooring anything after the first decimal every step of the calculation, it was just badly worded in the Hagun calculation on the store tp page as it only showed rounding down for the 2nd step.

This means the 99.6 Relic is getting is correct and I assume Edens STP system is working correctly.

**Comment by Volkaru** [comment]
After reading through this, it seems that it's been deemed that this is accurate behavior. Closing unless someone can bring evidence suggestion otherwise.
