### ISSUE TITLE
Jailer of Temperance

### ISSUE THREAD

**Issue by ElectronicMan83** [EdenServer/community#2869]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
All resistance seemed to work as intended, but he **kept spamming meiko meishui >> reactor cool 3x**. It didnt use all the arsenal of a normal Zdei.

**Comment by icariumkupo** [comment]
^ Only in blunt mode. Never used optical induration. In other modes, it used other TP moves like overload reactor.

Also,

1. All dots seem to tick for 0, except for requiem.

From wiki:
"DoT is very effective. Keep Bio III, Poison II or Disseverment poison and Shock/Choke/Burn or Rasp/Drown/Frost on at all times."

2. Seems to move at player speed

From wiki:
"150% movement speed."

**Comment by roriffxi** [comment]
Temperance is popping in the taru-taru tower much more often than any other tower.  It should be fairly random with a PH that changes from time to time, making it so that players have to spread out and cover multiple towers at once to have the best chance at popping

https://www.bluegartr.com/threads/40462-Temperance-spawning-conditions
"It's been said in a bunch of other related topics, but to summarize... Similar to the others, it's a 'trigger' that moves between towers.

Trigger is believed to be at a tower for about 15 minutes. (that part is still unknown for certain)

Kill all tower PHs at once and you're almost guaranteed to have it spawn.

15 minute repop on the NM."

**Comment by Garphilius** [comment]
We have yet to notice Temperance poping in Taru tower more often. We send a group to Elvaan and Taru towers and take the 2/5 chance of poping rather than sending people to other towers since Elvaan and Taru are easy to get to. 

Last night we had a pop in Elvaan and one pop in Taru. It took us almost 2 hours to get the one at Taru to pop. 

So far I do not see anything wrong with spawn conditions on Temperance.

**Comment by Garphilius** [comment]
Also, for us, DoTs were doing amazing. Just from DoTs, he went from 100 to around 80％ while our other group ran to tower he poped at. 

As for his speed, yeah, it definitely is not at 150％ like it says it is supposed to be on wiki.

**Comment by 59blargedy** [comment]
final issue with this ticket was movement speed, resolved 9/6 patch
