### ISSUE TITLE
Northlands Dynamis AF2 Drop Rates

### ISSUE THREAD

**Issue by MysticLogos** [EdenServer/community#2927]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

version 30181205_0

After several Beaucedine and Xarcabard runs, it seems like northlands AF2 drops are low compared to era, a bit overnerfed since the last audit/change (~0-4 drops per run).  I'm writing on behalf of my LS - we are currently in Beaucedine again, 0 AF2 after 2 hours.  I'd like to request another audit on these drop rates.

In addition, AF2 drop rates in cities currently seem a bit too high (~8-15 per run) based on our last few runs.

**Comment by Garphilius** [comment]
I am glad someone created a bug report about this. I was going to create a bug report after doing our 4th Dynamis Beaucedine run to have a better pool of data but it seems other LSes are having the same issue.

We have done three Dynamis Beaucedine runs and we have never seen more than 2 AF drop on each run. One of the runs there were 0 AF drops. This is with clearing most of the zone (except the Hydra area). So if this is the case for other LSes as well, I think a call to audit the AF drop rate in Dynamis Beaucedine deserves some merit. 

We have yet to enter Dynamis Xarc. so cannot comment on the AF drop rate there. But if that also seems a bit too low, would be a good idea to audit that too.

**Comment by rka666** [comment]
I can echo too. Good few runs with our LS and max two AF pieces.

**Comment by Slamm21** [comment]
These are definitely correct. In era they were 2.5% with TH4 per kill and were buffed massively in a 2008 update. Eden uses the original version

When drop rates are this low, you need some luck on your side. Like our last xarcabard we got 13 and our last glacier we got 3.  There are tons of mob in each zone.
If you don't have TH4 yet that does make it harder, 2.25% with TH3 and 2% with TH2

![image](https://user-images.githubusercontent.com/5552081/83852019-11015400-a70b-11ea-92cd-a43e7b0bdbd3.png)
If you were perfect at tagging everything and cleared everything but hydra in the glacier your average would be 6.53 where as if you really cleared everything in xarc it would be 10.75

We saw the drop rates were correct on the stream jmcmorris did a while back.

**Comment by Kurtalicious** [comment]
Could you please share the evidence that the drop rates were as you claim?

**Comment by Kurtalicious** [comment]
Could you also please share the evidence of 261 mobs?  And that 261 mobs includes NMs?

**Comment by Slamm21** [comment]
the 261 mobs does not include NMs, you can check this on ffxidb, filter out hydra, NMs and any pets including avatars.l.

Honestly the biggest proof here is common sense. We know for sure it was increased in 2008 due to update notes and also remembering it happen on retail. No one ever got a 47 average in glacier so we need to look at the rare category for 2008 being 20.88. This also means by default very rare must be the case for pre the 2008 patch and if you look at early dynamis posts you will see plenty of runs with under 5 AF.

**Comment by Kurtalicious** [comment]
What is the drop rate of relic from NMs in Glacier?  Also, do you concur that there are 60 NMs?

**Comment by Slamm21** [comment]
in the glacier I never looked at the NMs in detail, only in xarc. Some people think the glacier NMs had increased drop rate but there is no evidence for or against this to my knowledge.

**Comment by Kurtalicious** [comment]
![649F3B01-308E-495A-AA88-07267C7E90AC](https://user-images.githubusercontent.com/46094411/83910041-7ff0a400-a72f-11ea-9c71-806b1ca9ecf3.png)

Can I upload pictures here?

**Comment by icariumkupo** [comment]
Just a thought - maybe just maybe Dynamis uses a different drop rate table than the rest of the game? Maybe dynamis assumed this table the 2008 update but not prior? Assumptions are being made, and maybe not for the better. I get you want to use the data Slamm, but in practice this is simply just not working. Obv drop rates in cities are too high, and obv drop rates in beau/xarc are too low.

**Comment by Falaras** [comment]
Sounds like some bad luck. Since the changes there's been 8 recorded Xarcabards that average 7.75 relic a run even being weighed down by DL runs. Way less people doing BCD but recorded including your run there's been 4 with the average of 4 relic a run including that 2 relic run. I'd recommend if you aren't filling data on the spreadsheets to do so, because with the current spreadsheets numbers the drop rates really don't seem that bad.

**Comment by Slamm21** [comment]
drop rates in cities are not too high and drop rates in glacier are not too low. Watch the stream if it's still around.

**Comment by Kurtalicious** [comment]
![image](https://user-images.githubusercontent.com/46094411/83924706-db7c5b00-a74a-11ea-9a3e-849e1a173713.png)

**Comment by Kurtalicious** [comment]
![image](https://user-images.githubusercontent.com/46094411/83924763-f51da280-a74a-11ea-86a6-47396bdab757.png)

**Comment by Raphtalia1** [comment]
there is no data that suggests that NM's outside of xarcabard have higher drop rates, if we can get some proof, either recorded kills/drops or some video that seemingly shows NM droppings more relic than normal mobs that would be very helpful

**Comment by Kurtalicious** [comment]
https://www.bluegartr.com/threads/42997-108-Dynamis-worth-of-Drops

http://ultimals.com/threads/trophy-post.2310/

**Comment by ccl085** [comment]
Since we're having drop in dynamis from  september 2008 ( blu cor pup relic) shouldn't we also have the 2008 drop rate ? Otherwise we're having it worse than era  in glacier/xar drop wise.

**Comment by Kurtalicious** [comment]
> Since we're having drop in dynamis from september 2008 ( blu cor pup relic) shouldn't we also have the 2008 drop rate ? Otherwise we're having it worse than era in glacier/xar drop wise.

I agree.  They have added the pup/cor/blu relic in Sept 2008.  Some of the reason SE increased drop rates was because the added relic would further dilute the already scarce drop pool.  It's only fair that in regards to dynamis changes in this patch that we either adopt all the changes or none of the changes.  We have clearly decided to choose what we want in this patch in regards to dynamis such as:

_- Timeless Hourglass: 1,000,000 gil -> 500,000 gil and 

- The drop rate of relic armor in Dynamis has been adjusted. Rates for the following areas in particular have been increased:

Dynamis – Beaucedine / Dynamis – Xarcabard / Dynamis – Valkurm / Dynamis – Buburimu / Dynamis – Qufim / Dynamis - Tavnazia_

![image](https://user-images.githubusercontent.com/46094411/85635458-89d93900-b643-11ea-95a8-f4076ed86e73.png)

**Comment by 59blargedy** [comment]
resolved by another dev in april 18, 2022 update
