### ISSUE TITLE
Sanction duration doesn't increase after assault rank up

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#2943]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Ranked up to Private First Class and Santion duration is still 3 hours and 20 minutes.
According to wiki: https://ffxiclopedia.fandom.com/wiki/Sanction Duration should be 4 hours.

VER: 30181205_0

**Comment by KnowOne134** [comment]
There are many different sources with different times. Rank up would give you 20 extra mins

**Comment by falzum** [comment]
Well, before and after rank up with was providing a 3hr and 20min sanction effect. So either the PSC value is wrong, then, or the PFC value is.

**Comment by KnowOne134** [comment]
Well the old was was bloated and should have been getting 3 hours for psc and now 3 hours 20 mins for pfc.
So anyone without 2nd rank will be at 3 hours now and 2nd rank is 3 hours 20 mins

**Comment by falzum** [comment]
Okay cool. So not a bug after all then. Sorry man.

**Comment by KnowOne134** [comment]
Was more that it was a bug before getting an increase. The amount is still really unknown. With and without astral. If someone wants to gather real data and present we can always edit it up

**Comment by iklarazu** [comment]
This is still actually a bug.

PSC was 3hrs 20 on Eden last week, and continues to be as PFC. The base 2nd class in retail was 3 hrs, with each rank up giving an additional hour, as with Signet.

PFC should be 4 hrs, as is documented here :https://ffxiclopedia.fandom.com/wiki/Sanction?oldid=100279

An increase of 20mins per rank has **never** been a thing.

**Comment by FariskaEden** [comment]
http://wiki.ffo.jp/html/706.html this seems to be the only wiki I've found with durations matching to what I've experienced on retail.
![image](https://user-images.githubusercontent.com/46270382/96023398-60c1fb80-0e20-11eb-9e8a-46d832674dd0.png)
Magic flute is Astral Candescence, but the durations mentioned here are accurate.

**Comment by DeuceFFXI** [comment]
I feel the need to add to this discussion and include that I searched through all of the version updates since ToAU was released in April, 2006.  Beginning with the May 10th, 2011 version update all future version update information was posted on the official forums. 

https://forum.square-enix.com/ffxi/forums/84-Version-Updates

This makes searching for certain information after said date quite easy.  Searching for "sanction" brings up nothing.  That only leaves a little over five years of updates to look through and fortunately SE only did version updates about 3 or 4 times a year.  You can also ctrl+f and search for sanction on those posts individually.

In doing so, I did not find a single version update which mentions changes to Sanction while there have been a few changes to Signet and its effects made.  With that said, I would say it is safe to assume that current retail has "era" accurate sanction and could be directly pulled from for reference rather than relying on incomplete wiki information.

Ultimately, I was hoping SE had posted tables regarding Sanction Durations themselves in an official manner; sadly, this was not the case.  I may try another search using "astral" to see if that brings up anything as well, but I'm not expecting it to as I had searched using that word on several of the patch notes pages.

**Comment by DeuceFFXI** [comment]
Alright, so far I have confirmed on retail that Private First Class is 4 hours, and Superior Private is 5 hours.

Private First Class - 4 hours
https://youtu.be/rxjiapgk0g0

https://drive.google.com/drive/folders/14eS7gAtTkF9Z_iGOwMMZ3_0StpwozklD?usp=sharing

Superior Private - 5 hours
https://youtu.be/LPvoOQ3YG5g

https://drive.google.com/drive/folders/1PhD4zCHj2oynqByzhkqf-g6bKMKGeO1J?usp=sharing

Over the free login period ending March 1st, I'll try to work towards ranking up a few more times to confirm the duration of Sanction for the next several ranks.  Unfortunately, on my server(Asura), it will be difficult to prove how long sanction lasts as Besieged is rarely if ever lost there these days.

**Comment by DeuceFFXI** [comment]
Lance Corporal - 6 hours
https://youtu.be/_Rmoh5kDFKI

https://drive.google.com/drive/folders/16SGwPvUtrHdvjMhymW89WBGMeg5vXhcJ?usp=sharing

I'll continue to update this post for each rank as I progress.  Once finished, I'll make a final post.
