### ISSUE TITLE
Marid Incorrect Drop rate

### ISSUE THREAD

**Issue by ElectronicMan83** [EdenServer/community#3036]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

From Wiki : 

| Marid Hair (7.6%)Marid Hide (9.4%)Marid Tusk (4.2%)

In the current situation
-  2 hair in 4 hour of farming ( around 75+ kill )

Got a tusk almost each time and double drop 1/3 ish.

**Comment by E5una** [comment]
Which zone were you farming in? There seem to be slightly varying drop rates in different zones, but more importantly ffxidb.com seems to have the more accurate data that Eden is likely using. It has a much higher sample size for these mobs than the wiki which lists the drop rate as "may be inaccurate" due to a small sample size.

http://www.ffxidb.com/zones/51/marid

**Comment by ElectroNicMan83** [comment]
I tried Wajaom, Tusk seem to be accurate . But for the hair, bhauf. drop rate seem off by a lot . Wajaom seemed accurate or pretty close to what it should be .

**Comment by KnowOne134** [comment]
looked up drops and compared to http://www.ffxidb.com/zones/52/marid and http://www.ffxidb.com/zones/51/marid and both are accurate to what we have except for a .1% for a Lesser Chigoe to drop
drops are changed by how many tusks get broken during fight.
