### ISSUE TITLE
Orcish Barricader Lantern Shield Drop Rate

### ISSUE THREAD

**Issue by jaymantan** [EdenServer/community#3045]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

The Lantern Shield drop rate from the Orcish Barricader may not be accurate. Per old posts, there's a 5% chance to drop the shield (statistically 1/20 kills). I've been camping and killing every pop for the past two days and am currently 0/32 for the shield. The person who was camping before me for 2+ days went 0/40+. Statistically speaking, the shield should have dropped 3 times within our 70+ straight kills. Are we just unlucky? Can we get a check on the drop rate?

version 30181205_0

6/27 Update: I'm currently 0/55.
6/30 Update: I'm currently 0/82.

**Comment by Rikoooooo** [comment]
I have also noticed this drop rate being considerably low. I spent a couple days going between this "NM" and Hoo Mjuu the Torrent. This actually makes a good comparison I killed Hoo Mjuu the Torrent around 8~10 times over a day and got the Monster Signa. I was going to the Orcish Barricader after and killing that as well as the Wallbreacher which is in the same spot. Out of around 15 kills of both Orcish Barricader and Wallbreacher I got no Lantern Shield but 2 Strike Baghnaghks_(which are supposed to be a lower drop rate than the shield according to the old wiki)_.

Also Jaymantan pointed out that this is supposed to be a 5% drop rate because he looked at the old wikipedia, like I did also. ffxi wikipedia is actually very inaccurate when it comes to things that are not reported so often. Even things that are, there's too much human error over time when considering a drop rate% from that site. XIVDB shows much cleaner info with little error, even on things that aren't reported much. You can see right now on the old wiki that this shield would seem to be a 5% drop rate. However, when you look at XIVDB it shows that it should be around 25% drop rate, the Baghnagkhs are also around 20% drop rate as opposed to the 7% that the old wiki shows. I'm willing to bet that XIVDB is correct on this one, both of the drops.
