### ISSUE TITLE
Seiryu has no Regain

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#3055]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Seiryu currently has no regain, it should use TP moves more often when it has regain. This should also apply to the Seiryu that Kirin summons.
https://www.youtube.com/watch?v=83qR8JPqd1g
https://youtu.be/QFXAlvgOHXo?t=588
https://ffxiclopedia.fandom.com/wiki/Seiryu

version 30181205_0

**Comment by Slamm21** [comment]
Watch any rdm solo him, he did not have regain.
The vast majority of mobs in ffxi did not have regain but people underestimate just how quickly you can give a mob 1k tp with even 1 person hitting it

**Comment by FariskaEden** [comment]
I think the second video shows that it clearly has regain. Here's also a video of Avesta soloing it https://www.youtube.com/watch?v=pqTbRTZeyo4 and it TPs pretty quickly multiple times without any melee attacks being made.

**Comment by Slamm21** [comment]
No it does not.
Mobs use TP as soon as they have it under 25%, if it had regain the video would be very different. Every Nuke you do, or any spell that does 1+ damage gives 100tp.
https://www.youtube.com/watch?v=b4OyhaOky_Q
here is a clearer video, you can see it uses a tp move at 17% and does not for the rest of the fight. This is the only TP move it does 25% or below which would be impossible if he had regain.

**Comment by VirtuosusFFXI** [comment]
The Avesta video clearly showed Seiryu use a TP move at 0:20 and then another at 1:42 and then a third at 3:24. While the video is sped up, you can tell that Avesta is not using enough TP feeding spells to give him over 1000 TP between each move.

The video you linked can't be used as evidence because it's a private server. Wouldn't the best way to solve this be to just go and pop a god on retail? I doubt they changed anything.

**Comment by Slamm21** [comment]
If the video I linked is from a private server, then yeah ignore it. I don't see it saying anything like that in the description though unless I'm blind.
No harm of course popping it on retail, getting it to under 25% and just standing there not taking damage.

**Comment by VirtuosusFFXI** [comment]
I had to dig through that person's channel to be sure of it but yeah it's on Nightbrood server. Found it after looking through enough videos, since I thought it was odd the upload dates were recent and the quality was good. The Avesta video as well as the second video Fariska linked in the original post are pretty good proof, but I'm sure they can supply retail proof if necessary since they have an active account I believe. Both wikis also mention the regain.

**Comment by VirtuosusFFXI** [comment]
If anyone decides to go ahead and test this on retail, be sure to determine the following: 

1) Note whether it spawns with TP or not. This might be hard to figure out because Seiryu typically spawns and starts casting, giving it enough time to regain naturally while its busy in a long spellcast.

2) Get it to sub 25% to ensure it uses TP as soon as it hits 1000, then make sure you don't feed it any TP or get hit. Note the time between TP moves and make sure he doesn't waste his time casting spells between them, as that would introduce delay. This can be used to roughly estimate how much TP regain it has.

**Comment by Slamm21** [comment]
Thanks, have no issue with being proved wrong :)
I stand by my most mobs do not have regain though, same with refresh.

**Comment by VirtuosusFFXI** [comment]
Adding onto this: https://www.bluegartr.com/threads/51311-Seiryu-Issues

> seiryu always has TP regen with insane amount.

> I noticed it also when it was shadowbinded and it spammed Wind Wall 3 fucking times before it broke...

 > this is normal seiryu behavior<_< watch the beginning of the video, it uses radiant breath followed by 2 wind walls in about 30 seconds total 
(video removed of course)

**Comment by FariskaEden** [comment]
https://www.youtube.com/watch?v=gF7ZGJQvqMA shortest I saw between two TP moves was 6 seconds (where I saw "Seiryu readies movename") but it varied a bit. Didn't seem to change it's usage when it went below 25%.

**Comment by dowzer** [comment]
Confirming Seiryu has Regain. The fastest "back to back" TP moves were approximately 6-7 seconds apart.

https://www.youtube.com/watch?v=4RZ4bMgL2pg

**Comment by 59blargedy** [comment]
looking at this, i'm kinda inclined to believe he also does back to back tp moves, but there's an occasional spell in between that makes it difficult.

**Comment by dowzer** [comment]
It definitely looked like a potent Regain. I wonder if there’s a difference when a kc feeds it

I landed Silence and Bind but there was still a discrepancy of time between tp moves. A larger sample under 25% HP would be needed to determine the potency of Regain and frequency of tp moves

**Comment by dowzer** [comment]
Keeping Seiryu silenced and bound didn't seem to affect the erratic frequency of tp moves.

With little to no tp feed, Seiryu seemed to use a move every 6-7 seconds in succession. The longest interval between tp moves was 12 seconds. Later in the video, feeding him with a kc didn't increase the frequency of tp moves, the shortest interval was still 6-7 seconds.

https://www.youtube.com/watch?v=tsOe3eKTLj0

Also, in the first video, it did not appear to have tp upon spawning it. It was able to melee for two rounds before casting Tornado.

**Comment by 59blargedy** [comment]
resolved december 7 update
