### ISSUE TITLE
Respawn for Outdoor mobs is incorrect

### ISSUE THREAD

**Issue by greyenvy** [EdenServer/community#3065]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0

The respawns for outdoor mobs is set to 5m30s.  From the ToD in the log they will respawn exactly 5m48s from that message since the corpse takes 18s to disappear.  The timer should be set to exactly 5m on outdoor mobs.

This can be tested by going to literally any outdoor area and killing a monster and checking the respawn.

**Comment by Mozzy4Ever** [comment]
Tested on Land Crab in South Gustaberg (NPCID 17215922). Death message was 4:59:08 so add 5 mins 16 seconds (Pretty sure it's 16 seconds to despawn, not 18) should mean it respawns at 5:04:16. Instead respawn at about 5:04:56.

So can confirm, respawn time for outdoor mobs does seem to be incorrect.

**Comment by greyenvy** [comment]
Yeah probably a client/lag issue.  Could be 16-18s for corpse despawn but either way it is still 30s too long.

**Comment by FariskaEden** [comment]
Have outdoor mobs always been set to 5 minutes on retail?

**Comment by 59blargedy** [comment]
https://ffxiclopedia.fandom.com/wiki/Respawn_Time?oldid=297560
seems so

**Comment by FariskaEden** [comment]
I did take a look at it on retail but found something weird, some mobs I killed at different times respawned at the same time. I believe that the server will only spawn mobs at the :00 and :30 second marks (on w/e time it's on so my clock was off probably) so that's why there was same time spawns. Outdoor and dungeons have about 5 minute spawn timers on retail. Dungeons in this era had longer spawn time. Not sure if the rounding thing was around in era though.

https://www.youtube.com/watch?v=-YMmNEDqm4s
https://www.youtube.com/watch?v=AtA8Cl1r8a8
