### ISSUE TITLE
Excavation Duty - Brittle rocks & Magic Mortar (PUP) doing too much damage

### ISSUE THREAD

**Issue by Aster-FF** [EdenServer/community#3228]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

As stated in title, Automaton's ws Magic Mortar seems to be doing too much damage, perhaps Brittle rock's damage reduction formula is not applying correctly against Magic Mortar? It currently does 150+- damage on the rock(Automaton HP: 100%), and goes a lot higher(900+) with the right build. The only downside is that it takes prep time to make this happen, around 10mins usually, to bring the Automaton's HP to as low as possible. 

To reproduce, just bring mage automaton's hp down to as low as possible, and then get it to use Magic Mortar.

version 30181205_0

**Comment by FariskaEden** [comment]
I looked into it how it did on retail at iLvL119 on that rock and it didn't do a lot.
https://i.gyazo.com/c16108a0def5a8be497af22e7b17372d.mp4 - 20 damage MM at 32% HP with 1k TP
https://i.gyazo.com/0d7b571c7d5446390f08853ea3cad6e1.mp4 - 18 damage MM at 32% HP with 3k TP
Not sure what damage type magic mortar is since even today they still don't know what damage type it is.
![image](https://user-images.githubusercontent.com/46270382/92129509-9dd2b100-edd1-11ea-9033-cdd36af10ca6.png)

I'd also take a look at the -MDT the rock has since I think I've seen Thunder on Eden do more damage than that to the rock.

**Comment by KnowOne134** [comment]
fixed 11/9 update
