### ISSUE TITLE
Frightful Roar

### ISSUE THREAD

**Issue by Elysien** [EdenServer/community#3231]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Both the blue magic spell version, and the monster version, seem to be adding defense, not reducing it.

**Comment by VirtuosusFFXI** [comment]
Confirmed myself using Brontotaur in Uleguerand Range that their Frightful Roar "Defense Down" debuff is correctly lowering my defense by exactly 10%. Also confirmed on test server that Blue Mage's Frightful Roar spell is correctly lowering the target's defense by exactly 10%.

I would suggest making sure what you say is true before creating a bug report on it. Also, your bug report has completely ignored everything in the check list. If you believe this is a bug that only happens under certain circumstances, then provide more information. Otherwise, this report is safe to close.

**Comment by KnowOne134** [comment]
Closing unless evidence can be shown

**Comment by Elysien** [comment]
@VirtuosusFFXI 

Strange, I noticed it when trying to learn roar in sac, when used they were giving me +1 defence. I went back today though, in response to your post here, and it's working as it should.

As for saying the blu spell was similar, it was largely based on my then-findings of the enemy version, but also tested it some with various before/after check experiments to see if the defense description changed it did not, so assumed it may be broken like the enemy version seemingly was.

Anyhow, if it's working then that's cool
