### ISSUE TITLE
Khimaira drop rate

### ISSUE THREAD

**Issue by him911** [EdenServer/community#3240]
Retail outlier was 20-25 kills for hauteclaire. Going on 60+ kills now no sword, i think the test server test returned with 1 sword on 350 kills, i mean loll  Not sure what the TH change a few months back

### Checklist

- [yes ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [/ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ /] I have provided my client version in the details. (type /ver into your game window)

**Comment by perkuprightmeow** [comment]
FWIW I went around 2/25 on the test server when I looked into this about two weeks ago.

**Comment by 59blargedy** [comment]
test server results from the test op was referring to were 31 out of 363 (8.5%). can certainly have a discussion about probability, but let's start with the right data.

**Comment by Mikokiko** [comment]
I'm one of the 2 persons that actually did the test to try to find the issue with Khimaira Hauteclaire not droping.

The data we gathered, out of 355 kills show the percentage drop rate on test server to be accurate. All kills were done with TH4. 

The longest streak between 2 kills before an hauteclaire droped was 49 kills. 

**This is why I wanted to wait until we're at 0/50 before making a bug report.** 

We are currently at 0/44 hauteclaire drop data tracked since April (including other LS). We have an average of 22.73% drop rate atm for Seveneyes. 

We have been gathering data since April 25, 2020, no Hauteclaire have droped since then. We unfortunately don't remmeber if Drognand (sorry if spelling is wrong) was the last Hauteclaire obtained on the server, or if someone else got one before we tracked data, so it could be more kills then the 0/44 we are at right now. 

It seems the raw poourcentage of the drop is not the issue, but maybe the RNG factor deciding what drop. I'm not quite sure how the RNG works on eden.

**Comment by him911** [comment]
ya i duno about all that but we getting ridills np vs  0 hautes, somethings off

**Comment by icariumkupo** [comment]
Heard theres been 6 hauts dropped in the last two weeks. somethin still off or what lol

**Comment by Slamm21** [comment]
this is just luck, closing
