### ISSUE TITLE
Apollyon SW - Exit Chest

### ISSUE THREAD

**Issue by Slamm21** [EdenServer/community#3351]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
ver 30181205_0
### Details
Group entered on Lightningday, got to the final floor, killed all Lightning Elementals and no chest popped.
The chest should pop after you kill all elementals, the element of the day you entered SW Apollyon.

**Comment by Slamm21** [comment]
![image](https://user-images.githubusercontent.com/5552081/96442380-f1268480-1202-11eb-9ffe-0560840b021c.png)
![image](https://user-images.githubusercontent.com/5552081/96442455-10251680-1203-11eb-92f3-6b7872c9424c.png)

**Comment by Satirof** [comment]
"Defeating the Elementals corresponding to the in-game day that you entered this floor will spawn the final chest"
As in, when you entered the fourth floor, not SW Apollyon
So since you entered that floor on lightsday, it should of been light elementals no?

https://ffxiclopedia.fandom.com/wiki/SW_Apollyon

**Comment by Slamm21** [comment]
yeah my bad, closing
