### ISSUE TITLE
Extremely low drop rate on BLU Testimony

### ISSUE THREAD

**Issue by Eternan** [EdenServer/community#3371]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I have spent ~12 hours farming my BLU Testimony before finally receiving one. More than half of that time was spent with TH3 and a small amount with TH1. I would estimate over 130 Mamool Ja Mimickers were killed in this time frame. If anything I'm requesting a deeper look into the drop rate or any possible bugs that might exist with these mob's loot table. The Mimickers that were killed are located in both Mamook (2 spawns near F-8) and Wajaom Woodlands (2 spawns: 1 at H-10, the other at D-8). The Testimony officially dropped from the Mimicker located at the top right corner of F-8 in Mamook.

Client Version: 30181205_0

**Comment by Shoruto** [comment]
This appears to be all over the place based on the various reports located.  Not able to find any era % rates.

https://ffxi.allakhazam.com/db/item.html?fitem=10519
https://www.ffxionline.com/forum/ffxi-game-related/race-job-type-q-a/blue-mage/66106-blue-mage-test

Apr 21 2007
Helped a friend get this today and we had no luck after killing 20 of these Mimickers around Wajaom Woodlands and Mamook. **Every BLU I've talked to said they got drop in 2-3 Mimickers** so I don't know what the problem was. Even had a THF with TH2 with us (some of the people I talked to didn't). **Don't know what the problem was but we left with no drop after 4 hours trying...**

Nov 08 2006
 **Took 2-3 Mimickers but we got the test**... just thought I'd let you all know. I'm sure there are other Mimickers but this one was nice, it was easy (coned T to me at 70) and near the city. Hope it helps. 

Eohmer
Blue Mage Test
02-13-2007
We're currently trying to get his Testimony, and it's a major pain in the ass. **2 nights and it hasn't dropped yet. I once heard a Blue Mage in our server once took 3 days to get the drop.**

Eohmer
02-19-2007
Update: **We got the test at the end of the 3rd night of trying.**

**Comment by Slamm21** [comment]
http://www.ffxidb.com/zones/51/mamool-ja-mimicker
http://www.ffxidb.com/zones/65/mamool-ja-mimicker
that's quite comfortably in the common category
15% base, 45% with TH4

**Comment by Slamm21** [comment]
would not surprise me if all testimony are the same also

**Comment by 59blargedy** [comment]
resolved in January 4, 2021 patch
