### ISSUE TITLE
Orcish Grapplers in La Theine Plateau Attack Too Quickly

### ISSUE THREAD

**Issue by JigokunoOusama** [EdenServer/community#339]
They act as though they have Hundred Fists active.  An EP at lvl 11 had my HP in the red.

**Comment by godmode** [comment]
Have you fought any orcs in other zones? Do they all attack too fast or just here?

**Comment by beauxq** [comment]
I tested Grapplers in La Theine and Initiates in Sarutabaruta on Eden. Both match each other at about 5.07 seconds per attack round.
This is a little bit fast according to this video:
https://www.youtube.com/watch?v=yiRGdn6Ax_0
The Grappler has a 6.4 seconds per attack round.

It looks like someone forgot about the Martial Arts that was already included in what they timed from retail, and then DSP adds Martial Arts, so they effectively get the Martial Arts bonus twice.

Note that if the Eden Grappler has Martial Arts, and if we took that Martial Arts away, it should change it to 6.4 seconds per attack round - that matches what is in the video.

But that's not what we want to do, because we want to keep Martial Arts in.

So we need to find the base delay that gives 6.4 seconds AFTER Martial Arts, instead of 6.4 seconds BEFORE Martial Arts like it is now.

**Comment by beauxq** [comment]
It would seem what we want for a base delay for all MNK mobs is 464.
Then Martial Arts would automatically adjust that for the mob's level.

That seems a little weird to me, because the base delay for player H2H is 480. But that would put Grapplers and Initiates at 6.67 seconds per attack round, and all of my measurements are closer to 6.4 seconds.

Maybe someone with access to a retail account could get better measurements. If someone with access to a retail account could use the timestamp addon on and go let a grappler swing at them for a few minutes, and screenshot the log...
