### ISSUE TITLE
sneak / invis

### ISSUE THREAD

**Issue by tectal831** [EdenServer/community#34]
Sneak / invis durations are lasting 8 minutes each at the moment.

**Comment by gweivyth** [comment]
I had different results, so this may be based on the enhancing skill of the caster. Celisse is 71 and I'm only getting 6 minute durations. This may be a pretty decent thing to keep since it rewards players for leveling one of their skills. 

Maybe adjust it down but keep the mechanic itself in place?

**Comment by godmode** [comment]
Item times were greatly increased while spells were greatly decreased.
