### ISSUE TITLE
Dynamis Mijin Gakure only hitting players in the alliance with active claim

### ISSUE THREAD

**Issue by gweivyth** [EdenServer/community#346]
Mijin Gakure is not correctly hitting everyone in the area of effect, it is currently only hitting players in the group/alliance that have active claim on it.  Mattyg replicated this a bunch of times, as did I with my White Mage.

**Comment by godmode** [comment]
Hmm, I imagine this has to do with all aoe things. Do you know if things like aoe spells and other weapon spells land on members outside alliance?

**Comment by gweivyth** [comment]
The Quadav NM AoE (Curse I think it's called?) was working correctly, it killed Celisse a few times from outside of the main alliance.

**Comment by beauxq** [comment]
I think this should be dealt with as if outside of dynamis, according to the threat list (and the alliance of everyone on the threat list) because it could be harmful to make a lot of special cases just for dynamis.

For example, if an exp party has a powerlevel, if the powerlevel hasn't gotten on the threat list
by casting on someone else in the threat list, then it's ok if AOE doesn't hit them. But if the powerlevel has threat, then AOE should hit both the powerlevel and the exp party.
