### ISSUE TITLE
Summoner Blood Pacts incorrectly use avatar TP

### ISSUE THREAD

**Issue by seehj** [EdenServer/community#3528]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
ver. 30181205_0

According to update  Sep. 14, 2004:

"Avatar TP will now affect the damage of select magical Blood Pact attacks. Just as with normal player TP, after the attack, the avatar's TP will be reset to zero. Avatar TP does not affect physical, enhancing, or enfeebling Blood Pact techniques, and thus will not be lost after an avatar uses one of these abilities"

Currently every blood pact consumes avatars tp regrdless if it scales with it or not, but only magical blood pacts should use it.

Wiki pages about Healing Ruby 1&2, Spring Water from 2008 mentions that amount healed scales with tp but I haven't seen any changes to them in patch notes. My assumption is that "affect the damage of select magical Blood Pact attacks" is mistranslation, since later they explicitly state which types are not affected and they don't mention healing type.

There is also this thread: https://www.ffxionline.com/forum/ffxi-game-related/race-job-type-q-a/summoner/69477-blood-pacts-and-tp

last post mentions that healing ruby and spring water is affected by tp.

"Avatars have the same basic TP properties as players, only that their TP only affects their magical BPs (Nuke IVs, Meteorite, Healing Ruby I/II, Spring Water, Merit BPs, stuff like that)."

Patch note source: http://www.playonline.com/updateus/040914gs7tr3.html

**Comment by deepbreathingeden** [comment]
![1612766398802](https://user-images.githubusercontent.com/53072734/109504522-11215b00-7ab5-11eb-8328-c3ce966611b5.jpg)

**Comment by Steam-arch** [comment]
Does not help that much, but incase someone wants to tackle this someday: 

On eden currently Whispering wind & Springwater & Healing Ruby II are unaffected by tp, Healing ruby I calcs are the same as wikis (but makes you wonder if it was changed at some point and is "off" era because its healing for +1000hp for 6mp with 2k tp) 

Here are 2016 testings of the abilities
![image](https://user-images.githubusercontent.com/69089249/140728058-e435d34e-1c82-4f43-81b1-14830c86b0cc.png)
(source https://www.ffxiah.com/forum/topic/46440/the-6th-ministrys-secret-a-summoners-guide-v2/46/)

According to that, only the range of springwater and whispering wind are affected by TP (and the healing + is tied to avatars hp scaling hmm) Which would make more sense later past 80 cap.  Altho wikis say that healing IS affected by tp in all abilities, and wikis springwater 2012 addition also entitles: 
![image](https://user-images.githubusercontent.com/69089249/140730419-b938a1fe-e541-4490-8c90-83e675cf5d33.png)
which is abit weird since 2016 testing didnt show any increase, maybe there was some changes to it (?)

**But for 100% atleast healing ruby II should be affected by tp. 3000 tp (2016) is exactly a 50% increase from 0 tp.** Does not give 1k and 2k tp values.

**Comment by Steam-arch** [comment]
Weird request but, can we split this bug report into 2? Reasoning: the other one is much easier to fix and more straight forward and is a somewhat significant buff to smn BP2 abilities + magic abilities which arent currently that used.

Split would be:
1: Avatar Physical PBs are reducing avatar tp to 0
2: Some Avatar BPs should scale with tp

I can do the reports for them.

**Comment by seehj** [comment]
Hey I can comment \o/
3rd split would be that enfeebling  and enchanting BP shouldn't consume TP either.

Should this issue stay open and new ones referance this for info?

**Comment by 59blargedy** [comment]
resolved in November 21, 2022 update
