### ISSUE TITLE
Cerberus can use TP move 3 time in a row

### ISSUE THREAD

**Issue by ElectronicMan83** [EdenServer/community#3584]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

In retail Cerberus can TP 3 times in a row after successfull stun. The current cerberus is easy and does not do that. I remembered that it was a lot more fun and challenging in retail. Check Oyazzaiiii from this post who got closed because no proof. On the video at 3:00ish it clearly show it. Not because of TP feed. And we can see on wiki some talk about this feature too. ( Triple attack; triple ws? ) 

https://github.com/EdenServer/community/issues/2020 
"Cerberus could only used TP multiple times in a row if the TP moves were stunned. If the TP move got through, its tp reset to 0. As for TP regain, I think we need someone with a retail account to test that. It's too hard to tell from videos because there aren't any where TP isn't being fed. I personally thought it had regain but Elysien claimed that it didn't in his report before ToAU HNM were released."

Main video that prove that cerberus do not lose tp if stunned until 3 time unless TP goes off. If you watch carefully you can see at 3 minute sequence.

https://www.youtube.com/watch?v=pW39RBZV49g

Wiki : 
" At 25% Cerberus will begin to use Gates of Hades when it gets TP. The cast time is long enough to Stun fairly easily, however lag from competing linkshells or even your own alliance can easily allow Gates of Hades to go off even if your Stun appears in log window to go through. It is especially dangerous because Cerberus can use a second Gates of Hades immediately after you Stun the first."

Second video.  These guys dont stun it 3 time at the end. But 2 time and it tp back to back.
https://www.youtube.com/watch?v=HckKO-NLY1A

Third video .  3:47 : GoH Stun > wears off > Lava TP move not stunned.
https://www.youtube.com/watch?v=kYXhDEGy5qY

Not the main subject but need to be adjusted too. 

https://ffxi.allakhazam.com/db/bestiary.html?fmob=4152 
Note: AoE abilities will hit -everyone- within range, regardless of whether you or your alliance have any hate on Cerberus or not.

**Comment by roriffxi** [comment]
Stunning a tp move on eden doesn't reset a mobs TP to 0, but it does reduce it some.

In each of your videos Cerb is below 25% and has melee on him.  This means 
1) He will TP as soon as he is able to (IE: not locked by the animation of a previous TP move, or not stunned)
2) He is being fed constant TP

In your main video at 2:52 Cerberus readies GOH, gets hit by 4 melee hits and lands an auto attack after the stun wears off (this hit happens after the log readies the GOH but it would be impossible for it to back-to-back and get this melee hit off with this timing due to the cast time of GOH so the hit had to have happened in-between and it is just log delay), readies GOH again at 3:03 which is also stunned, takes 4 melee hits and then readies sulferous breath at 3:10 which is not stunned, takes at least 6 melee hits & a steel cyclone and readies GOH again at 3:19 and takes 2 more hits that might have happened before the GOH was readied and show up after due to log delay.

Video 2 it readies goh at 3:10, the hits are filtered but there are melee swinging at it and from the animations you can see those hits landing, it then uses another TP move a 3:17 that isnt stunned it melees several times and is hit by 2 weapon skills then at 3:28 it uses GOH and is stunned and then dies.

Video 3 it gohs at 3:42 which is stunned, takes 5 melee hits and gets off an auto attack before lava spitting at 3:52, it gets hit by a gekko and then at 4:00 the video is cut here, you see the gear on rdm (Vihke) change without actually displaying the blink animation and it goes from casting a white magic spell to finishing a black magic spell cast, so the log / timing here isnt usable for determining the previous sequence.

The split picks up with a GOH being stunned, 4 melee hits landing and then another GOH getting stunned and cerb dieing afterwards.

All of this is consistent with a system where partial TP is removed after a stun and then having the TP filled back up due to feed from taking / landing melee hits and is what you would observe if you were to use the same tactics on Eden.

**Comment by ElectronicMan83** [comment]
On Eden Cerberus will not come out of a stun immediately into another TP move, we’ve killed it with plenty of melee multiples times and it does not behave in the same regards as the video posted. Far from it. We use 2-5 melee most of the time. This can be easily debunked because people never stun under 25%. Will record video on the next few cerb unless this can be tested on test server.

**Comment by roriffxi** [comment]
![Capture3](https://user-images.githubusercontent.com/37307792/104959760-c5dd3e00-5987-11eb-976e-dd7865088a33.PNG)
I captured this on the test server.  It definitely does look like tp is either being wiped to 0 or by a much larger amount than it should be when GoH is stunned.

The number of melee hits i got off during the stun (I was using hundred fists & a mercurial sword.  Wearing a GM cape for the +900 to all stats so my stuns from /drk would land).

I also had done some fighting using just h2h and there was an instance where i stunned lava spit and landed 9 h2h hits before it TP'd again.

I'm not completely certain how much TP 9 h2h with 0 subtle blow feeds but that would seem to me its not getting 0'd but is definitely at minimum having a much higher % of TP wiped on stun than it should.

This is probably systemic across all mobs and would be worth looking into.

**Comment by InoUno** [comment]
As of the February 1st, 2021 patch, mobs will now retain some of their TP if interrupted during a TP move. As such Cerberus should behave more like what is documented here.
