### ISSUE TITLE
Land Worms in Korrokola Tunnel should not aggro

### ISSUE THREAD

**Issue by AJ3281** [EdenServer/community#366]
Land Worms in Korrokola Tunnel should not aggro. In era only the land worms in qufim aggrod.

**Comment by gweivyth** [comment]
I seem to remember these being aggressive.  Can you provide some kind of source so we can verify?

**Comment by beauxq** [comment]
https://ffxiclopedia.fandom.com/wiki/Land_Worm

It's been that way through the entire history, and there isn't any reason SE would have changed it anyway.

And it's not the only instance of mobs with the same name that aggro in original areas, but don't aggro in RotZ areas.
It is the same with Soldier Crawlers and Rumble Crawlers and Helm Beetles. (These should also be checked on Eden, because I've seen it wrong on DSP before.)

**Comment by beauxq** [comment]
I just confirmed on Eden that Soldier Crawlers are also wrong.
I recommend we change the issue name to:
Certain mobs in RotZ areas should not aggro

and see if we can find any more...

**Comment by AJ3281** [comment]
I was going to say what Beaux said in regards to the link to ffxi wikia page in retail. Besides that it has always been that way. I have run through here countless times and they never aggrod. Not to mention if your previous server in era ever had a smn burn here where a high level tank would pull the zone and then a group of 5 summoners would sunce to a lvl 12 and kill the horde and get from 12-18 and repeat. This literally could not be done if the worms were aggroing then. 

Now that I think about ti there was a bat that aggrod me somewhere that shouldnt of but cant remember where.
