### ISSUE TITLE
Chocobo Digging: Randomly increased delay on digs.

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#372]
Veteran Rank so the dig delay should be 0.  First time digging since new DSP version.

![image](https://user-images.githubusercontent.com/41595732/49116206-e2c7cc00-f26a-11e8-9002-aca692f0699a.png)

![image](https://user-images.githubusercontent.com/41595732/49116223-eeb38e00-f26a-11e8-84df-5f50d3416d1e.png)

Happens on both my characters.

**Comment by Lilswitche** [comment]
After speaking with Pan... it seems the timer between digs only actually goes down when you're moving and not standing still.

**Comment by gweivyth** [comment]
I've been experiencing this too.  I'm rank 4 now but when I was still rank 3 and there should have been a delay, randomly I'd be able to dig back-to-back making me think that I had ranked up.

**Comment by Wiggo32** [comment]
Yea, the new dsp version broke digging in many different places, and we're waiting for me to have some time to fix it because it's going to be a major overhaul which will require I'm approximating about 40 hours of straight work. So, the next time I have 2 complete full days free with nothing else on my plate, I will straighten everything out.
