### ISSUE TITLE
Dungeon mob respawn timer disparity

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#390]
Some are 5 mins, some are 18~ mins. We should probably normalize this one way or the other.

**Comment by beauxq** [comment]
I think it's not that important for all the timers to be the same.

I think era experience camps should be viable with fast enough respawn times.

And I think quests involving dungeons should not be made more difficult for low levels because of fast respawn times.
(If someone is working their way through some high EP and DC mobs, taking 3 minutes to kill each one, they shouldn't be killed by respawn links.)

**Comment by tectal831** [comment]
Mobs will be handled as they were in era, and on an individual basis. If you feel some mobs are incorrect, please post the mob individually.
