### ISSUE TITLE
Heatsink reducing burden on all maneuvers, not just fire

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4465]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Heatsink seems to have a large impact on all maneuvers rather than just fire. I can't speak to the specifics of what it is doing on Eden, but it appears to be affecting all when it should only be fire maneuvers in era. Heatsink affecting all maneuvers is a 2011 change.

https://forum.square-enix.com/ffxi/threads/18132-December-14-2011-(JST)-Version-Update

![image](https://user-images.githubusercontent.com/13668758/130644629-7ff1a533-856b-46b7-9ac3-d5d84d505434.png)

**Comment by Dribblet** [comment]
Looking over patch notes: Heatsink has only has 1 offical change in the patch notes from inception to 2017, and thats to change it from only affect Fire Maneuvers to affecting all Maneuvers (patch linked in OP's post). From this, we can assume it's functions are similar on launch up to 2017 apart from what maneuvers it affects.
 
 This gives us clear knowledge on what Heatsink's functionality is when combined with a community rep's post on the JP forums in 2016 detailing what Heatsink does:
https://forum.square-enix.com/ffxi/threads/7090-%E6%95%99%E3%81%88%E3%81%A6%EF%BC%81%E9%96%8B%E7%99%BA%E3%81%95%E3%82%93%EF%BC%81%E3%80%90%E3%81%8B%E3%82%89%E3%81%8F%E3%82%8A%E5%A3%AB%E3%80%91?p=585033#post585033
 
 Translated, it gives us a baseline of 1 degree of burden removed per tick (3 seconds), with the heatsink attachment involved it bumps up the burden removal to 2/tick at 0 water maneuvers, 4/tick at 1water, 5/tick at 2water, 6/tick at 3water.
 
The baseline for 1 degree of burden removal per tick was also independantly verified by a user through testing in-era, as shown by this archived ffxiwiki post in a 2008 era: https://web.archive.org/web/20081231070501/http://wiki.ffxiclopedia.org/wiki/Overload
 
The deep numbers testing done by the same user that did the Overload/burden testing earlier also shows that Heatsink has an effect similar to doubling the amount of burden shed per tick as demonstrated by their archived post. (Note that since overload procs are random, it's not a direct 100% noticeable change) https://web.archive.org/web/20090228000848/http://ffxi.allakhazam.com/db/jobs.html?fjob=18;mid=1195067879211022569;page=1;howmany=50
 
 To pull an example from the link:  
 5 fire maneuvers on Iceday causes an overload which lasts 51 seconds, doing the same 5fire on Iceday with heatsink attached produces an overload that lasts 37 seconds.
 
 From this, it can be relatively safely assumed that heatsink in-era functions the same as the Community Rep describes, apart from replacing "all burden" with "fire-specific burden" to match it with era values, and that the only OoE functionality it has right now on Eden (barring incorrect values) is that it should only be affecting fire manuevers in-era.

**Comment by 59blargedy** [comment]
resolved in a previous update
