### ISSUE TITLE
Flash should have no effect when monster is already flashed

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4493]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

![flash2](https://user-images.githubusercontent.com/13668758/132688878-b5067956-5bdc-4f86-83cf-308a39b69769.JPG)

https://ffxiclopedia.fandom.com/wiki/Flashbulb

"The Flash effect from this attachment is treated as the same effect as the white magic spell, thus if it is used while the enemy already has a flash effect on it, it will have "no effect", and vice-versa."

**Comment by FariskaEden** [comment]
No-effect message does occur for when the automaton tries to apply on top of a player's flash / another automaton's flash. Maybe it was resisted in the screenshot you provided since that can occur.
![image](https://user-images.githubusercontent.com/46270382/132696044-4eeba73f-8d38-4227-ac93-b09ed098ba38.png)
However I think the player version is able to overwrite the automaton's? Though not sure if that's retail accurate or not.
![image](https://user-images.githubusercontent.com/46270382/132696111-b834984b-6f38-4248-b8bc-fc89c947d041.png)

**Comment by E5una** [comment]
Must have been resisted then, I've only ever seen it say it worked, that was just the first time I took a picture, strange. Thanks for testing :)

**Comment by 59blargedy** [comment]
can one of you test whether player overwrites player, i think it might and then i'll know what to fix.

**Comment by E5una** [comment]
In my experience as a BLU it doesn't (at least not with actinic burst interacting with flash) but I'll go test right now and let you know. 

This happened in my party last night though...

![huh](https://user-images.githubusercontent.com/13668758/132878691-06148943-13d4-46c0-8376-6ada36889816.JPG)

First time I've ever seen flashbulb say it didn't work, and it was after an ally used flash

**Comment by E5una** [comment]
Player then automaton. Both 75 vs level 40ish mobs.

![image](https://user-images.githubusercontent.com/13668758/132879777-223c8406-f35b-4dde-a537-289833938634.png)

![image](https://user-images.githubusercontent.com/13668758/132880131-498be092-cffb-4ff4-b7d8-35a02ac9877f.png)

![image](https://user-images.githubusercontent.com/13668758/132880174-97a08cf2-0d75-46e1-8fcb-54f938e41f84.png)

![image](https://user-images.githubusercontent.com/13668758/132880398-70f4b7a9-e8fd-42bd-beb2-1e0d497c2407.png)

![image](https://user-images.githubusercontent.com/13668758/132880500-be0c731a-a66d-4777-8230-529a466366d2.png)

Maybe its working fine and the player flash is just wearing off VERY quickly? Seems odd for a 75 PLD to have flash wear off that fast vs a too weak mob.

**Comment by E5una** [comment]
Player -> Player

![image](https://user-images.githubusercontent.com/13668758/132880987-2e0f5ac7-8eef-4d77-a19d-5aefc9f5d195.png)

![image](https://user-images.githubusercontent.com/13668758/132881100-54c62144-0f3c-44b5-96ec-ce97630c8891.png)

![image](https://user-images.githubusercontent.com/13668758/132881258-2bf2e23d-59a5-463b-98b8-cafc4a6bacc4.png)

![image](https://user-images.githubusercontent.com/13668758/132881373-c4b77ac3-6f65-48ea-b99a-3928819e3a56.png)

![image](https://user-images.githubusercontent.com/13668758/132881508-a24796ac-ef64-43f3-8682-dd5b6389da5f.png)

Just going to throw in one more test of Minnemouse->Esunii in case something matters there.

![image](https://user-images.githubusercontent.com/13668758/132881628-fcf52f0c-7abf-42ac-aa23-b0b1bebfe67b.png)

Well okay then. Does this have something to do with MND or CHR potency or something?

**Comment by E5una** [comment]
I'll stop the testing there, let me know if you want me to do the Automaton -> Player test or any other testing!

**Comment by 59blargedy** [comment]
Ehhh, so this effects all flashes and isn't automaton-specific. since actinic burst can be overwritten by flash, flash overwriting is based on the power, however since the power declines per tick you can overwrite flash whether you're a player or an auto or even a blue mage casting actinic burst if the initial flash spell has decayed enough. not really sure how to deal with this atm, fixing title for now.

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
