### ISSUE TITLE
HP aggro thru wall?

### ISSUE THREAD

**Issue by adricteo** [EdenServer/community#4561]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Was in Sacrarium doing swift belt, we are outside the room with door closed. Formor from inside the room will aggro yellow HP. They can attack us from behind wall, now we cant attack them when they are just behind the wall.

**Comment by ConteAlmaviva** [comment]
Echoing this report; this makes 4-3 and/or Swift Belts an utter nightmare.  The Fomors will ranged attack through the wall, but you cannot attack them back due to LoS rules.  I don't recall era retail being like this; I don't think they ever aggroed through the walls.

**Comment by 59blargedy** [comment]
line of sight issues from the comment were resolved January 11, 2022. if someone can provide more details on the OP i'd appreciate it, im not sure if OP meant door or legit mobs are attacking from inside a wall.

**Comment by ConteAlmaviva** [comment]
@59blargedy It's been a while since my linkshell's last 4-3/Swift Belt run, though I think we have it scheduled for Friday so might get more firsthand data then.  If I'm remembering correctly, Fomors were blood aggroing through the doors, which they did not do prior to the LoS updates and I don't believe they did on retail.  Additionally, if they were RNG, NIN, or spellcaster fomors, they would attack/cast through the closed door, but you could not attack them or cast on them; it seemed like the door would count as obstructing your view of them for LoS purposes, but not their view of you.  I may be misremembering, so if we find things are different on Friday I'll update this post, but we're a bit more cautious in how we approach clearing the room to pop the NMs, so I might have to do some solo testing to fully verify.

**Comment by 59blargedy** [comment]
Ok so door but not wall. That's what was confusing me. Thanks for the addl
info

**Comment by bliven-was-taken** [comment]
https://www.twitch.tv/videos/1293937347

**Comment by 59blargedy** [comment]
thanks for the retail clip! can you tell me if you can a) cast magic
through and b) RA through the door as a player? (sorry)

**Comment by 59blargedy** [comment]
looks like aggro happens through doors on retail, and validated that players can /ra and cast magic through doors if they have a target on both eden and retail (i was able to cast and ra through the door on eden, not sure if the general los issues before were confusing the issue, but these doors have always been castable through).
what is definitely still incorrect is the range of the blood aggro, which (unverified) varies based on level of fomor hate. ill leave this ticket up for that purpose, though may look to consolidate the issue under the general fomor hate one.

**Comment by 59blargedy** [comment]
with the blood aggro changes, this is fully resolved in April 18, 2022 patch
