### ISSUE TITLE
Bee Family Final Sting

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#4564]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Currently final sting is able to be used above 25% from bees. From what I've seen on retail and in videos, bees will only use this move once they are at 25% or below. 

https://www.youtube.com/watch?v=O-xCe-M9Cm0&t=95s
https://www.youtube.com/watch?v=PB1h9rgcusk
https://youtu.be/IqmGSAP72X4?t=290
https://youtu.be/MJfhwts3uXM?t=192
https://youtu.be/lOmbvyvkf_A?t=138

version 30181205_0

**Comment by Mozzy4Ever** [comment]
Currently on Eden, Bees use Final Sting once they are at =< 50% HP. They should only use Final Sting when at =<33% HP.

https://forum.square-enix.com/ffxi/threads/31553-%E3%83%AC%E3%82%A4%E3%83%B4%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6?p=422397&viewfull=1#post422397 is a comment from a SE Community Rep on the JP FFXI forums talking about a change done in 2013 where Final Sting was reduced so that 2hp = 1 damage. In it, they mention that the activation requirements of 1/3rd HP is unchanged. Elsewhere in the JP forums, the same Community Rep talks about it needing an additional version update that is to come because the Final Sting change affects "Bees across vanadiel".
http://wiki.ffo.jp/html/6140.html also speaks of the 1/3rd requirement.

**Comment by FariskaEden** [comment]
Currently final sting is able to be anticipated by third eye. It should ignore third eye.

https://i.gyazo.com/694ba42a037bfb562b3f1599541b6dfd.mp4 - Final Sting going through Third Eye
