### ISSUE TITLE
Dia or Bio won't overwrite

### ISSUE THREAD

**Issue by Aeniesh** [EdenServer/community#46]
Attempting to skill enfeebling and dark magic and notice that neither will overwrite.

**Comment by Lilswitche** [comment]
I'll add this one in here as well. 
![image](https://user-images.githubusercontent.com/41595732/46429565-bed98580-c714-11e8-8425-032c005f6c22.png)

When casting a lower level Bio/Dia.. it should still do damage but not overwrite the effect.

**Comment by beauxq** [comment]
I think this is not correct in its current state on Eden.

I think everyone understands there are weaker spells and stronger spells:
Bio III > Dia III > Bio II > Dia II > Bio > Dia

There are obvious different scenarios for casting a second spell after one of them is already on the enemy:
3 situaions:
The second spell is stronger than the earlier spell.
The second spell is the same as the earlier spell.
The second spell is weaker than the earlier spell.

It may be less obvious that there are 2 different questions to ask for each of these scenarios:
Does the spell do it's initial damage?
Does it apply a new DOT/enfeebling status effect.

The 1st scenario is well-known and documented for both questions.
The 2nd scenario is not as well documented, but it is known by experienced FFXI players (because of the practice of spamming Dia to level enfeebling skill).

I couldn't find documentation on the 3rd scenario, and my memory is also fuzzy on it.
I think it may be divided into 2 scenarios:
a weaker spell of the same element
a weaker spell of the opposite element

This table shows all the scenarios and questions:

|                  | initial | dot effect  |
|                  | damage  | (new/reset) |
| ---------------- | ------- | ----------- |
| stronger spell   | yes     | yes         |
| same spell       | yes     | no          |
| weaker same elem | yes ?   | no          |
| weaker opp elem  | no ?    | no          |


The question marks are the ones without documentation and just my fuzzy memory. Maybe others can provide more information.

It sounds like Lilswitche would put yes in both the question mark cases.

For the non-question marks, what I noticed is wrong on Eden is that casting the same spell should not overwrite the dot effect.

**Comment by godmode** [comment]
You’re saying that casting same strength dia 1 should do damage but not overwrite the effect of a dia 1 already on the mob?

**Comment by beauxq** [comment]
That's right.
