### ISSUE TITLE
Bard songs not overwriting properly 

### ISSUE THREAD

**Issue by HitGubz** [EdenServer/community#4675]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)
- [X ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Client version: 30191205_0

**Scenario** 
Step 1: BRD uses Blade Madrigal + Valor Minuet IV on party 
Step 2: BRD uses Mages Ballad 1 + Mages Ballad II 

**Result**
BRD is left with Mages Ballad + Minuet when it should be left with 2x Ballad 

**Theory**
Seems as if the numerical value (IV minuet being greater than II ballad) is blocking it, whereas Blade Madrigal with no numbers is being overwritten.

**Comment by falzum** [comment]
It's working correctly now. What you're seeing is intended behavior. Songs overwrite the song with the lowest duration remaining. You're seeing this issue because ballad has less base duration then the other songs because no instrument for ballad.

Minuet and madrigal duration is 2:24 with instrument.
Ballad is 2:00 cause no instrument

**Comment by HitGubz** [comment]
Oh i seeeeee - thanks man. That's annoying but makes sense.
