### ISSUE TITLE
Auto attacking next mob issue

### ISSUE THREAD

**Issue by AJ3281** [EdenServer/community#481]
Say you are fighting two mobs at once and you just killed one then it autotargets the next one within range. You should hit relatively immediately but instead the game mechanics takes your next swing off your weapon delay instead of immediately attacking.

**Comment by Lilswitche** [comment]
Yeah killing a mob then auto-targetting definitely reset the AA timer on retail.  Manually seitching between targets didn't though.  I can't recall if being slept still wore down your AA timer but it doesn't seem to on dsp.

On Dec 13, 2018 2:30 PM, AJ3281 <notifications@github.com> wrote:

Say you are fighting two mobs at once and you just killed one then it autotargets the next one within range. You should hit relatively immediately but instead the game mechanics takes your next swing off your weapon delay instead of immediately attacking.

**Comment by DrunkSkeeterPilot** [comment]
This is still not fixed.
