### ISSUE TITLE
Monster Astral Flow way too strong

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#486]
As the title says. This is notably a problem with Kirin and Jungle Boogeymen

**Comment by Aneyus** [comment]
In addition to astral flow doing WAY too much damage and making fighting any summoner NM outside of dynamis a death sentence, if you do somehow manage to survive, the mob's avatar will spam its astral flow blood pact anyway. You cannot survive astral flow in this state at all.

**Comment by panfunk** [comment]
Lobais wiki:
"Special Attacks: Astral Flow (summons an Avatar to use it with) for ~300-400 damage; both black and summoning magic."

![image](https://user-images.githubusercontent.com/36666121/54494118-45ef7400-48d7-11e9-965f-2b593de27573.png)

**Comment by godmode** [comment]
What does that mean? I don’t have the same context from which you’re posting this about.

**Comment by panfunk** [comment]
According to FFXI wiki from 2008, the Sacrarium NM Lobais is supposed to deal around 600 dmg with Astral Flow:
https://ffxiclopedia.fandom.com/wiki/Lobais?oldid=597789

The above screenshot was from fighting him yesterday, dealing almost 1800.

This problem is not limited to high level NMs with Astral Flow.
