### ISSUE TITLE
port windy airship boarding dialogue is incorrect if player does not have enough gil

### ISSUE THREAD

**Issue by Gravionblack** [EdenServer/community#4932]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Eden trying to zone to the airship in port Windurst it says I do not have a airship pass, but I do. I have normal and kazham.

**Comment by 59blargedy** [comment]
sorry, i dont understand where you're encountering the issue. is this upon clicking on the door inside the airship building, where you would normally purchase a ticket? or where exactly/with whom exactly is this issue occurring? can you provide some more details so we can help? also, can you file a gm ticket (through the help desk menu) so that they can help you immediately?

**Comment by Gravionblack** [comment]
Problem solved.

**Comment by 59blargedy** [comment]
resolved in April 18, 2022 patch
