### ISSUE TITLE
Prime Avatar fights are broken (damage is way off)

### ISSUE THREAD

**Issue by Hestichan** [EdenServer/community#4981]
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)
- [ x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
30181205_0

Prime avatar runs are currently just about impossible to do now as pet damage for some inexplicable reason is way down from what it normally was (which was normal damage)

Poison nails hits for around 40-60dmg where before it was in the normal range of 100-400 dmg.
Most other avatar lvl70 BPs (flaming crush, mountain buster etc) are hitting for 180-300 dmg, when they normally should be hitting around 500-1500 dmg.

Avatar melee hits would normally be 40-150 dmg (carby on lower end, fenrir on higher end). Now they are in the 10s and 20s per hit.

I fought Ramuh on both Lightningsday and on Earthsday and it was the same ridiculously low damage in both cases.

_As a side remark, I'd like to point out that it's very disconcerting that such a beloved job as Summoner seems to get unfair treatment on Eden, whether intentionally or not. We spend a long time to reach 75 so we can do things like prime runs for a little income and help others get their pets, but then that gets made practically impossible to do. The Weapon Skill "Spirit Taker" misses far too often and doesn't absorb nearly enough MP to make up for how expensive Blood Pacts cost to use.

I rarely want to play Summoner. It makes no sense to if one can't maintain MP for blood pacts to make soloing any fun, and prime runs are too difficult to be of any value, whether in terms of fun or income

I also know you will blow off my report here just like you blow off practically every other concern of mine. I don't know why I even bother. You will say "it's working just as intended" or "oh this is more like retail now somehow magically in our minds" You are deviating further and further from old retail and it's a shame. I'll move to another server like others, perhaps._

**Comment by Mozzy4Ever** [comment]
You marked the "I have provided proof of my claim" but didn't. 

![image](https://user-images.githubusercontent.com/11255886/163692634-831189e0-a023-46d0-93c4-3e7607dc5716.png)


On retail they had PDT that they were missing, which is why the damage is different now than what you're used to on Eden.

**Comment by Steam-arch** [comment]
Wasnt SMN soloing always somewhat niche on retail. Spirit taker at 3000% tp should restore a decent amount of mp, but havent tested it myself on eden.

Using day of the week/weather avatar is pretty much mandatory and you can swap to carby when you need to recover more mp. When/if phys BP tp reset gets fixed you can rotate IV spells in which saves ~50 mp per BP

**Comment by Slamm21** [comment]
I'd bet smn who would solo these on retail did magic BPs, they are low level opponents so they take big magic damage.
you could fight them naked without merits on rdm and a nuke wouldn't resist for example.

going to close this for now since we have no evidence, post if you get some.

**Comment by 59blargedy** [comment]
To close this out, if you have a concern and can provide proof of it, that will never be blown off. Quite literally, [thousands of changes](https://github.com/EdenServer/community/issues?q=is%3Aissue+is%3Aclosed) have been made as a result of people providing sources that show eden isn't accurate to era - this is an ever-evolving server and the staff works hard to make changes happen. We've given summoners considerable balancing changes over the years to bring them closer to era and are aware that even with so much time spent, it's still not fully dialed in, there's definitely still more to go. 

If there are valid claims here that you wish to back up with proof, please post and I will happily reopen the ticket. 
For spirit taker - here's some suggestions to help make a new report: check era vids, find sources that show what the mp return should be, compare to wiki and your eden results. JP wiki is an amazing resource too. Prove something is off and we'll 100% do something about it. Eden's ethos has always been era accuracy. PLEASE prove us wrong if it's not that way, so that we can bring it closer. For the PDT reported here, I personally tested the -PDT on retail and found it to be the case on avatars, so implemented it accordingly. These changes are not the whim of evil developers, but real people seeking to get as close to accurate as possible, spending hundreds of hours researching and testing changes to this game we all love.
