### ISSUE TITLE
Mourioche, mandy type mobs incorrect delay

### ISSUE THREAD

**Issue by blacknesscrows** [EdenServer/community#503]
I was roaming around the boyahada tree and attacked one of these mandragoras. The double attack was working, the damage seemed pretty high but it might still be right. What was not right was the delay between his "monk" attacks. One of these guys blasted through a 73-75 Courier Carrie like a hot knife through butter with his fast attacks.

**Comment by beauxq** [comment]
Ok. When doing research for this bug https://github.com/EdenServer/community/issues/339 , I was assuming mobs would have normal Martial Arts the same as players.

After more research, I find mob Martial Arts is not the same as for players.

As I mentioned in that bug, MA1 should be 384 delay.
(That was assuming a normal MA1 from 464 base delay. But now it seems base delay doesn't matter because MA is not normal for mobs.)
In this video:
https://www.youtube.com/watch?v=OueUflbAb2k
I measure MA3 to be 368 delay. (well outside of a measurement error of where normal MA would put it at 344)
In these videos:
https://www.youtube.com/watch?v=xx4VJdlRVRY
https://www.youtube.com/watch?v=wx-9KxPCDOY
I measure MA6 and maybe MA5 to be 364 delay.
So there is only 4 delay difference between MA3 and MA6.

So, I'm guessing for MA4 and above, it's capped at 364 or mobs.


I think this is what I'm seeing, for mobs:
MA1 is 384
safe to assume MA2 is 376 (halfway in between 1 and 3)
MA3 is 368
MA4 and above is capped at 364
