### ISSUE TITLE
Out of Era Holy Water Synth

### ISSUE THREAD

**Issue by bsgilber** [EdenServer/community#509]
I don't believe the use of the Trituration - KI was available for the creation of Holy Water x3 until after 2010. 

Prior to that, SE also nerfed the NPCable price of Holy Water considerably to combat RMT. I'm not sure if that is needed (warranted) on Eden, but the combination of having both the Trituration and full NPC sell price means that you can do the following, with the yields being NPCable prices:

```
Light Crystal x 1 = ~300
Distilled Water x 3 = ~10
Triturator x 1 = ~25
Total Cost: 335gil
-----------------------------
Yields:
x3  1050
x6  2100
x9  3150
x12 4200
```

**Comment by SleazyFFXI** [comment]
Light Crystals are 5K+ and never available on the AH,   just sayin lol

**Comment by godmode** [comment]
Thank you for reporting. Anyone who took advantage of this had their gil removed from its revenue.

**Comment by beauxq** [comment]
Not that it matters much, but just so people who see this issue page can understand:
The NPC price change for holy water was NOT because of RMT.
The price change was specifically because of adding this Trituration recipe. (Both changed in the same update.)
http://forum.square-enix.com/ffxi/threads/24155-June-14-2012-%28JST%29-Version-Update
