### ISSUE TITLE
Grimshell Shocktroopers Possible Incorrect Drop

### ISSUE THREAD

**Issue by edhooQQ** [EdenServer/community#5198]
I just did the BCNM60 Grimshell Shocktroopers in an attempt to get Vassago's Scythe, but I received a Kabrakan's axe instead (which I dont see listed as a potential drop on any Wiki). Is the Axe suppose to be a potential drop from this BCNM, or is the game bugged and I received the axe instead of the scythe? The vile elixer +1 I got also isn't listed as a potential reward either.

Client version: 30181205_0

![image](https://user-images.githubusercontent.com/37385471/182520592-d905b4c4-0d6b-4203-9049-56f036f3082c.png)

### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ x] I have provided my client version in the details. (type /ver into your game window)
- [x ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by 59blargedy** [comment]
resolved in september 21, 2022 update

**Comment by ThoseWhoFight** [comment]
This still seems to be an issue, just got similar drops to OP from same BCNM. Looks like it's still using Kindred Spirits drop pool. Is this actually accurate and wiki is just wrong? Also seems to still only be getting 4-5 drops instead of the 6 listed.

<img width="362" alt="image" src="https://user-images.githubusercontent.com/37572397/193232309-e6f455c9-6128-4d1a-bb4d-430037eb897c.png">
<img width="142" alt="image" src="https://user-images.githubusercontent.com/37572397/193232380-60eda6b2-d308-4aae-8609-026799d7dd3b.png">
<img width="137" alt="image" src="https://user-images.githubusercontent.com/37572397/193232415-d86c2ba1-a018-4906-9811-40d524480491.png">
<img width="215" alt="image" src="https://user-images.githubusercontent.com/37572397/193232465-62934888-bdc8-4a9b-b1f3-422c0c247ce2.png">

**Comment by 59blargedy** [comment]
yeah this is my bad, i thought the change got in but did not yet.

**Comment by 59blargedy** [comment]
I did resolve this in the previous update, though the droplist tables still need a quantity audit if i can get some help on retail

**Comment by 59blargedy** [comment]
Resolved in August 7, 2023 update
