### ISSUE TITLE
Sandy 2-1 cannot progress. 

### ISSUE THREAD

**Issue by Narzinor** [EdenServer/community#5206]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

NPCs in Sandoria Mission 2-1 in La Theine Plateau do not appear to have correct names and NPC Tayula locks up character when talking to after second line of dialogue. Cannot progress mission. 

Client ver: 30190305_0

https://classicffxi.fandom.com/wiki/The_Rescue_Drill#articleComments

**Comment by 59blargedy** [comment]
hey there, this is an issue with having the wrong client version. in order to progress, you'll need to reinstall eden. make sure you back up your macros first. if you are playing on another private server and wish to continue, you'll need to follow instructions in the discord in #tech-support on how to use both servers.
there are no issues with npcs when you have the correct client version.
