### ISSUE TITLE
Certain Combat Skills Not Skilling Up Where They Should Despite Not Being Capped

### ISSUE THREAD

**Issue by Matillais** [EdenServer/community#5266]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

This may be a different issue to what was seen in #1648 where swapping the weapons temporarily resolved the issue. I have already tried this and I do not return to receiving Sword Skillups. I am playing on a Lvl 7 THF, with a Sword Skill of 14 currently, and am receiving no sword skillups against Decent Challenge mobs. This is consistent against 4 consecutive kills as shown in the video links below (Apologies, they weren't available for viewing at time of issue being posted, they should be viewable now):

1. https://www.youtube.com/watch?v=MWHpJ0F6lyA
2. https://www.youtube.com/watch?v=SjCCkuvnGIg
3. https://www.youtube.com/watch?v=b7Mc5AHz7uY (1:53 for dagger skillup on first successful hit with the weapon)
4. https://www.youtube.com/watch?v=ncBFFgqS1JY

You can see in video 3 that. when swapping to the dagger in my inventory, I started receiving dagger skillups against the same Crawler. The lack of sword skillups received seems too consistent to be expected behaviour.

Ver is in screenshot 
![image](https://user-images.githubusercontent.com/114115072/191628709-42385deb-338f-4d8f-b660-9bd5d3e2203c.png)

**Comment by 59blargedy** [comment]
i cannot replicate this yet locally, so a clarifying q: if the mob is DC high defense, for example, are you receiving skillups? or is it all DC?

**Comment by Matillais** [comment]
I can't recall if any of the DCs had high defense yesterday. I just fought a Goblin Thug that was DC HD and I started getting sword skillups. Afterwards I fought a Crawler that was just DC and got none. I could try to continue testing this further and will have more videos to provide later, too, if needed.

**Comment by falzum** [comment]
Seems like a misconception in how skill ups work. A mob being tw, ep, DC, em, VT, or it makes no difference. 

It's a simple check of your skill in that weapon vs the mobs level.

The highest you can skill up on a particular mob is roughly the (mobs level x3). So at 14 skill that's roughly a level 5 mob(14/3=4.6).

The closer you get to the cap, the more rare skill ups become. I recommend using the checker addon which tells you a mobs exact level as well as its normal check value.

**Comment by ConteAlmaviva** [comment]
> The highest you can skill up on a particular mob is roughly the (mobs level x3). So at 14 skill that's roughly a level 5 mob(14/3=4.6).

To be more specific, I believe the highest you can skill up on a target is whatever your skill cap would be at that target's level.  For example, if I'm a THF using a sword on a level 5 crawler, the highest I can skill up off of that crawler is whatever THF's sword skill cap would be at level 5.  THF has D rank in sword; at level 5, D rank skills cap at 14.  To skill it up any further, I would need to fight a mob that's level 6 or higher.

The skill calculator at https://ffxi.allakhazam.com/db/skillcalc.html is mostly accurate--there are a few Eden custom things like PUP H2H skill and a few instances where I think retail might have diverged from era, or it simply has the wrong skill rank for a particular job/skill combination.  You can select the job you're playing and fill in the level of the mob you're fighting (rather than your own level), which you can get with the checker addon; that will tell you the highest skill level you can expect to get from that mob.

**Comment by Matillais** [comment]
Thanks @falzum and @ConteAlmaviva , your comments combined make sense to me and the use of the checker addon confirms the difference between skill gains based on enemy level instead of their rating after further testing.

I had been unaware there was this softcap on skill gains, and only aware of the hardcap (blue number) at the time.
Thanks for everyone's contribution on this, glad it wasn't a bug.
