### ISSUE TITLE
2-3 Dragon Breath

### ISSUE THREAD

**Issue by bobusffxi** [EdenServer/community#5412]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

The dragons in the 2-3 nation BCNMs are possibly using the wrong breath TP skill and are dealing too much damage with the breath they do use. 

Based on my own experience, Dread Dragon in Horlais Peak is using Flame Breath, and Dark Dragon in Waughroon Shrine is using Wind Breath. Linked below is a bunch of log screenshots of Eden damage values and era youtube videos with timestamps for the dragons only using Poison Breath and lower average damage. 

https://imgur.com/a/SErgilr

https://youtu.be/RYJHIaUj7QE?t=39
https://youtu.be/hGeVjPz8PAU?t=484
https://youtu.be/YPlr01nNdUM?t=400
https://youtu.be/O_zPe6QBLRk?t=93

version 30181205_0

**Comment by E5una** [comment]
"Using the breath immediately on pull may also be incorrect." -This part can be removed. Its been researched already and known to be possible for the dragon to open with a TP move, in addition the first video you linked starts with a breath weapon, so we know that part is accurate.

Per our discussion in discord, the focus is really on the fact that we can't find evidence of other non-poison breaths in any of the videos online (I watched 11), and that the cap on the breath attack seems much lower than the 250 dmg flame breath cap on Eden or the 400ish damage cap on wind breath.

![image](https://user-images.githubusercontent.com/13668758/204543671-6a65c811-46cb-427e-9f62-29455bacbc0b.png)

![image](https://user-images.githubusercontent.com/13668758/204543694-77f07b20-64f4-42d5-a4de-4b9b07e8b094.png)

This is the only one I found with 100% HP breath usage (the first video linked in the github)

![image](https://user-images.githubusercontent.com/13668758/204543845-dfea0c5a-0847-4876-a991-faa24a486115.png)

It appears to deal 63 damage, but the BLU in the video has metallic body on. My guess is that its cap is 100 but I'm having trouble calculating it exactly because JPwiki/Bgwiki/Ffxiclopedia all disagree on the formula for Metallic Body. Metallic Body seems to be 30-34ish stoneskin at that level, but I can't be sure due to the inconsistent formulas.

**Comment by bobusffxi** [comment]
Edited the post. Thanks for pointing that out.

**Comment by 59blargedy** [comment]
can confirm from recent retail testing that the dread dragon uses only flame breath, so removed poison in last patch. with the adjustments in the tp fixes this year including variable breath caps in addition to the change in may 2023 update, this one is fully complete
