### ISSUE TITLE
Nidd Drops

### ISSUE THREAD

**Issue by tectal831** [EdenServer/community#554]
M Body {Do you need it}

**Comment by godmode** [comment]
with th3 on test server:
1. m.body
2. a.body x2
3. m.body
4. m.body
5. m.body
6. n.legs x2
7. a.body, m.body
8. m.body
9. n.legs x2
10. a.body

I looked at the drop table and it was skewed toward m.body dropping so that is fixed--but it wasn't so much so that it would be nearly impossible to get other abjurations. I have adjusted it though. Should be live Monday.
