### ISSUE TITLE
Arrapago Remnants QQ Treasure Hunter floor 3 looses hate even with dot's

### ISSUE THREAD

**Issue by Maesedanielot** [EdenServer/community#5712]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by 59blargedy** [comment]
the treasure hunter will lose hate with dots on retail as well. you have to be within a certain distance of him (which players would often achieve by standing against the wall as mentioned on wiki)
there are some issues with his pathing but this is not one of them.  just saving you some time of typing it out.

**Comment by 59blargedy** [comment]
yeah it should work, but there is a ~3-5 second window where the mob logic could hit and you're out of range. this is also mentioned in bg threads as a weird anomaly. if you're consistently not able to do it, we will definitely reopen the ticket but as of 2 days ago this mechanic worked.

**Comment by Lilswitche** [comment]
When I ran this the other night the “run back” behaviour was not as expected with the logic on retail. Currently on Eden, when the QQTH procs their return behaviour towards a player, they stop well short of the player and immediately start running away again; this leaves no opportunity for the player to do meaningful damage. The expected behaviour is that the QQTH should run up to the player and melee meleeing them or mobskilling for a small amount of time. 

The expected behaviour is captured from retail in this video: https://youtu.be/UOTPJ8zz1AQ at around minute 25. You’ll see Tacocat stand still with the QQTH running away, on it’s path back it notices the player and engages them. 

Also, on initial aggro, the QQTH should take pause for a second or two with an engaged stance before running away. It appears to begin it’s runaway phase much quicker on Eden.
