### ISSUE TITLE
Myxomicete's TP Move [Silence Gas] still deals significantly High Breath Damage

### ISSUE THREAD

**Issue by BlueMageNahida** [EdenServer/community#5715]
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Myxomicete, a Funguar Monster from The Sanctuary of Zitah, is currently dealing tons of damage with its TP Move [Silence Gas]
It used to be way higher when the numbers got tweaked, but even so, it's still pretty high damage.

**Comment by 59blargedy** [comment]
the numbers are according to studio gobli
https://w-atwiki-jp.translate.goog/studiogobli/pages/26.html?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en
can see here that the move does 250+ damage in a level 30 cap bcnm at less than 100%, i cant find non bcnm evidence but this aligns with the damage value of hp * .25 as their total hp is ~1k and it was around 80%
https://www.youtube.com/watch?v=Cfbi6Kl6NXc
if you find evidence to the contrary, can file a bug report with that information. the caps were not determined so that could be something that could make a difference, but without proof going with the documented proof we have.
