### ISSUE TITLE
Ququroon not trading for Nashmau Stew

### ISSUE THREAD

**Issue by ekoya** [EdenServer/community#5803]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

version 30181205_0

1. Start the quest Rat Race and get to the step where you need to talk to Ququroon in Nashmau to get the Nashmau Stew.  
2. Talking to Ququroon the first time will get the cutscene for the quest Cook-A-Roon.
3. Talking to Ququroon a second time gets the cutscene for Rat Race.
4. Talking to Ququroon after that just gives the reminder about what fish you need:
![image](https://github.com/EdenServer/community/assets/95725249/eae8c32f-e80c-43c6-a3dd-70e9f2dc2f11)

At this point, I have both quests flagged in my quest tracker:
![image](https://github.com/EdenServer/community/assets/95725249/911a691c-b654-4d50-9a50-f5b812465b82)

5. Trade the 5 requested fish to Ququroon:
![image](https://github.com/EdenServer/community/assets/95725249/504d2bd0-4768-4089-b320-63e127e4d338)

Nothing happens. No Stew, no chat message, still have all the fish in my inventory.

Tried this on a second character and got the same results, even attempting to get the Nashmau Stew for Cook-A-Roon before getting the cutscene for Rat Race at Ququroon

**Comment by 59blargedy** [comment]
Resolved in November 19, 2023 update.

**Comment by Pingletown** [comment]
I just tried this and have experienced the exact same error as the original post,

**Comment by 59blargedy** [comment]
this should be more firmly resolved now. silly fish.

**Comment by Tavnazian** [comment]
I suggest reopening this as i just had the error, with new info.

I was doing Rat race and when i got to the Ququroon step, he instead of progressing it, completed "Cook-a-roon?" WITHOUT it even being flagged. so it seems that he's all at once, flagging cook-a-roon?, completeing cook-a-roon?, and progressing rat race. what's more, is because it's actively progging cook-a-roon? and passively also progging rat race, he can(and did for me) FAIL to make the stew and gave me nothing. not realising what had happened, i had ls mate fisherman get me the fish again, and then i got stuck here, with him asking for the 5 fish but not taking them. GM gave me the stew and KyoKyoroon accepted it.

https://ffxiclopedia.fandom.com/wiki/Rat_Race?oldid=612869
https://ffxiclopedia.fandom.com/wiki/Cook-a-roon%3F?oldid=621420

ver 30181205_0

**Comment by Tavnazian** [comment]
so it looks like i actually did flag cook-a-roon? when i approached him while trying to progress rat race. and everything in this video happened(except he failed to make the item). https://www.youtube.com/watch?v=j_u-dtEpESg
and it just counted as progress for rat race at the same time. which it should not.
