### ISSUE TITLE
Convergence not wearing under AoE status-only spells

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#5869]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

/ver 30181205_0

Convergence isn't being removed when AoE debuff-only BLU spells are used as shown in this screenshot:
![image](https://github.com/EdenServer/community/assets/11255886/fb29f9a4-7b31-4fab-a501-48c364cce58f)
However, AoE debuff spells aren't getting the bonus MACC that Convergence should be giving.
Convergence **is** removed if an AoE spell does both damage **and** status effect, though.

Expected behavior per https://ffxiclopedia.fandom.com/wiki/Convergence and https://wiki.ffo.jp/html/12121.html is that Convergence is removed, and only the +MACC is given to that spellcast (status effect potency isn't changed)

**Comment by 59blargedy** [comment]
resolved in July 5th, 2024 patch

**Comment by ProtomanEXE** [comment]
Looks like this might be happening again. Logs show I used "Convergence" into "Frightful Roar". The target was hit with the spell but my status of "convergence" did not wear off until its timer fully dissipated instead of on use of "Frightful Roar"
![Screenshot 2025-01-14 145349](https://github.com/user-attachments/assets/a545eff1-b7d3-4c61-bc78-d5a2573e6e5e)
![Screenshot 2025-01-14 150101](https://github.com/user-attachments/assets/9e52d9f6-f7c2-425a-a240-c67366d7539d)
