### ISSUE TITLE
SMN Avatar's completely ignoring Retreat command

### ISSUE THREAD

**Issue by Avarghaladion** [EdenServer/community#5903]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

30181205_0

Since the latest round of patches, Retreat is broken. Pets are ignoring the Retreat command altogether (not even attempting to disengage from target, just continuing on as if no command was given) and it's currently impossible to reposition an engaged pet by any means. 

Steps to reproduce:

1. Summon pet.
2. Assault mob.
3. Wait for pet to tag mob.
4. Attempt to retreat.
5. Nothing happens. Pet continues attacking as though no command was given. 

The correct behaviour we should be seeing is that if a mob is attacking the pet, it should Retreat as normal; the only instances where a mob should be re-engaging is if a mob has the SMN at the top of its hate list (over any pet or other party member), in which case the pet would engage that mob following the retreat. The Retreat command is not supposed to do nothing.

**Comment by maxdecphoenix** [comment]
just want to second this bug.  I noticed it the evening of the 5th after the Update, due to Ramuh behaving weirdly during some Thunderspark horde-farming. but haven't had the time to submit a bug report.    

if the SMN Rage-pacts a mob with avatar, the avatar is supposed to sit there and be beat on til it's dead. Never attacking. However, I noticed that Ramuh would auto-attack after the pact, then continue to target and attack every mob in the horde (that was targeting him), until they were all dead.  With no assault command. 
  
  I.e. 
  1: use an alt to build a horde of mobs by low emnity means, or sound/sight/casting links/agro.
  2: SMN calls ramuh
  3: Ramuh is in follow mode because no emnity on SMN. Use thunderspark on a mob
  4: all the mobs, that survive, will target/attack ramuh.
5: ramuh continues to randomly and individually target and kill mobs until they're all dead. 

Step 5 isn't supposed to happen.  It's very helpful, currently, but it's not how it's supposed to be.  In this example Ramuh is historically supposed to do Thunderspark, then sit there being beat on til given a command.  This behavior is related to the 'ignoring retreat' bug.   

It seems that when the avatars take hate (i.e. the focus of an enemy), it's triggering bodyguard mode.  Even when you retreat, the avatar is instantly detecting that it's being targeted and goes right back into bodyguard mode so fast that it doesn't even move, nor appear to stop attacking.  And if they're capable of AOE attack, and pull hate on multiple mobs, it continually triggers bodyguard mode.   I'd bet when the code was updated, the target the game is supposed to be looking for to initiate the avatar into bodyguard mode erroneously got changed from master (i.e. the smn) to self (the avatar).

Pre-post edit.
While writing this i convinced myself that's the issue, and i figured a good way to confirm it is fight a mob with a partymember who can easily take hate off avatar, and when/if the avatar isn't the primary focus of the mob, see does the avatar respond to retreat.  That would confirm the game is using the incorrect <target> to enter the avatar into bodyguard mode.

I did this quick test: 
made party smn/whm thf/nin.  warped to cape terrigan.  called carbuncle.  assaulted a lizard behind the OP.  ordered carbuncle to retreat. Carbuncle ignored.  Sneak Attacked lizard with thf, and pulled hate.  Thf now the focus of mob.  ordered carbuncle to retreat. Carbuncle retreated.  

So, yea.  the game is using the incorrect <target> variable  to enter the avatar into bodyguard mode.  It's checking is the avatar being targeted, not the master.   You're welcome Eden.

**Comment by maxdecphoenix** [comment]
https://www.youtube.com/watch?v=w7emYFmB3gE

**Comment by Avarghaladion** [comment]
A few times now I've also observed Ifrit commencing auto-attack on a target after it pulled hate with a Flaming Crush despite the SMN themselves never being close to top of hate table. It definitely seems, post-patch, that pets are incorrectly self-identifying as PCs for the purposes of retreat and sentinel behaviour.

**Comment by nfontanait** [comment]
Similar issue on BST. "Stay" command does not function at all.

**Comment by 59blargedy** [comment]
resolved by another dev in July 30, 2024 update.
