### ISSUE TITLE
Enlight not working correctly

### ISSUE THREAD

**Issue by Avarghaladion** [EdenServer/community#5945]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [/] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

30181205_0

Steps to reproduce:

1. Craft an Enlight-enchantment weapon (tested with Sacred Wand).
2. /checkparam yourself & note accuracy.
3. Activate enchantment.
4. /checkparam yourself and note no change in accuracy (verified this issue persists even after attacking a mob and starting the Enlight "countdown").
5. Begin attacking a mob.
6. Note that Enlight damage begins at an arbitrary value then decreases (as it should) by 1-per-hit
7. Effect stops decreasing at 1. Never hits 0 and wears off like it should; just keeps hitting for 1 thereafter until duration expires.

Issues:
- The effect should decrease to 0 then wear off after x hits, where x is the initial potency of the buff.
- Player accuracy should be increased by the buff's current potency at any given time.

Potential issues:
- Buff isn't calculating potency based on Divine Magic skill. I can't recall if these Enlight enchantments were fully true-calcs or fixed but I don't remember having this issue with such low initial potency with them in era.
- Effect is removed if the weapon is removed. Can't remember from era if this is normal but all other Enspell enchantments remain active when the associated equipment is removed so it seems abnormal.

**Comment by 59blargedy** [comment]
the enlight weapons were in the game well before the spell, so do not function at all like the spell - even with the enchantment active, and even on current retail (just got around to testing to make sure). Accuracy is unaffected when using the enlight enchantment on retail, damage is static for the life of the enchantment, and the buff is removed if the weapon is removed. Divine magic skill has no effect: at 140 and 357 respectively, there is no change in the enspell damage, which matches other weapon enchantment effects. The bug is the decreasing dmg - that's covered by some other reports so i'll close this one out.
