### ISSUE TITLE
Promyvion Dem Issue

### ISSUE THREAD

**Issue by tectal831** [EdenServer/community#60]
After a wipe, boss in Promyvion Dem did not spawn adds second fight. Not sure if it was lucky, or bugged

**Comment by Lilswitche** [comment]
It only spawns them when it uses Fissure.  I don't recall getting any in our fight either, but we did use some anima on the NM.

**Comment by gweivyth** [comment]
To add on to this, we wiped in the attempt due to some bad luck, (thanks, Berserk...) but when we went back in the second time we saw ZERO Fissures, where in the first fight it seemed like that was the only move that he used under 20%.  

I don't know why the two attempts would be related at all since they should be two separate instances, but just thought I would mention this for troubleshooting purposes in case it was somehow relevant?
