### ISSUE TITLE
Unexpected Treasure Quest not working

### ISSUE THREAD

**Issue by rujind** [EdenServer/community#609]
https://ffxiclopedia.fandom.com/wiki/Unexpected_Treasure

The part with the moogle works where you get the small teacup KI, but nothing afterwards.

**Comment by Shoruto** [comment]
Did you talk to Morunaude at least twice till he talks about Calovour?

**Comment by rujind** [comment]
I don't think he ever does.

**Comment by Althaia** [comment]
I encountered this as well. The Mog gave me the key item from the furnishing, but after talking to the person at the furniture store -- actually, I talked to both of them, MULTIPLE times -- I wasn't able to get the text required to proceed.

So I went to the NPC in the Cathedral hoping I could trade the item to it and complete the quest, but nope, it's a no-go.

So it looks like this quest is only partially implemented or otherwise got stuck partway through.

**Comment by 59blargedy** [comment]
quest implemented sept 27 2020
