### ISSUE TITLE
Bomb Toss OP Zi Tah Op

### ISSUE THREAD

**Issue by SaberSuper** [EdenServer/community#673]
Sooo Uhh is Bomb Toss supposed to 1 shot? Bar Fire was cofirmed applied.

![supersaber_2019 01 05_052249](https://user-images.githubusercontent.com/44216595/50723344-52bb4480-10aa-11e9-9200-fb88e6265945.png)

**Comment by godmode** [comment]
It’s possible to but not likely. Will look into it again. Can you tell me the level you guys were synced to?

**Comment by Caelic** [comment]
Exact same thing happened to my party last night in Yuhtunga Jungle synced to 26. Goblin Smithy snackbar'd us, 4 people were 1shot. Seems like it only happens when the bomb toss also kills the goblin. So it's definitely not fixed.

**Comment by godmode** [comment]
For this stuff I really need more details. Testing this I had no issues and others have reported it’s better as well. So HP of goblin, your level and HP max, zone, gob name, et cetera and so on and so forth. For bug tickets vague reports = longer dev time and possibly not even getting to it because investigation takes time away from other development

**Comment by gweivyth** [comment]
@godmode the easiest place to duplicate this would be Bibiki on Hobgoblins or Zi'Tah when sync'd to 31.  We can do it on live or test server if you want, but I've had this happen quite a bit too.  Goblins are generally widely avoided because suicide bombs are a wipe about 80% of the time unless you have Rampart.  Barfire does seem to help but not always.

**Comment by Caelic** [comment]
@gweivyth Barfira increases chance to resist (half damage, quarter damage, etc) so if bomb toss one-shots four of your party members (like it did in my Yuhtunga party) it likely saved your party from having 5 killed instead, maybe even 6. I think barfire is working, it's just luck related.

**Comment by godmode** [comment]
@gweivyth can you let me know which goblins are causing the high damage? Like the actual name of them as well not just the subfamily or level. Reason why is the job of the goblin and other data

**Comment by Caelic** [comment]
@godmode Goblin Smithy, the one nearest to the Kazham zone line, is the one that blew up my 26 sync party.

**Comment by SaberSuper** [comment]
I believe we were sync'd to lvl 33 or 34
    On Tuesday, January 8, 2019, 10:30:57 AM EST, Caelic <notifications@github.com> wrote:  
 
 
@godmode Goblin Smithy, the one nearest to the Kazham zone line, is the one that blew up my 26 sync party.

**Comment by gweivyth** [comment]
> @gweivyth can you let me know which goblins are causing the high damage? Like the actual name of them as well not just the subfamily or level. Reason why is the job of the goblin and other data

I'll go do a tour and take some notes.  I know for 100% certain that all of the Hobgoblins do this, it's been an issue EVERY time we've pulled one in Bibiki regardless of job.  I'll go find names though.
