### ISSUE TITLE
Can't log on slot 4 character

### ISSUE THREAD

**Issue by Jowy68** [EdenServer/community#743]
All my characters from slots 1-2-3-5 are working properly.

But I get POL-0001 on character named Jeanne on slot 4, this has been going on for more than a day.

(tried rebooting ashita, restarting comp, etc.)

**Comment by Imakyl** [comment]
I'm having the exact same issue.  User name is Imakyl_Yufast and the 4th character's name is Fishybox.    To add more details, the login issues began right after I created a 5th character under the account.  I attempted to delete the 5th character (Gearbox) to solve the problem, but the process gets hung up on "Deleting from Lobby Server."   Requesting help with logging onto Fishybox and/or deleting Gearbox.   Fishybox has a lot of items I'd like to get back.  Thank you, and if there's any way I could donate to this amazing project, please let me know!

**Comment by gweivyth** [comment]
You're not supposed to be making this many characters on one account, DSP has known issues with character slots past the first couple.  There really isn't ever any reason to do so when accounts are unlimited and free.  Please make your new characters on different accounts.

**Comment by godmode** [comment]
What Gweivyth meant to say is everything he did except for the first half of the first sentence. :p

**Comment by Imakyl** [comment]
Is there any way to delete my 5th character (Gearbox) on your end, since deletion is temporarily disabled?  I read online today that that resolved the login issues for a different private server.  The character I cannot log in to is holding all the moat carp I was saving for Lu Shang quest. 

I greatly apologize for the inconvenience; I have only played on retail before.  Again, if there's anything I can do to contribute to the project, please let me know.

**Comment by bkesecker** [comment]
For reference: https://github.com/DarkstarProject/darkstar/issues/497
