### ISSUE TITLE
Logging in Yhoator Jungle

### ISSUE THREAD

**Issue by gilbezach** [EdenServer/community#822]
Currently you can log out of era wood here (Aquilaria Log and Kapor Log) this would not be an issue but they vendor for 0 gil. Is it possible for them to simply be removed to make logging here better?

**Comment by tengokujin** [comment]
I am unsure why this issue was closed, considering that the issue persists in the form of butterpears.

Is it because they were not a part of the initial report?

version 30181205_0

![zidNUiW 1](https://user-images.githubusercontent.com/55920387/93167658-151c1500-f6ef-11ea-860d-1cdf08fe6377.png)

![jyZh7Sw 1](https://user-images.githubusercontent.com/55920387/93167687-26fdb800-f6ef-11ea-9786-14da88a86267.png)

In any case, FFXIclopedia shows that butterpears were added in 2011, as a synthesis material for a skillup food.
