### ISSUE TITLE
Inventory 29/30 yet still lost item

### ISSUE THREAD

**Issue by Shoruto** [EdenServer/community#824]
My inventory showed 29/30 however I had a fire crystal and beastman seal in my treasure pool.  When I lotted on the fire crystal, it said I ended up losing it due to no space.

**Comment by rujind** [comment]
I've seen this bug before, I'm not sure what causes it. I don't know if it can be fixed in-game by resorting inventory and such, but I know relogging fixes it. I think it's probably autosort malfunctioning somehow (basically the client and server becoming desynced and your inventory was actually full on the server due to autosort not working)
