### ISSUE TITLE
OP Warp NPC States Region Control Incorrectly

### ISSUE THREAD

**Issue by bkesecker** [EdenServer/community#827]
Outpost warp NPC states region is not under my nation's control despite the conquest showing the opposite.  Unsure if this has an affect on the cost, which was 20 CP to port (for example, from Bastok to Valkrum Dunes).

**Comment by archfiendrubicante** [comment]
https://i.gyazo.com/c18029ebfb4775436c63a9521e5738ea.png

Since the NPCs report the opposite of whether or not your region has control, I believe that this specific issue can be fixed by adding the "!" (NOT) operator to the line of code that governs determining whether or not a nation has control of an area in regards to these three specific NPCs. (Those NPCs being Conrad in Bastok Mines, Jeanvirgaud in Northern San D'Oria, and Rottata in Port Windurst)

This would flip the logic in the statements that determine control and should cause the text to output the proper result.

**Comment by kochiemonster** [comment]
I think they just say that if your nation is not on top of the regional influence bar as it stands. Take Derfland for example, right now Windurst owns it, but right now they are at the bottom of the influence bar.

**Comment by archfiendrubicante** [comment]
I believe that's incorrect. Right now Windurst has complete control of Sarutabaruta, and is dominant in the area, but the outpost warp NPC states that Windurst does not have control of Sarutabaruta.

Flipping the logic with a (!)NOT operator in the statement to determine which message to output would properly reflect control of the area.

**Comment by archfiendrubicante** [comment]
Here's a list:
https://i.gyazo.com/7fd4d01a130580e1e57a1e12988662e9.png

Note that each of the areas when checked reports that the area is NOT under windurst control(when they in actuality are under windurst control)

A check of the opposite reveals the same thing, with one interesting example that stands out:
https://i.gyazo.com/b0d0046f9d2dbcde50fe88d568faad1d.png

In Li'Telor, Qufim Island, and Ronfuare; Li'Telor and Ronfuare report that the areas ARE under Windurst control when they are not. HOWEVER, Qufim Island properly reports the status of the area as "Not Under Windurstan Control"

**Comment by archfiendrubicante** [comment]
Whatever lines of code are present when describing Qufim island are the proper lines to determine when an area is under your nations control, the rest are reporting the opposite.

**Comment by InoUno** [comment]
I've made a fix for this, and it has been merged into release of topaz: https://github.com/project-topaz/topaz/pull/608
