### ISSUE TITLE
Blast from the Past - Quest is Broken

### ISSUE THREAD

**Issue by ultimazero** [EdenServer/community#834]
Unable to spawn Ichorous Ire, ironically I can't finish the SMN AF weapon quest until I finish Blast from the Past because of another bug with Koru-Moru the NPC.

**Comment by ultimazero** [comment]
I found out that I can spawn him at different fossil rocks than the guide on the wiki says. Can close this ticket (although the fact I cant finish SMN AF without beating this quest is still a bug)

**Comment by Althaia** [comment]
Well this is odd, because I was able to successfully spawn Ichorous Ire from the exact same fossilized rocks as indicated in the guide (I use FFXIclopedia; I know it's not era-accurate but a lot of what they say still applies).

The wiki I used did say that you'd be able to spawn the quest even if you hadn't flagged it, though, and that's probably false for Eden/era, because I was there with a friend who was trying to get the lapis coral key item for Windurst Mission 2-1.

He clicked on Ichorous Ire's fossilized rocks many times as we spent three hours in the Maze trying to help him get the coral (he went back later and eventually got it). He never spawned Ichorous Ire from any fossilized rocks in the Maze.

I, however, did have Blast from the Past flagged and only had to click on Ichorous Ire's fossilized rocks once to spawn the NM.

I, too, was doing Windurst 2-1, though I already had my coral, if that matters.

In any case, this issue was opened in January, maybe you guys fixed something in the meanwhile. Just wanted to report that it all worked as intended when I did it in August.

**Comment by bkesecker** [comment]
Thanks for following up with so much detail.  Unfortunately, there is a bug that affects all quests and missions that rarely fails to record progress, but some are more frequent than others because the finish event fires for many players at once and is not protected from that scenario.  Not unavoidable, but problematic to fix for all quests/missions simultaneously.  Some counter measures have already been implemented and have been working in a large majority of the cases.

And, of course, there are the many places where quest A blocks quest/mission B, which requires reforming the original logic for each NPC.  Those are being handled on a case-by-case basis at this time.

Thanks again!

**Comment by KnowOne134** [comment]
Working on quest block code in quest rewrite
