### ISSUE TITLE
 [Sheep in Antlion's Clothing ENM] Tuchulcha's movement is incorrect

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#906]
On my most recent run I just stayed at the entrance and waited for Tuchulcha to repop at his original spot, and he eventually did so every time after a short wait, maybe about 1-2 minutes. I was also able to hear his footsteps skittering underground for a moment every time before he would re-emerge at this spot.
I hypothesize that something may be causing him to revert back to his original position after he's been underground for a given period of time.

**Comment by Mozzy4Ever** [comment]
Can confirm he definitely sandpits and moves to one of his locations, but will walk back to his original point. You can intercept it's walk back by listening for it moving, and which point it will sandpit you. I'm guessing this is because sandpit wipes the enmity list so it thinks that the participants have left or died so it resets back to it's original point. Maybe a check is needed so that if there's someone in that BCNM, it's bound until it Pit Ambushes?
