### ISSUE TITLE
Setting blue magic doesn't trigger spell cooldown

### ISSUE THREAD

**Issue by Arlen90** [EdenServer/community#993]
At the moment, you can change spells on the fly. Even in combat. Just change your set spells and use them. There used to be a 1 minute (I think?) lockout, where you were unable to use any blue magic after changing set spells. Not sure if this is intentional or not currently, but it's potentially very strong / OP if kept like this in the future. You could just have full DPS set spells/job abilities on, then equip a dispel spell, use it, and unequip it again.

**Comment by jmcmorris** [comment]
This was not intentional and will be fixed. Thank you for reporting!

**Comment by StriderClerix** [comment]
Watching someone stream on Eden today, and I noticed this was still able to be abused.  

https://ffxiclopedia.fandom.com/wiki/Category:Blue_Magic?oldid=216281

You can reference that from March 2007 to see: 

> 
"Please be aware that any time blue magic spells are set, the blue mage will be unable to cast any spells for 1 minute."

**Comment by Volkaru** [comment]
It hasn't been looked at since jmcmorris last looked at it early this year. We even tried packet capturing the mechanic from retail and couldn't figure out an easy way to implement it. (The packets pretty much showed nothing even happening) It's still going to be worked on. Probably whenever an entire BLU rework happens.

**Comment by rude-jerk** [comment]
Resolved in patch on December 7, 2020.
